// النصوص العربية لواجهة التطبيق.
export default {
  'app.name': 'تاريخ العالم',
  'app.description': 'تاريخ العالم من عصور ما قبل التاريخ حتى الحاضر: العصور، الموضوعات الشاملة، الخط الزمني، المسرد، الاختبار، البحث والمفضلة. يعمل دون اتصال بالإنترنت.',
  'app.skipToContent': 'الانتقال إلى المحتوى',
  'app.brandAria': 'تاريخ العالم – الصفحة الرئيسية',
  'app.install': 'تثبيت التطبيق',
  'app.installed': 'تم تثبيت التطبيق',
  'app.loading': 'جارٍ تحميل المحتوى …',
  'app.loadFailed': 'تعذّر تحميل المحتوى',
  'app.retry': 'إعادة المحاولة',
  'app.error': 'خطأ',
  'app.update.available': 'يتوفر إصدار جديد',
  'app.update.action': 'إعادة التحميل',

  'nav.home': 'الرئيسية',
  'nav.epochs': 'العصور',
  'nav.timeline': 'الخط الزمني',
  'nav.themes': 'الموضوعات',
  'nav.glossary': 'المسرد',
  'nav.quiz': 'الاختبار',
  'nav.bookmarks': 'المفضلة',
  'nav.more': 'المزيد',
  'nav.search': 'بحث',
  'nav.aria.main': 'التنقل الرئيسي',
  'nav.aria.bottom': 'التنقل',

  'lang.label': 'اللغة',
  'theme.toggle': 'تغيير نظام الألوان',
  'theme.toast': 'نظام الألوان: {name}',
  'title.page': '{title} – تاريخ العالم',

  'year.bc': '{n} ق.م',
  'year.ad': '{n} م',
  'year.approx': 'نحو {s}',
  'year.unknown': '؟',
  'year.today': 'اليوم',

  'unit.event.zero': 'حدث',
  'unit.event.one': 'حدث',
  'unit.event.two': 'حدثان',
  'unit.event.few': 'أحداث',
  'unit.event.many': 'حدثًا',
  'unit.event.other': 'حدث',
  'unit.person.zero': 'شخص',
  'unit.person.one': 'شخص',
  'unit.person.two': 'شخصان',
  'unit.person.few': 'أشخاص',
  'unit.person.many': 'شخصًا',
  'unit.person.other': 'شخص',
  'unit.term.zero': 'مصطلح',
  'unit.term.one': 'مصطلح',
  'unit.term.two': 'مصطلحان',
  'unit.term.few': 'مصطلحات',
  'unit.term.many': 'مصطلحًا',
  'unit.term.other': 'مصطلح',
  'unit.theme.zero': 'موضوع',
  'unit.theme.one': 'موضوع',
  'unit.theme.two': 'موضوعان',
  'unit.theme.few': 'مواضيع',
  'unit.theme.many': 'موضوعًا',
  'unit.theme.other': 'موضوع',
  'unit.epoch.zero': 'عصر',
  'unit.epoch.one': 'عصر',
  'unit.epoch.two': 'عصران',
  'unit.epoch.few': 'عصور',
  'unit.epoch.many': 'عصرًا',
  'unit.epoch.other': 'عصر',
  'unit.entry.zero': 'عنصر',
  'unit.entry.one': 'عنصر',
  'unit.entry.two': 'عنصران',
  'unit.entry.few': 'عناصر',
  'unit.entry.many': 'عنصرًا',
  'unit.entry.other': 'عنصر',
  'unit.hit.zero': 'نتيجة',
  'unit.hit.one': 'نتيجة',
  'unit.hit.two': 'نتيجتان',
  'unit.hit.few': 'نتائج',
  'unit.hit.many': 'نتيجةً',
  'unit.hit.other': 'نتيجة',
  'unit.question.zero': 'سؤال',
  'unit.question.one': 'سؤال',
  'unit.question.two': 'سؤالان',
  'unit.question.few': 'أسئلة',
  'unit.question.many': 'سؤالًا',
  'unit.question.other': 'سؤال',
  'unit.region.zero': 'منطقة',
  'unit.region.one': 'منطقة',
  'unit.region.two': 'منطقتان',
  'unit.region.few': 'مناطق',
  'unit.region.many': 'منطقةً',
  'unit.region.other': 'منطقة',
  'unit.attempt.zero': 'محاولة',
  'unit.attempt.one': 'محاولة',
  'unit.attempt.two': 'محاولتان',
  'unit.attempt.few': 'محاولات',
  'unit.attempt.many': 'محاولةً',
  'unit.attempt.other': 'محاولة',

  'heading.events': 'الأحداث',
  'heading.persons': 'الأشخاص',
  'heading.terms': 'المصطلحات',

  'century.earliest': 'قبل 10,000 ق.م',
  'century.bc': 'القرن {n} ق.م',
  'century.ad': 'القرن {n}',

  'ui.milestone': 'حدث بارز',
  'ui.bookmark.save': 'حفظ',
  'ui.bookmark.saved': 'محفوظ',
  'toast.bookmark.added': 'تم حفظ المفضلة',
  'toast.bookmark.removed': 'تمت إزالة المفضلة',

  'home.intro': 'جميع الموضوعات الأساسية من الماضي، من أول البشر حتى يومنا هذا. مرتّبة حسب العصور والموضوعات الشاملة والمناطق، مع خط زمني ومسرد واختبار.',
  'home.stat.quiz': 'أسئلة الاختبار',
  'home.cta.epochs': 'استكشاف العصور',
  'home.cta.timeline': 'الخط الزمني',
  'home.cta.quiz': 'بدء الاختبار',
  'home.install.title': 'التثبيت كتطبيق',
  'home.install.ios': 'في Safari، اضغط على مشاركة ثم أضِف إلى الشاشة الرئيسية. بعد ذلك سيعمل التطبيق أيضًا دون اتصال بالإنترنت.',
  'home.install.android': 'ثبّت {name} على شاشتك الرئيسية. سيعمل التطبيق بعد ذلك أيضًا دون اتصال بالإنترنت.',
  'home.install.action': 'تثبيت',
  'home.install.dismiss': 'إخفاء',
  'home.random.kicker': 'حدث عشوائي',
  'home.random.more': 'قراءة المزيد',
  'home.random.again': 'حدث آخر',
  'home.progress.kicker': 'تقدّمك في الاختبار',
  'home.progress.title': 'تم إتقان {done} من {total} عصور',
  'home.progress.label': 'التقدّم',
  'home.progress.hint': 'تُعتبر العصر متقنًا عند الإجابة الصحيحة عن 80 بالمئة على الأقل من الأسئلة.',
  'home.progress.link': 'الانتقال إلى الاختبار',
  'home.section.epochs': 'العصور',
  'home.section.themes': 'الموضوعات الشاملة',
  'home.section.regions': 'المناطق',
  'home.section.reference': 'المرجع',
  'home.showall': 'عرض الكل',
  'home.epochs.note': 'بترتيب زمني، من العصر الحجري حتى اليوم.',
  'home.themes.note': 'خيوط تمتد عبر الألفيات.',
  'home.hub.glossary.title': 'المسرد',
  'home.hub.glossary.sub': 'شرح موجز لـ {terms}',
  'home.hub.search.title': 'بحث',
  'home.hub.search.sub': 'أحداث، أشخاص، موضوعات، مصطلحات',
  'home.hub.bookmarks.title': 'المفضلة',
  'home.hub.bookmarks.sub': 'العناصر التي حفظتها',

  'epochs.title': 'العصور',
  'epochs.intro': 'تاريخ العالم في {count} أقسام، بترتيب زمني. يحتوي كل عصر على نظرة عامة وأحداث رئيسية وشخصيات مهمة ونتائجها.',

  'epoch.notfound': 'هذا العصر غير موجود.',
  'epoch.back': 'جميع العصور',
  'epoch.hero.position': 'العصر {index} من {total}',
  'epoch.quiz.start': 'بدء الاختبار',
  'epoch.quiz.best': 'أفضل نتيجة {best}/{total}',
  'epoch.timeline': 'على الخط الزمني',
  'epoch.toc.title': 'المحتويات',
  'epoch.toc.aria': 'محتويات هذا العصر',
  'epoch.toc.events': 'الأحداث',
  'epoch.toc.persons': 'الأشخاص',
  'epoch.toc.terms': 'المصطلحات',
  'epoch.toc.consequences': 'النتائج',
  'epoch.keyfacts.title': 'لمحة سريعة',
  'epoch.keyfacts.milestones': 'المحطات البارزة',
  'epoch.overview.title': 'نظرة عامة',
  'epoch.events.title': 'الأحداث الرئيسية',
  'epoch.events.only': 'المحطات البارزة فقط ({n})',
  'epoch.persons.title': 'شخصيات مهمة',
  'epoch.terms.title': 'مصطلحات هذا العصر',
  'epoch.terms.link': 'في المسرد',
  'epoch.consequences.title': 'النتائج والأهمية',
  'epoch.themes.title': 'الموضوعات الشاملة ذات الصلة',
  'epoch.nav.prev': 'العصر السابق',
  'epoch.nav.next': 'العصر التالي',
  'epoch.nav.aria': 'العصور المجاورة',

  'event.notfound': 'هذا الحدث غير موجود.',
  'event.back': 'العصر',
  'event.importance.major': 'حدث بارز',
  'event.importance.label': 'الأهمية',
  'event.persons.title': 'الأشخاص المعنيون',
  'event.terms.title': 'مصطلحات هذا الحدث',
  'event.themes.title': 'الموضوعات الشاملة',
  'event.nearby.title': 'في الوقت نفسه في هذا العصر',
  'event.nav.aria': 'الأحداث المجاورة زمنيًا',
  'event.nav.prev': 'قبل',
  'event.nav.next': 'بعد',

  'person.notfound': 'هذا الشخص غير موجود.',
  'person.back': 'العصر',
  'person.events.title': 'الأحداث المرتبطة',
  'person.terms.title': 'المصطلحات',
  'person.themes.title': 'الموضوعات الشاملة',
  'person.contemporaries.title': 'معاصرون',

  'bookmarks.title': 'المفضلة',
  'bookmarks.empty.title': 'لا توجد مفضلة بعد',
  'bookmarks.empty.text': 'اضغط على «{save}» عند عصر أو حدث أو شخص لجمعهم هنا.',
  'bookmarks.count': 'تم حفظ {entries}. تُخزَّن المفضلة على هذا الجهاز فقط.',

  'notfound.title': 'غير موجود',
  'notfound.heading': 'الصفحة غير موجودة',
  'notfound.text': 'هذه الصفحة غير موجودة.',
  'notfound.home': 'الانتقال إلى الصفحة الرئيسية',

  'theme.label.system': 'تلقائي',
  'theme.label.light': 'فاتح',
  'theme.label.dark': 'داكن',
  'theme.buttonTitle': 'نظام الألوان: {name} (انقر للتغيير)',

  'quiz.verdict.excellent': 'ممتاز!',
  'quiz.verdict.verygood': 'جيد جدًا!',
  'quiz.verdict.good': 'أحسنت.',
  'quiz.verdict.keepgoing': 'واصل التدرّب!',

  'tile.theme.kicker': 'موضوع شامل',
  'tile.theme.events': '{events} عبر جميع العصور',

  'timeline.title': 'الخط الزمني',
  'timeline.intro': 'جميع الأحداث بترتيب زمني، مجمّعة حسب العصر والقرن. تشير النقاط الكبيرة إلى المحطات البارزة.',
  'timeline.filter.epoch': 'تصفية حسب العصر',
  'timeline.filter.region': 'تصفية حسب المنطقة',
  'timeline.filter.theme': 'تصفية حسب الموضوع',
  'timeline.allRegions': 'جميع المناطق',
  'timeline.allThemes': 'جميع الموضوعات',
  'timeline.onlyMilestones': 'المحطات البارزة فقط',
  'timeline.toTop': 'العودة إلى الأعلى',
  'timeline.empty.title': 'لا توجد أحداث',
  'timeline.empty.text': 'لا توجد عناصر لهذا المزيج من المرشِّحات.',

  'regions.title': 'المناطق',
  'regions.intro': 'التاريخ حسب القارات: ما الأحداث والشخصيات التي شكّلت كل منطقة من العالم؟',
  'regions.notfound': 'هذه المنطقة غير موجودة.',
  'regions.back': 'جميع المناطق',
  'regions.persons.title': 'شخصيات من هذه المنطقة',

  'themes.title': 'الموضوعات الشاملة',
  'themes.intro': 'التاريخ مقروءًا عبر العصور: يربط كل موضوع الأحداث والأشخاص والمصطلحات من جميع العصور في خيط واحد – من البدايات حتى اليوم.',
  'themes.notfound': 'هذا الموضوع غير موجود.',
  'themes.back': 'جميع الموضوعات',
  'themes.empty.title': 'لا توجد موضوعات بعد',
  'themes.empty.text': 'يجري إعداد الموضوعات.',
  'themes.empty.link': 'الانتقال إلى العصور',
  'themes.intro.title': 'مقدمة',
  'themes.course.title': 'عبر العصور',

  'glossary.title': 'المسرد',
  'glossary.intro': '{terms} من جميع العصور، مرتّبة أبجديًا وموضّحة باختصار.',
  'glossary.filter': 'تصفية المصطلحات …',
  'glossary.letters': 'الحروف',
  'glossary.allEpochs': 'جميع العصور',
  'glossary.none': 'لم يُعثر على مصطلحات.',
  'glossary.empty.title': 'لا توجد مصطلحات بعد',
  'glossary.empty.text': 'المسرد قيد الإعداد.',

  'search.title': 'بحث',
  'search.placeholder': 'حدث، شخص، عصر، موضوع أو مصطلح …',
  'search.label': 'كلمة البحث',
  'search.all': 'الكل ({n})',
  'search.hint': 'أدخل حرفين على الأقل. أمثلة:',
  'search.resultsFor': '{results} عن «{term}»',
  'search.none': 'لا توجد نتائج عن «{term}».',
  'search.examples': 'نابليون، الثورة، الصين، الديمقراطية، جدار برلين',
  'search.tooShort': 'الرجاء إدخال كلمة من حرفين على الأقل.',

  'quiz.intro': 'اختبر معلوماتك: عصرًا تلو الآخر أو بشكل مختلط عبر تاريخ العالم بأكمله. تُحفظ أفضل نتيجة لك على هذا الجهاز.',
  'quiz.notfound': 'هذا الاختبار غير موجود.',
  'quiz.back': 'نظرة عامة على الاختبارات',
  'quiz.mastered.label': 'العصور المتقنة (≥ 80٪)',
  'quiz.mastered.value': '{done} من {total}',
  'quiz.mixed.title': 'اختبار مختلط',
  'quiz.mixed.sub': '{questions} من جميع العصور',
  'quiz.epoch.sub': '{shown} من {total} سؤالًا في كل جولة',
  'quiz.epochTitle': 'اختبار: {epoch}',
  'quiz.best': 'أفضل نتيجة',
  'quiz.notPlayed': 'لم يُلعب بعد',
  'quiz.reset': 'إعادة تعيين التقدّم',
  'quiz.reset.confirm': 'هل تريد حقًا حذف تقدّمك في الاختبار؟',
  'quiz.noQuestions.title': 'لا توجد أسئلة',
  'quiz.noQuestions.text': 'لا توجد أسئلة لهذا العصر بعد.',
  'quiz.questionOf': 'السؤال {n} من {total}',
  'quiz.difficulty.easy': 'سهل',
  'quiz.difficulty.medium': 'متوسط',
  'quiz.difficulty.hard': 'صعب',
  'quiz.correct': 'إجابة صحيحة!',
  'quiz.wrong': 'ليست صحيحة تمامًا. الإجابة الصحيحة هي: {answer}',
  'quiz.keyHint': 'تلميح: أجب باستخدام المفاتيح A–D أو 1–4، واضغط على Enter للمتابعة.',
  'quiz.next': 'التالي',
  'quiz.finish': 'النتائج',
  'quiz.percentCorrect': '{percent}٪ إجابات صحيحة',
  'quiz.again': 'اللعب مرة أخرى',
  'quiz.other': 'اختبار آخر',
  'quiz.toEpoch': 'الانتقال إلى العصر',
  'quiz.review': 'يستحق المراجعة',
  'quiz.answerWas': 'الإجابة الصحيحة: {answer} –',
  'quiz.allCorrect': 'جميع الإجابات صحيحة – ممتاز!',

  'more.intro': 'مزيد من أقسام التطبيق والإعدادات والمعلومات.',
  'more.discover': 'استكشاف',
  'more.themes.sub': '{themes} عبر جميع العصور',
  'more.regions.sub': 'التاريخ حسب القارات',
  'more.search.sub': 'البحث في كل المحتوى',
  'more.bookmarks.sub': 'تم حفظ {entries}',
  'more.settings': 'الإعدادات',
  'more.theme.title': 'نظام الألوان',
  'more.theme.action': 'تغيير',
  'more.progress.title': 'تقدّم الاختبار',
  'more.progress.sub': 'أفضل النتائج والمحاولات على هذا الجهاز',
  'more.progress.action': 'إعادة التعيين',
  'more.progress.done': 'تمت إعادة تعيين التقدّم',
  'more.offline.title': 'البيانات دون اتصال',
  'more.offline.sub': 'تحديث ملفات التطبيق المخزَّنة مؤقتًا',
  'more.offline.action': 'تحديث',
  'more.offline.done': 'تم مسح التخزين المؤقت – جارٍ إعادة التحميل …',
  'more.offline.noNetwork': 'لا يوجد اتصال بالإنترنت – البيانات دون اتصال محفوظة.',
  'more.data.title': 'حذف جميع البيانات',
  'more.data.sub': 'المفضلة وتقدّم الاختبار والإعدادات على هذا الجهاز',
  'more.data.action': 'حذف',
  'more.data.confirm': 'هل تريد حقًا حذف جميع المفضلة وتقدّم الاختبار والإعدادات على هذا الجهاز؟',
  'more.data.done': 'تم حذف جميع البيانات',
  'more.about.title': 'حول التطبيق',
  'more.about.text': 'هو تطبيق تعليمي للموضوعات الأساسية من الماضي – من أول البشر حتى يومنا هذا، في كل القارات.',
  'more.about.note': 'تلخّص النصوص حالة البحث المعترف بها عمومًا، وهي مكتوبة للمدرسة والجامعة والثقافة العامة. تُشار السنوات قبل الميلاد بـ«ق.م»، والتواريخ التقريبية بـ«نحو». تبقى المفضلة وتقدّم الاختبار على هذا الجهاز فقط.',
  'more.version': 'الإصدار {version} · {kind} · يعمل دون اتصال بالإنترنت',
  'more.kind.native': 'إصدار التطبيق',
  'more.kind.pwa': 'تطبيق ويب تقدّمي',
  'more.privacy': 'سياسة الخصوصية',
  'more.imprint': 'بيانات قانونية',
  'quiz.joker': 'مساعدة 50:50',
  'quiz.joker.watch': 'مساعدة 50:50 مقابل إعلان قصير',
  'quiz.joker.used': 'تمت إزالة إجابتين خاطئتين.',
  'quiz.joker.unavailable': 'لا يتوفر إعلان حاليًا. يُرجى المحاولة لاحقًا.',
  'quiz.joker.loading': 'جارٍ تحميل الإعلان …',
  'more.ads.title': 'الإعلانات والخصوصية',
  'more.ads.sub': 'تغيير موافقتك على الإعلانات المخصصة',
  'more.ads.action': 'تغيير',
  'ads.label': 'إعلان',
};
