// English interface texts. Keys and placeholders must match js/strings/de.js exactly.
export default {
  'app.name': 'World History',
  'app.description': 'World history from prehistory to the present: epochs, cross-cutting themes, a timeline, a glossary, a quiz, search and bookmarks. Works offline.',
  'app.skipToContent': 'Skip to content',
  'app.brandAria': 'World History – home',
  'app.install': 'Install app',
  'app.installed': 'App installed',
  'app.loading': 'Loading content …',
  'app.loadFailed': 'Content could not be loaded',
  'app.retry': 'Try again',
  'app.error': 'Error',
  'app.update.available': 'New version available',
  'app.update.action': 'Reload',

  'nav.home': 'Home',
  'nav.epochs': 'Epochs',
  'nav.timeline': 'Timeline',
  'nav.themes': 'Themes',
  'nav.glossary': 'Glossary',
  'nav.quiz': 'Quiz',
  'nav.bookmarks': 'Bookmarks',
  'nav.more': 'More',
  'nav.search': 'Search',
  'nav.aria.main': 'Main navigation',
  'nav.aria.bottom': 'Navigation',

  'lang.label': 'Language',
  'theme.toggle': 'Change color scheme',
  'theme.toast': 'Color scheme: {name}',
  'title.page': '{title} – World History',

  'year.bc': '{n} BC',
  'year.ad': '{n} AD',
  'year.approx': 'c. {s}',
  'year.unknown': '?',
  'year.today': 'today',

  'unit.event.one': 'event',
  'unit.event.other': 'events',
  'unit.person.one': 'person',
  'unit.person.other': 'people',
  'unit.term.one': 'term',
  'unit.term.other': 'terms',
  'unit.theme.one': 'theme',
  'unit.theme.other': 'themes',
  'unit.epoch.one': 'epoch',
  'unit.epoch.other': 'epochs',
  'unit.entry.one': 'entry',
  'unit.entry.other': 'entries',
  'unit.hit.one': 'result',
  'unit.hit.other': 'results',
  'unit.question.one': 'question',
  'unit.question.other': 'questions',
  'unit.region.one': 'region',
  'unit.region.other': 'regions',
  'unit.attempt.one': 'attempt',
  'unit.attempt.other': 'attempts',

  'heading.events': 'Events',
  'heading.persons': 'People',
  'heading.terms': 'Terms',

  'century.earliest': 'Before 10,000 BC',
  'century.bc': '{n} century BC',
  'century.ad': '{n} century',

  'ui.milestone': 'Milestone',
  'ui.bookmark.save': 'Save',
  'ui.bookmark.saved': 'Saved',
  'toast.bookmark.added': 'Bookmark saved',
  'toast.bookmark.removed': 'Bookmark removed',

  'home.intro': 'All the essential subjects of the past, from the first humans to the present day. Arranged by epoch, cross-cutting theme and region, with a timeline, a glossary and a quiz.',
  'home.stat.quiz': 'Quiz questions',
  'home.cta.epochs': 'Explore the epochs',
  'home.cta.timeline': 'Timeline',
  'home.cta.quiz': 'Start the quiz',
  'home.install.title': 'Install as an app',
  'home.install.ios': 'In Safari, tap Share and then Add to Home Screen. After that the app works offline as well.',
  'home.install.android': 'Install {name} on your home screen. The app then works offline as well.',
  'home.install.action': 'Install',
  'home.install.dismiss': 'Hide',
  'home.random.kicker': 'Random event',
  'home.random.more': 'Read more',
  'home.random.again': 'Another event',
  'home.progress.kicker': 'Your quiz progress',
  'home.progress.title': '{done} of {total} epochs mastered',
  'home.progress.label': 'Progress',
  'home.progress.hint': 'An epoch counts as mastered once you answer at least 80 percent of the questions correctly.',
  'home.progress.link': 'Go to the quiz',
  'home.section.epochs': 'Epochs',
  'home.section.themes': 'Cross-cutting themes',
  'home.section.regions': 'Regions',
  'home.section.reference': 'Reference',
  'home.showall': 'Show all',
  'home.epochs.note': 'In chronological order, from the Stone Age to today.',
  'home.themes.note': 'Threads running through the millennia.',
  'home.hub.glossary.title': 'Glossary',
  'home.hub.glossary.sub': '{terms} explained briefly',
  'home.hub.search.title': 'Search',
  'home.hub.search.sub': 'Events, people, themes, terms',
  'home.hub.bookmarks.title': 'Bookmarks',
  'home.hub.bookmarks.sub': 'The items you have saved',

  'epochs.title': 'Epochs',
  'epochs.intro': 'World history in {count} sections, in chronological order. Every epoch contains an overview, key events, important people and their consequences.',

  'epoch.notfound': 'This epoch does not exist.',
  'epoch.back': 'All epochs',
  'epoch.hero.position': 'Epoch {index} of {total}',
  'epoch.quiz.start': 'Start the quiz',
  'epoch.quiz.best': 'Best score {best}/{total}',
  'epoch.timeline': 'On the timeline',
  'epoch.toc.title': 'Contents',
  'epoch.toc.aria': 'Contents of this epoch',
  'epoch.toc.events': 'Events',
  'epoch.toc.persons': 'People',
  'epoch.toc.terms': 'Terms',
  'epoch.toc.consequences': 'Consequences',
  'epoch.keyfacts.title': 'At a glance',
  'epoch.keyfacts.milestones': 'Milestones',
  'epoch.overview.title': 'Overview',
  'epoch.events.title': 'Key events',
  'epoch.events.only': 'Milestones only ({n})',
  'epoch.persons.title': 'Important people',
  'epoch.terms.title': 'Terms of this epoch',
  'epoch.terms.link': 'In the glossary',
  'epoch.consequences.title': 'Consequences and significance',
  'epoch.themes.title': 'Related cross-cutting themes',
  'epoch.nav.prev': 'Previous epoch',
  'epoch.nav.next': 'Next epoch',
  'epoch.nav.aria': 'Neighboring epochs',

  'event.notfound': 'This event does not exist.',
  'event.back': 'Epoch',
  'event.importance.major': 'Major event',
  'event.importance.label': 'Significance',
  'event.persons.title': 'People involved',
  'event.terms.title': 'Terms for this event',
  'event.themes.title': 'Cross-cutting themes',
  'event.nearby.title': 'At the same time in this epoch',
  'event.nav.aria': 'Chronological neighbors',
  'event.nav.prev': 'Before',
  'event.nav.next': 'After',

  'person.notfound': 'This person does not exist.',
  'person.back': 'Epoch',
  'person.events.title': 'Linked events',
  'person.terms.title': 'Terms',
  'person.themes.title': 'Cross-cutting themes',
  'person.contemporaries.title': 'Contemporaries',

  'bookmarks.title': 'Bookmarks',
  'bookmarks.empty.title': 'No bookmarks yet',
  'bookmarks.empty.text': 'Tap “{save}” on an epoch, an event or a person to collect them here.',
  'bookmarks.count': '{entries} saved. Bookmarks are stored on this device only.',

  'notfound.title': 'Not found',
  'notfound.heading': 'Page not found',
  'notfound.text': 'This page does not exist.',
  'notfound.home': 'Go to the home page',

  'theme.label.system': 'Automatic',
  'theme.label.light': 'Light',
  'theme.label.dark': 'Dark',
  'theme.buttonTitle': 'Color scheme: {name} (click to change)',

  'quiz.verdict.excellent': 'Excellent!',
  'quiz.verdict.verygood': 'Very good!',
  'quiz.verdict.good': 'Well done.',
  'quiz.verdict.keepgoing': 'Keep practicing!',

  'tile.theme.kicker': 'Cross-cutting theme',
  'tile.theme.events': '{events} across all epochs',

  'timeline.title': 'Timeline',
  'timeline.intro': 'Every event in chronological order, grouped by epoch and century. Large dots mark the milestones.',
  'timeline.filter.epoch': 'Filter by epoch',
  'timeline.filter.region': 'Filter by region',
  'timeline.filter.theme': 'Filter by theme',
  'timeline.allRegions': 'All regions',
  'timeline.allThemes': 'All themes',
  'timeline.onlyMilestones': 'Milestones only',
  'timeline.toTop': 'Back to top',
  'timeline.empty.title': 'No events',
  'timeline.empty.text': 'There are no entries for this combination of filters.',

  'regions.title': 'Regions',
  'regions.intro': 'History by continent: which events and people shaped each region of the world?',
  'regions.notfound': 'This region does not exist.',
  'regions.back': 'All regions',
  'regions.persons.title': 'People from this region',

  'themes.title': 'Cross-cutting themes',
  'themes.intro': 'History read across the ages: each theme ties events, people and terms from every epoch into one thread – from the beginnings to the present day.',
  'themes.notfound': 'This theme does not exist.',
  'themes.back': 'All themes',
  'themes.empty.title': 'No themes yet',
  'themes.empty.text': 'The themes are being prepared.',
  'themes.empty.link': 'Go to the epochs',
  'themes.intro.title': 'Introduction',
  'themes.course.title': 'Through the epochs',

  'glossary.title': 'Glossary',
  'glossary.intro': '{terms} from every epoch, in alphabetical order and briefly explained.',
  'glossary.filter': 'Filter terms …',
  'glossary.letters': 'Letters',
  'glossary.allEpochs': 'All epochs',
  'glossary.none': 'No terms found.',
  'glossary.empty.title': 'No terms yet',
  'glossary.empty.text': 'The glossary is being prepared.',

  'search.title': 'Search',
  'search.placeholder': 'Event, person, epoch, theme or term …',
  'search.label': 'Search term',
  'search.all': 'All ({n})',
  'search.hint': 'Enter at least two characters. Examples:',
  'search.resultsFor': '{results} for “{term}”',
  'search.none': 'No results for “{term}”.',

  'quiz.intro': 'Test your knowledge: one epoch at a time or mixed across all of world history. Your best score is stored on this device.',
  'quiz.notfound': 'This quiz does not exist.',
  'quiz.back': 'Quiz overview',
  'quiz.mastered.label': 'Epochs mastered (≥ 80%)',
  'quiz.mastered.value': '{done} of {total}',
  'quiz.mixed.title': 'Mixed quiz',
  'quiz.mixed.sub': '{questions} from all epochs',
  'quiz.epoch.sub': '{shown} of {total} questions per round',
  'quiz.epochTitle': 'Quiz: {epoch}',
  'quiz.best': 'Best score',
  'quiz.notPlayed': 'Not played yet',
  'quiz.reset': 'Reset progress',
  'quiz.reset.confirm': 'Really delete your quiz progress?',
  'quiz.noQuestions.title': 'No questions',
  'quiz.noQuestions.text': 'There are no questions for this epoch yet.',
  'quiz.questionOf': 'Question {n} of {total}',
  'quiz.difficulty.easy': 'Easy',
  'quiz.difficulty.medium': 'Medium',
  'quiz.difficulty.hard': 'Hard',
  'quiz.correct': 'Correct!',
  'quiz.wrong': 'Not quite. The answer is: {answer}',
  'quiz.next': 'Next',
  'quiz.finish': 'Results',
  'quiz.percentCorrect': '{percent}% correct',
  'quiz.again': 'Play again',
  'quiz.other': 'Another quiz',
  'quiz.toEpoch': 'Go to the epoch',
  'quiz.review': 'Worth a second look',
  'quiz.answerWas': 'Correct: {answer} –',
  'quiz.allCorrect': 'Every question right – excellent!',

  'more.intro': 'More areas of the app, settings and information.',
  'more.discover': 'Discover',
  'more.themes.sub': '{themes} across all epochs',
  'more.regions.sub': 'History by continent',
  'more.search.sub': 'Search all content',
  'more.bookmarks.sub': '{entries} saved',
  'more.settings': 'Settings',
  'more.theme.title': 'Color scheme',
  'more.theme.action': 'Change',
  'more.progress.title': 'Quiz progress',
  'more.progress.sub': 'Best scores and attempts on this device',
  'more.progress.action': 'Reset',
  'more.progress.done': 'Progress reset',
  'more.offline.title': 'Offline data',
  'more.offline.sub': 'Refresh the cached app files',
  'more.offline.action': 'Refresh',
  'more.offline.done': 'Cache cleared – reloading …',
  'more.about.title': 'About the app',
  'more.about.text': 'is a learning app for the essential topics of the past – from the first humans to the present day, on every continent.',
  'more.about.note': 'The texts summarize the generally accepted state of research and are written for school, university and general education. Years before Christ are marked “BC”, approximate dates with “c.”. Bookmarks and quiz progress stay on this device only.',
  'more.version': 'Version {version} · {kind} · Works offline',
  'more.kind.native': 'App version',
  'more.kind.pwa': 'Progressive Web App',
  'more.privacy': 'Privacy policy',
  'more.imprint': 'Legal notice',
};
