// Textos de interfaz en español.
export default {
  'app.name': 'Historia universal',
  'app.description': 'Historia universal desde la prehistoria hasta la actualidad: épocas, temas transversales, línea de tiempo, glosario, cuestionario, búsqueda y favoritos. Funciona sin conexión.',
  'app.skipToContent': 'Saltar al contenido',
  'app.brandAria': 'Historia universal – inicio',
  'app.install': 'Instalar la aplicación',
  'app.installed': 'Aplicación instalada',
  'app.loading': 'Cargando contenido …',
  'app.loadFailed': 'No se pudo cargar el contenido',
  'app.retry': 'Reintentar',
  'app.error': 'Error',
  'app.update.available': 'Nueva versión disponible',
  'app.update.action': 'Recargar',

  'nav.home': 'Inicio',
  'nav.epochs': 'Épocas',
  'nav.timeline': 'Línea de tiempo',
  'nav.themes': 'Temas',
  'nav.glossary': 'Glosario',
  'nav.quiz': 'Cuestionario',
  'nav.bookmarks': 'Favoritos',
  'nav.more': 'Más',
  'nav.search': 'Buscar',
  'nav.aria.main': 'Navegación principal',
  'nav.aria.bottom': 'Navegación',

  'lang.label': 'Idioma',
  'theme.toggle': 'Cambiar el esquema de color',
  'theme.toast': 'Esquema de color: {name}',
  'title.page': '{title} – Historia universal',

  'year.bc': '{n} a. C.',
  'year.ad': '{n} d. C.',
  'year.approx': 'c. {s}',
  'year.unknown': '?',
  'year.today': 'hoy',

  'unit.event.one': 'evento',
  'unit.event.other': 'eventos',
  'unit.person.one': 'persona',
  'unit.person.other': 'personas',
  'unit.term.one': 'término',
  'unit.term.other': 'términos',
  'unit.theme.one': 'tema',
  'unit.theme.other': 'temas',
  'unit.epoch.one': 'época',
  'unit.epoch.other': 'épocas',
  'unit.entry.one': 'entrada',
  'unit.entry.other': 'entradas',
  'unit.hit.one': 'resultado',
  'unit.hit.other': 'resultados',
  'unit.question.one': 'pregunta',
  'unit.question.other': 'preguntas',
  'unit.region.one': 'región',
  'unit.region.other': 'regiones',
  'unit.attempt.one': 'intento',
  'unit.attempt.other': 'intentos',

  'heading.events': 'Eventos',
  'heading.persons': 'Personas',
  'heading.terms': 'Términos',

  'century.earliest': 'Antes del 10.000 a. C.',
  'century.bc': 'Siglo {n} a. C.',
  'century.ad': 'Siglo {n}',

  'ui.milestone': 'Hito',
  'ui.bookmark.save': 'Guardar',
  'ui.bookmark.saved': 'Guardado',
  'toast.bookmark.added': 'Favorito guardado',
  'toast.bookmark.removed': 'Favorito eliminado',

  'home.intro': 'Todos los temas esenciales del pasado, desde los primeros humanos hasta el presente. Organizados por época, tema transversal y región, con línea de tiempo, glosario y cuestionario.',
  'home.stat.quiz': 'Preguntas del cuestionario',
  'home.cta.epochs': 'Explorar las épocas',
  'home.cta.timeline': 'Línea de tiempo',
  'home.cta.quiz': 'Comenzar el cuestionario',
  'home.install.title': 'Instalar como aplicación',
  'home.install.ios': 'En Safari, toca Compartir y luego Añadir a pantalla de inicio. Después, la aplicación también funcionará sin conexión.',
  'home.install.android': 'Instala {name} en tu pantalla de inicio. La aplicación también funcionará sin conexión.',
  'home.install.action': 'Instalar',
  'home.install.dismiss': 'Ocultar',
  'home.random.kicker': 'Evento aleatorio',
  'home.random.more': 'Leer más',
  'home.random.again': 'Otro evento',
  'home.progress.kicker': 'Tu progreso en el cuestionario',
  'home.progress.title': '{done} de {total} épocas dominadas',
  'home.progress.label': 'Progreso',
  'home.progress.hint': 'Una época se considera dominada cuando respondes correctamente al menos el 80 % de las preguntas.',
  'home.progress.link': 'Ir al cuestionario',
  'home.section.epochs': 'Épocas',
  'home.section.themes': 'Temas transversales',
  'home.section.regions': 'Regiones',
  'home.section.reference': 'Referencia',
  'home.showall': 'Mostrar todo',
  'home.epochs.note': 'En orden cronológico, desde la Edad de Piedra hasta hoy.',
  'home.themes.note': 'Hilos conductores a través de los milenios.',
  'home.hub.glossary.title': 'Glosario',
  'home.hub.glossary.sub': '{terms} explicados brevemente',
  'home.hub.search.title': 'Buscar',
  'home.hub.search.sub': 'Eventos, personas, temas, términos',
  'home.hub.bookmarks.title': 'Favoritos',
  'home.hub.bookmarks.sub': 'Los elementos que has guardado',

  'epochs.title': 'Épocas',
  'epochs.intro': 'La historia universal en {count} secciones, en orden cronológico. Cada época incluye una visión general, eventos clave, personas importantes y sus consecuencias.',

  'epoch.notfound': 'Esta época no existe.',
  'epoch.back': 'Todas las épocas',
  'epoch.hero.position': 'Época {index} de {total}',
  'epoch.quiz.start': 'Comenzar el cuestionario',
  'epoch.quiz.best': 'Mejor puntuación {best}/{total}',
  'epoch.timeline': 'En la línea de tiempo',
  'epoch.toc.title': 'Contenido',
  'epoch.toc.aria': 'Contenido de esta época',
  'epoch.toc.events': 'Eventos',
  'epoch.toc.persons': 'Personas',
  'epoch.toc.terms': 'Términos',
  'epoch.toc.consequences': 'Consecuencias',
  'epoch.keyfacts.title': 'De un vistazo',
  'epoch.keyfacts.milestones': 'Hitos',
  'epoch.overview.title': 'Visión general',
  'epoch.events.title': 'Eventos clave',
  'epoch.events.only': 'Solo hitos ({n})',
  'epoch.persons.title': 'Personas importantes',
  'epoch.terms.title': 'Términos de esta época',
  'epoch.terms.link': 'En el glosario',
  'epoch.consequences.title': 'Consecuencias e importancia',
  'epoch.themes.title': 'Temas transversales relacionados',
  'epoch.nav.prev': 'Época anterior',
  'epoch.nav.next': 'Época siguiente',
  'epoch.nav.aria': 'Épocas vecinas',

  'event.notfound': 'Este evento no existe.',
  'event.back': 'Época',
  'event.importance.major': 'Evento importante',
  'event.importance.label': 'Importancia',
  'event.persons.title': 'Personas involucradas',
  'event.terms.title': 'Términos relacionados con este evento',
  'event.themes.title': 'Temas transversales',
  'event.nearby.title': 'En la misma época',
  'event.nav.aria': 'Vecinos cronológicos',
  'event.nav.prev': 'Antes',
  'event.nav.next': 'Después',

  'person.notfound': 'Esta persona no existe.',
  'person.back': 'Época',
  'person.events.title': 'Eventos relacionados',
  'person.terms.title': 'Términos',
  'person.themes.title': 'Temas transversales',
  'person.contemporaries.title': 'Contemporáneos',

  'bookmarks.title': 'Favoritos',
  'bookmarks.empty.title': 'Aún no hay favoritos',
  'bookmarks.empty.text': 'Toca «{save}» en una época, un evento o una persona para reunirlos aquí.',
  'bookmarks.count': '{entries} guardado(s). Los favoritos se guardan solo en este dispositivo.',

  'notfound.title': 'No encontrado',
  'notfound.heading': 'Página no encontrada',
  'notfound.text': 'Esta página no existe.',
  'notfound.home': 'Ir a la página de inicio',

  'theme.label.system': 'Automático',
  'theme.label.light': 'Claro',
  'theme.label.dark': 'Oscuro',
  'theme.buttonTitle': 'Esquema de color: {name} (clic para cambiar)',

  'quiz.verdict.excellent': '¡Excelente!',
  'quiz.verdict.verygood': '¡Muy bien!',
  'quiz.verdict.good': 'Bien hecho.',
  'quiz.verdict.keepgoing': '¡Sigue practicando!',

  'tile.theme.kicker': 'Tema transversal',
  'tile.theme.events': '{events} a través de todas las épocas',

  'timeline.title': 'Línea de tiempo',
  'timeline.intro': 'Todos los eventos en orden cronológico, agrupados por época y siglo. Los puntos grandes marcan los hitos.',
  'timeline.filter.epoch': 'Filtrar por época',
  'timeline.filter.region': 'Filtrar por región',
  'timeline.filter.theme': 'Filtrar por tema',
  'timeline.allRegions': 'Todas las regiones',
  'timeline.allThemes': 'Todos los temas',
  'timeline.onlyMilestones': 'Solo hitos',
  'timeline.toTop': 'Volver arriba',
  'timeline.empty.title': 'No hay eventos',
  'timeline.empty.text': 'No hay entradas para esta combinación de filtros.',

  'regions.title': 'Regiones',
  'regions.intro': 'La historia por continentes: ¿qué eventos y personas dieron forma a cada región del mundo?',
  'regions.notfound': 'Esta región no existe.',
  'regions.back': 'Todas las regiones',
  'regions.persons.title': 'Personas de esta región',

  'themes.title': 'Temas transversales',
  'themes.intro': 'La historia leída de forma transversal: cada tema une eventos, personas y términos de todas las épocas en un mismo hilo conductor, desde los orígenes hasta la actualidad.',
  'themes.notfound': 'Este tema no existe.',
  'themes.back': 'Todos los temas',
  'themes.empty.title': 'Aún no hay temas',
  'themes.empty.text': 'Los temas se están preparando.',
  'themes.empty.link': 'Ir a las épocas',
  'themes.intro.title': 'Introducción',
  'themes.course.title': 'A través de las épocas',

  'glossary.title': 'Glosario',
  'glossary.intro': '{terms} de todas las épocas, en orden alfabético y explicados brevemente.',
  'glossary.filter': 'Filtrar términos …',
  'glossary.letters': 'Letras',
  'glossary.allEpochs': 'Todas las épocas',
  'glossary.none': 'No se encontraron términos.',
  'glossary.empty.title': 'Aún no hay términos',
  'glossary.empty.text': 'El glosario se está preparando.',

  'search.title': 'Buscar',
  'search.placeholder': 'Evento, persona, época, tema o término …',
  'search.label': 'Término de búsqueda',
  'search.all': 'Todos ({n})',
  'search.hint': 'Introduce al menos dos caracteres. Ejemplos:',
  'search.resultsFor': '{results} para «{term}»',
  'search.none': 'Sin resultados para «{term}».',
  'search.examples': 'Napoleón, Revolución, China, Democracia, Muro de Berlín',
  'search.tooShort': 'Introduce una palabra de al menos dos letras.',

  'quiz.intro': 'Pon a prueba tus conocimientos: por época o mezclados a través de toda la historia universal. Tu mejor puntuación se guarda en este dispositivo.',
  'quiz.notfound': 'Este cuestionario no existe.',
  'quiz.back': 'Resumen de cuestionarios',
  'quiz.mastered.label': 'Épocas dominadas (≥ 80 %)',
  'quiz.mastered.value': '{done} de {total}',
  'quiz.mixed.title': 'Cuestionario mixto',
  'quiz.mixed.sub': '{questions} de todas las épocas',
  'quiz.epoch.sub': '{shown} de {total} preguntas por ronda',
  'quiz.epochTitle': 'Cuestionario: {epoch}',
  'quiz.best': 'Mejor puntuación',
  'quiz.notPlayed': 'Aún no jugado',
  'quiz.reset': 'Restablecer progreso',
  'quiz.reset.confirm': '¿Seguro que quieres eliminar tu progreso en el cuestionario?',
  'quiz.noQuestions.title': 'Sin preguntas',
  'quiz.noQuestions.text': 'Aún no hay preguntas para esta época.',
  'quiz.questionOf': 'Pregunta {n} de {total}',
  'quiz.difficulty.easy': 'Fácil',
  'quiz.difficulty.medium': 'Medio',
  'quiz.difficulty.hard': 'Difícil',
  'quiz.correct': '¡Correcto!',
  'quiz.wrong': 'No exactamente. La respuesta es: {answer}',
  'quiz.keyHint': 'Consejo: responde con las teclas A–D o 1–4, pulsa Intro para continuar.',
  'quiz.next': 'Siguiente',
  'quiz.finish': 'Resultados',
  'quiz.percentCorrect': '{percent} % correcto',
  'quiz.again': 'Jugar de nuevo',
  'quiz.other': 'Otro cuestionario',
  'quiz.toEpoch': 'Ir a la época',
  'quiz.review': 'Vale la pena revisar',
  'quiz.answerWas': 'Correcto: {answer} –',
  'quiz.allCorrect': '¡Todas las preguntas correctas, excelente!',

  'more.intro': 'Más secciones de la aplicación, ajustes e información.',
  'more.discover': 'Descubrir',
  'more.themes.sub': '{themes} a través de todas las épocas',
  'more.regions.sub': 'La historia por continentes',
  'more.search.sub': 'Buscar en todo el contenido',
  'more.bookmarks.sub': '{entries} guardado(s)',
  'more.settings': 'Ajustes',
  'more.theme.title': 'Esquema de color',
  'more.theme.action': 'Cambiar',
  'more.progress.title': 'Progreso del cuestionario',
  'more.progress.sub': 'Mejores puntuaciones e intentos en este dispositivo',
  'more.progress.action': 'Restablecer',
  'more.progress.done': 'Progreso restablecido',
  'more.offline.title': 'Datos sin conexión',
  'more.offline.sub': 'Actualizar los archivos de la aplicación en caché',
  'more.offline.action': 'Actualizar',
  'more.offline.done': 'Caché borrada – recargando …',
  'more.offline.noNetwork': 'Sin conexión a internet – se conservan los datos sin conexión.',
  'more.data.title': 'Eliminar todos los datos',
  'more.data.sub': 'Favoritos, progreso del cuestionario y ajustes en este dispositivo',
  'more.data.action': 'Eliminar',
  'more.data.confirm': '¿Seguro que quieres eliminar todos los favoritos, el progreso del cuestionario y todos los ajustes de este dispositivo?',
  'more.data.done': 'Todos los datos eliminados',
  'more.about.title': 'Acerca de la aplicación',
  'more.about.text': 'es una aplicación de aprendizaje sobre los temas esenciales del pasado, desde los primeros humanos hasta la actualidad, en todos los continentes.',
  'more.about.note': 'Los textos resumen el estado de la investigación generalmente aceptado y están pensados para la escuela, la universidad y la cultura general. Los años antes de Cristo se indican con «a. C.», las fechas aproximadas con «c.». Los favoritos y el progreso del cuestionario permanecen solo en este dispositivo.',
  'more.version': 'Versión {version} · {kind} · Funciona sin conexión',
  'more.kind.native': 'Versión de la aplicación',
  'more.kind.pwa': 'Aplicación web progresiva',
  'more.privacy': 'Política de privacidad',
  'more.imprint': 'Aviso legal',
  'quiz.joker': 'Comodín 50:50',
  'quiz.joker.watch': 'Comodín 50:50 a cambio de un anuncio breve',
  'quiz.joker.used': 'Se han eliminado dos respuestas incorrectas.',
  'quiz.joker.unavailable': 'No hay ningún anuncio disponible en este momento. Inténtalo de nuevo más tarde.',
  'quiz.joker.loading': 'Cargando anuncio …',
  'more.ads.title': 'Anuncios y privacidad',
  'more.ads.sub': 'Cambiar tu consentimiento para anuncios personalizados',
  'more.ads.action': 'Cambiar',
  'ads.label': 'Anuncio',
};
