// Textes d'interface français.
export default {
  'app.name': 'Histoire du monde',
  'app.description': 'L\'histoire du monde de la préhistoire à nos jours : époques, thèmes transversaux, frise chronologique, glossaire, quiz, recherche et favoris. Fonctionne hors ligne.',
  'app.skipToContent': 'Passer au contenu',
  'app.brandAria': 'Histoire du monde – accueil',
  'app.install': 'Installer l\'application',
  'app.installed': 'Application installée',
  'app.loading': 'Chargement du contenu …',
  'app.loadFailed': 'Le contenu n\'a pas pu être chargé',
  'app.retry': 'Réessayer',
  'app.error': 'Erreur',
  'app.update.available': 'Nouvelle version disponible',
  'app.update.action': 'Recharger',

  'nav.home': 'Accueil',
  'nav.epochs': 'Époques',
  'nav.timeline': 'Frise chronologique',
  'nav.themes': 'Thèmes',
  'nav.glossary': 'Glossaire',
  'nav.quiz': 'Quiz',
  'nav.bookmarks': 'Favoris',
  'nav.more': 'Plus',
  'nav.search': 'Recherche',
  'nav.aria.main': 'Navigation principale',
  'nav.aria.bottom': 'Navigation',

  'lang.label': 'Langue',
  'theme.toggle': 'Changer le thème',
  'theme.toast': 'Thème : {name}',
  'title.page': '{title} – Histoire du monde',

  'year.bc': '{n} av. J.-C.',
  'year.ad': '{n} apr. J.-C.',
  'year.approx': 'v. {s}',
  'year.unknown': '?',
  'year.today': 'aujourd\'hui',

  'unit.event.one': 'événement',
  'unit.event.other': 'événements',
  'unit.person.one': 'personne',
  'unit.person.other': 'personnes',
  'unit.term.one': 'terme',
  'unit.term.other': 'termes',
  'unit.theme.one': 'thème',
  'unit.theme.other': 'thèmes',
  'unit.epoch.one': 'époque',
  'unit.epoch.other': 'époques',
  'unit.entry.one': 'entrée',
  'unit.entry.other': 'entrées',
  'unit.hit.one': 'résultat',
  'unit.hit.other': 'résultats',
  'unit.question.one': 'question',
  'unit.question.other': 'questions',
  'unit.region.one': 'région',
  'unit.region.other': 'régions',
  'unit.attempt.one': 'tentative',
  'unit.attempt.other': 'tentatives',

  'heading.events': 'Événements',
  'heading.persons': 'Personnes',
  'heading.terms': 'Termes',

  'century.earliest': 'Avant 10 000 av. J.-C.',
  'century.bc': '{n} siècle av. J.-C.',
  'century.ad': '{n} siècle',

  'ui.milestone': 'Jalon',
  'ui.bookmark.save': 'Enregistrer',
  'ui.bookmark.saved': 'Enregistré',
  'toast.bookmark.added': 'Favori enregistré',
  'toast.bookmark.removed': 'Favori supprimé',

  'home.intro': 'Tous les sujets essentiels du passé, des premiers hommes à nos jours. Organisés par époque, thème transversal et région, avec une frise chronologique, un glossaire et un quiz.',
  'home.stat.quiz': 'Questions de quiz',
  'home.cta.epochs': 'Explorer les époques',
  'home.cta.timeline': 'Frise chronologique',
  'home.cta.quiz': 'Commencer le quiz',
  'home.install.title': 'Installer comme application',
  'home.install.ios': 'Dans Safari, appuyez sur Partager puis sur Sur l\'écran d\'accueil. L\'application fonctionne ensuite aussi hors ligne.',
  'home.install.android': 'Installez {name} sur votre écran d\'accueil. L\'application fonctionne ensuite aussi hors ligne.',
  'home.install.action': 'Installer',
  'home.install.dismiss': 'Masquer',
  'home.random.kicker': 'Événement aléatoire',
  'home.random.more': 'Lire la suite',
  'home.random.again': 'Autre événement',
  'home.progress.kicker': 'Votre progression au quiz',
  'home.progress.title': '{done} époque(s) maîtrisée(s) sur {total}',
  'home.progress.label': 'Progression',
  'home.progress.hint': 'Une époque est considérée comme maîtrisée dès que vous répondez correctement à au moins 80 % des questions.',
  'home.progress.link': 'Aller au quiz',
  'home.section.epochs': 'Époques',
  'home.section.themes': 'Thèmes transversaux',
  'home.section.regions': 'Régions',
  'home.section.reference': 'Références',
  'home.showall': 'Tout afficher',
  'home.epochs.note': 'Par ordre chronologique, de l\'âge de pierre à aujourd\'hui.',
  'home.themes.note': 'Des fils conducteurs à travers les millénaires.',
  'home.hub.glossary.title': 'Glossaire',
  'home.hub.glossary.sub': '{terms} expliqués brièvement',
  'home.hub.search.title': 'Recherche',
  'home.hub.search.sub': 'Événements, personnes, thèmes, termes',
  'home.hub.bookmarks.title': 'Favoris',
  'home.hub.bookmarks.sub': 'Les éléments que vous avez enregistrés',

  'epochs.title': 'Époques',
  'epochs.intro': 'L\'histoire du monde en {count} sections, par ordre chronologique. Chaque époque comprend un aperçu, des événements clés, des personnages importants et leurs conséquences.',

  'epoch.notfound': 'Cette époque n\'existe pas.',
  'epoch.back': 'Toutes les époques',
  'epoch.hero.position': 'Époque {index} sur {total}',
  'epoch.quiz.start': 'Commencer le quiz',
  'epoch.quiz.best': 'Meilleur score {best}/{total}',
  'epoch.timeline': 'Sur la frise chronologique',
  'epoch.toc.title': 'Sommaire',
  'epoch.toc.aria': 'Sommaire de cette époque',
  'epoch.toc.events': 'Événements',
  'epoch.toc.persons': 'Personnes',
  'epoch.toc.terms': 'Termes',
  'epoch.toc.consequences': 'Conséquences',
  'epoch.keyfacts.title': 'En un coup d\'œil',
  'epoch.keyfacts.milestones': 'Jalons',
  'epoch.overview.title': 'Aperçu',
  'epoch.events.title': 'Événements clés',
  'epoch.events.only': 'Jalons uniquement ({n})',
  'epoch.persons.title': 'Personnages importants',
  'epoch.terms.title': 'Termes de cette époque',
  'epoch.terms.link': 'Dans le glossaire',
  'epoch.consequences.title': 'Conséquences et importance',
  'epoch.themes.title': 'Thèmes transversaux associés',
  'epoch.nav.prev': 'Époque précédente',
  'epoch.nav.next': 'Époque suivante',
  'epoch.nav.aria': 'Époques voisines',

  'event.notfound': 'Cet événement n\'existe pas.',
  'event.back': 'Époque',
  'event.importance.major': 'Événement majeur',
  'event.importance.label': 'Importance',
  'event.persons.title': 'Personnes impliquées',
  'event.terms.title': 'Termes liés à cet événement',
  'event.themes.title': 'Thèmes transversaux',
  'event.nearby.title': 'À la même époque',
  'event.nav.aria': 'Voisins chronologiques',
  'event.nav.prev': 'Avant',
  'event.nav.next': 'Après',

  'person.notfound': 'Cette personne n\'existe pas.',
  'person.back': 'Époque',
  'person.events.title': 'Événements liés',
  'person.terms.title': 'Termes',
  'person.themes.title': 'Thèmes transversaux',
  'person.contemporaries.title': 'Contemporains',

  'bookmarks.title': 'Favoris',
  'bookmarks.empty.title': 'Pas encore de favoris',
  'bookmarks.empty.text': 'Appuyez sur « {save} » sur une époque, un événement ou une personne pour les rassembler ici.',
  'bookmarks.count': '{entries} enregistré(s). Les favoris sont stockés uniquement sur cet appareil.',

  'notfound.title': 'Introuvable',
  'notfound.heading': 'Page introuvable',
  'notfound.text': 'Cette page n\'existe pas.',
  'notfound.home': 'Aller à la page d\'accueil',

  'theme.label.system': 'Automatique',
  'theme.label.light': 'Clair',
  'theme.label.dark': 'Sombre',
  'theme.buttonTitle': 'Thème : {name} (cliquer pour changer)',

  'quiz.verdict.excellent': 'Excellent !',
  'quiz.verdict.verygood': 'Très bien !',
  'quiz.verdict.good': 'Bien joué.',
  'quiz.verdict.keepgoing': 'Continuez à vous entraîner !',

  'tile.theme.kicker': 'Thème transversal',
  'tile.theme.events': '{events} à travers toutes les époques',

  'timeline.title': 'Frise chronologique',
  'timeline.intro': 'Tous les événements par ordre chronologique, regroupés par époque et par siècle. Les grands points marquent les jalons.',
  'timeline.filter.epoch': 'Filtrer par époque',
  'timeline.filter.region': 'Filtrer par région',
  'timeline.filter.theme': 'Filtrer par thème',
  'timeline.allRegions': 'Toutes les régions',
  'timeline.allThemes': 'Tous les thèmes',
  'timeline.onlyMilestones': 'Jalons uniquement',
  'timeline.toTop': 'Retour en haut',
  'timeline.empty.title': 'Aucun événement',
  'timeline.empty.text': 'Il n\'y a aucune entrée pour cette combinaison de filtres.',

  'regions.title': 'Régions',
  'regions.intro': 'L\'histoire par continent : quels événements et personnages ont façonné chaque région du monde ?',
  'regions.notfound': 'Cette région n\'existe pas.',
  'regions.back': 'Toutes les régions',
  'regions.persons.title': 'Personnes de cette région',

  'themes.title': 'Thèmes transversaux',
  'themes.intro': 'L\'histoire lue transversalement : chaque thème relie des événements, des personnages et des termes de toutes les époques en un même fil conducteur – des origines à nos jours.',
  'themes.notfound': 'Ce thème n\'existe pas.',
  'themes.back': 'Tous les thèmes',
  'themes.empty.title': 'Pas encore de thèmes',
  'themes.empty.text': 'Les thèmes sont en préparation.',
  'themes.empty.link': 'Aller aux époques',
  'themes.intro.title': 'Introduction',
  'themes.course.title': 'À travers les époques',

  'glossary.title': 'Glossaire',
  'glossary.intro': '{terms} de toutes les époques, classés par ordre alphabétique et brièvement expliqués.',
  'glossary.filter': 'Filtrer les termes …',
  'glossary.letters': 'Lettres',
  'glossary.allEpochs': 'Toutes les époques',
  'glossary.none': 'Aucun terme trouvé.',
  'glossary.empty.title': 'Pas encore de termes',
  'glossary.empty.text': 'Le glossaire est en préparation.',

  'search.title': 'Recherche',
  'search.placeholder': 'Événement, personne, époque, thème ou terme …',
  'search.label': 'Terme de recherche',
  'search.all': 'Tous ({n})',
  'search.hint': 'Saisissez au moins deux caractères. Exemples :',
  'search.resultsFor': '{results} pour « {term} »',
  'search.none': 'Aucun résultat pour « {term} ».',
  'search.examples': 'Napoléon, Révolution, Chine, Démocratie, Mur de Berlin',
  'search.tooShort': 'Veuillez saisir un mot d\'au moins deux lettres.',

  'quiz.intro': 'Testez vos connaissances : époque par époque ou mélangées à travers toute l\'histoire du monde. Votre meilleur score est enregistré sur cet appareil.',
  'quiz.notfound': 'Ce quiz n\'existe pas.',
  'quiz.back': 'Aperçu des quiz',
  'quiz.mastered.label': 'Époques maîtrisées (≥ 80 %)',
  'quiz.mastered.value': '{done} sur {total}',
  'quiz.mixed.title': 'Quiz mélangé',
  'quiz.mixed.sub': '{questions} de toutes les époques',
  'quiz.epoch.sub': '{shown} questions sur {total} par partie',
  'quiz.epochTitle': 'Quiz : {epoch}',
  'quiz.best': 'Meilleur score',
  'quiz.notPlayed': 'Pas encore joué',
  'quiz.reset': 'Réinitialiser la progression',
  'quiz.reset.confirm': 'Vraiment supprimer votre progression au quiz ?',
  'quiz.noQuestions.title': 'Aucune question',
  'quiz.noQuestions.text': 'Il n\'y a pas encore de questions pour cette époque.',
  'quiz.questionOf': 'Question {n} sur {total}',
  'quiz.difficulty.easy': 'Facile',
  'quiz.difficulty.medium': 'Moyen',
  'quiz.difficulty.hard': 'Difficile',
  'quiz.correct': 'Correct !',
  'quiz.wrong': 'Pas tout à fait. La réponse est : {answer}',
  'quiz.keyHint': 'Astuce : répondez avec les touches A–D ou 1–4, appuyez sur Entrée pour continuer.',
  'quiz.next': 'Suivant',
  'quiz.finish': 'Résultats',
  'quiz.percentCorrect': '{percent} % de bonnes réponses',
  'quiz.again': 'Rejouer',
  'quiz.other': 'Autre quiz',
  'quiz.toEpoch': 'Aller à l\'époque',
  'quiz.review': 'À revoir',
  'quiz.answerWas': 'Correct : {answer} –',
  'quiz.allCorrect': 'Toutes les questions correctes – excellent !',

  'more.intro': 'D\'autres sections de l\'application, des paramètres et des informations.',
  'more.discover': 'Découvrir',
  'more.themes.sub': '{themes} à travers toutes les époques',
  'more.regions.sub': 'L\'histoire par continent',
  'more.search.sub': 'Rechercher dans tout le contenu',
  'more.bookmarks.sub': '{entries} enregistré(s)',
  'more.settings': 'Paramètres',
  'more.theme.title': 'Thème',
  'more.theme.action': 'Changer',
  'more.progress.title': 'Progression au quiz',
  'more.progress.sub': 'Meilleurs scores et tentatives sur cet appareil',
  'more.progress.action': 'Réinitialiser',
  'more.progress.done': 'Progression réinitialisée',
  'more.offline.title': 'Données hors ligne',
  'more.offline.sub': 'Actualiser les fichiers de l\'application mis en cache',
  'more.offline.action': 'Actualiser',
  'more.offline.done': 'Cache vidé – rechargement …',
  'more.offline.noNetwork': 'Aucune connexion internet – les données hors ligne sont conservées.',
  'more.data.title': 'Supprimer toutes les données',
  'more.data.sub': 'Favoris, progression au quiz et paramètres sur cet appareil',
  'more.data.action': 'Supprimer',
  'more.data.confirm': 'Vraiment supprimer tous les favoris, la progression au quiz et tous les paramètres sur cet appareil ?',
  'more.data.done': 'Toutes les données ont été supprimées',
  'more.about.title': 'À propos de l\'application',
  'more.about.text': 'est une application d\'apprentissage sur les sujets essentiels du passé – des premiers hommes à nos jours, sur tous les continents.',
  'more.about.note': 'Les textes résument l\'état des connaissances généralement admis et sont destinés à l\'école, aux études supérieures et à la culture générale. Les années avant Jésus-Christ sont indiquées par « av. J.-C. », les dates approximatives par « v. ». Les favoris et la progression au quiz restent uniquement sur cet appareil.',
  'more.version': 'Version {version} · {kind} · Fonctionne hors ligne',
  'more.kind.native': 'Version de l\'application',
  'more.kind.pwa': 'Application web progressive',
  'more.privacy': 'Politique de confidentialité',
  'more.imprint': 'Mentions légales',
  'quiz.joker': 'Joker 50:50',
  'quiz.joker.watch': 'Joker 50:50 contre une courte publicité',
  'quiz.joker.used': 'Deux mauvaises réponses ont été supprimées.',
  'quiz.joker.unavailable': 'Aucune publicité n\'est disponible pour le moment. Veuillez réessayer plus tard.',
  'quiz.joker.loading': 'Chargement de la publicité …',
  'more.ads.title': 'Publicité et confidentialité',
  'more.ads.sub': 'Modifier votre consentement pour les publicités personnalisées',
  'more.ads.action': 'Modifier',
  'ads.label': 'Publicité',
};
