// हिन्दी इंटरफ़ेस टेक्स्ट।
export default {
  'app.name': 'विश्व इतिहास',
  'app.description': 'प्रागैतिहासिक काल से वर्तमान तक का विश्व इतिहास: युग, व्यापक विषय, समयरेखा, शब्दकोश, प्रश्नोत्तरी, खोज और बुकमार्क। ऑफ़लाइन भी काम करता है।',
  'app.skipToContent': 'सामग्री पर जाएं',
  'app.brandAria': 'विश्व इतिहास – होम',
  'app.install': 'ऐप इंस्टॉल करें',
  'app.installed': 'ऐप इंस्टॉल हो गया',
  'app.loading': 'सामग्री लोड हो रही है …',
  'app.loadFailed': 'सामग्री लोड नहीं हो सकी',
  'app.retry': 'फिर से कोशिश करें',
  'app.error': 'त्रुटि',
  'app.update.available': 'नया संस्करण उपलब्ध है',
  'app.update.action': 'रीलोड करें',

  'nav.home': 'होम',
  'nav.epochs': 'युग',
  'nav.timeline': 'समयरेखा',
  'nav.themes': 'विषय',
  'nav.glossary': 'शब्दकोश',
  'nav.quiz': 'प्रश्नोत्तरी',
  'nav.bookmarks': 'बुकमार्क',
  'nav.more': 'अधिक',
  'nav.search': 'खोजें',
  'nav.aria.main': 'मुख्य नेविगेशन',
  'nav.aria.bottom': 'नेविगेशन',

  'lang.label': 'भाषा',
  'theme.toggle': 'रंग योजना बदलें',
  'theme.toast': 'रंग योजना: {name}',
  'title.page': '{title} – विश्व इतिहास',

  'year.bc': '{n} ईसा पूर्व',
  'year.ad': '{n} ईस्वी',
  'year.approx': 'लगभग {s}',
  'year.unknown': '?',
  'year.today': 'आज',

  'unit.event.one': 'घटना',
  'unit.event.other': 'घटनाएं',
  'unit.person.one': 'व्यक्ति',
  'unit.person.other': 'व्यक्ति',
  'unit.term.one': 'शब्द',
  'unit.term.other': 'शब्द',
  'unit.theme.one': 'विषय',
  'unit.theme.other': 'विषय',
  'unit.epoch.one': 'युग',
  'unit.epoch.other': 'युग',
  'unit.entry.one': 'प्रविष्टि',
  'unit.entry.other': 'प्रविष्टियां',
  'unit.hit.one': 'परिणाम',
  'unit.hit.other': 'परिणाम',
  'unit.question.one': 'प्रश्न',
  'unit.question.other': 'प्रश्न',
  'unit.region.one': 'क्षेत्र',
  'unit.region.other': 'क्षेत्र',
  'unit.attempt.one': 'प्रयास',
  'unit.attempt.other': 'प्रयास',

  'heading.events': 'घटनाएं',
  'heading.persons': 'व्यक्ति',
  'heading.terms': 'शब्द',

  'century.earliest': '10,000 ईसा पूर्व से पहले',
  'century.bc': '{n}वीं शताब्दी ईसा पूर्व',
  'century.ad': '{n}वीं शताब्दी',

  'ui.milestone': 'महत्वपूर्ण पड़ाव',
  'ui.bookmark.save': 'सहेजें',
  'ui.bookmark.saved': 'सहेजा गया',
  'toast.bookmark.added': 'बुकमार्क सहेजा गया',
  'toast.bookmark.removed': 'बुकमार्क हटाया गया',

  'home.intro': 'पहले मनुष्यों से लेकर आज तक अतीत के सभी आवश्यक विषय। युग, व्यापक विषय और क्षेत्र के अनुसार व्यवस्थित, साथ में एक समयरेखा, एक शब्दकोश और एक प्रश्नोत्तरी।',
  'home.stat.quiz': 'प्रश्नोत्तरी के प्रश्न',
  'home.cta.epochs': 'युगों का अन्वेषण करें',
  'home.cta.timeline': 'समयरेखा',
  'home.cta.quiz': 'प्रश्नोत्तरी शुरू करें',
  'home.install.title': 'ऐप के रूप में इंस्टॉल करें',
  'home.install.ios': 'Safari में शेयर पर टैप करें और फिर होम स्क्रीन पर जोड़ें चुनें। इसके बाद ऐप ऑफ़लाइन भी काम करेगा।',
  'home.install.android': '{name} को अपनी होम स्क्रीन पर इंस्टॉल करें। इसके बाद ऐप ऑफ़लाइन भी काम करेगा।',
  'home.install.action': 'इंस्टॉल करें',
  'home.install.dismiss': 'छिपाएं',
  'home.random.kicker': 'यादृच्छिक घटना',
  'home.random.more': 'और पढ़ें',
  'home.random.again': 'एक और घटना',
  'home.progress.kicker': 'आपकी प्रश्नोत्तरी प्रगति',
  'home.progress.title': '{total} में से {done} युग पूर्ण',
  'home.progress.label': 'प्रगति',
  'home.progress.hint': 'एक युग तब पूर्ण माना जाता है जब आप कम से कम 80 प्रतिशत प्रश्नों के सही उत्तर देते हैं।',
  'home.progress.link': 'प्रश्नोत्तरी पर जाएं',
  'home.section.epochs': 'युग',
  'home.section.themes': 'व्यापक विषय',
  'home.section.regions': 'क्षेत्र',
  'home.section.reference': 'संदर्भ',
  'home.showall': 'सभी दिखाएं',
  'home.epochs.note': 'कालानुक्रमिक क्रम में, पाषाण युग से आज तक।',
  'home.themes.note': 'सहस्राब्दियों से चली आ रही धाराएं।',
  'home.hub.glossary.title': 'शब्दकोश',
  'home.hub.glossary.sub': '{terms} संक्षेप में समझाए गए',
  'home.hub.search.title': 'खोजें',
  'home.hub.search.sub': 'घटनाएं, व्यक्ति, विषय, शब्द',
  'home.hub.bookmarks.title': 'बुकमार्क',
  'home.hub.bookmarks.sub': 'आपके सहेजे गए आइटम',

  'epochs.title': 'युग',
  'epochs.intro': '{count} खंडों में विश्व इतिहास, कालानुक्रमिक क्रम में। हर युग में एक अवलोकन, प्रमुख घटनाएं, महत्वपूर्ण व्यक्ति और उनके परिणाम शामिल हैं।',

  'epoch.notfound': 'यह युग मौजूद नहीं है।',
  'epoch.back': 'सभी युग',
  'epoch.hero.position': 'युग {index} / {total}',
  'epoch.quiz.start': 'प्रश्नोत्तरी शुरू करें',
  'epoch.quiz.best': 'सर्वश्रेष्ठ स्कोर {best}/{total}',
  'epoch.timeline': 'समयरेखा पर',
  'epoch.toc.title': 'विषय-सूची',
  'epoch.toc.aria': 'इस युग की विषय-सूची',
  'epoch.toc.events': 'घटनाएं',
  'epoch.toc.persons': 'व्यक्ति',
  'epoch.toc.terms': 'शब्द',
  'epoch.toc.consequences': 'परिणाम',
  'epoch.keyfacts.title': 'एक नज़र में',
  'epoch.keyfacts.milestones': 'महत्वपूर्ण पड़ाव',
  'epoch.overview.title': 'अवलोकन',
  'epoch.events.title': 'प्रमुख घटनाएं',
  'epoch.events.only': 'केवल महत्वपूर्ण पड़ाव ({n})',
  'epoch.persons.title': 'महत्वपूर्ण व्यक्ति',
  'epoch.terms.title': 'इस युग के शब्द',
  'epoch.terms.link': 'शब्दकोश में',
  'epoch.consequences.title': 'परिणाम और महत्व',
  'epoch.themes.title': 'संबंधित व्यापक विषय',
  'epoch.nav.prev': 'पिछला युग',
  'epoch.nav.next': 'अगला युग',
  'epoch.nav.aria': 'पड़ोसी युग',

  'event.notfound': 'यह घटना मौजूद नहीं है।',
  'event.back': 'युग',
  'event.importance.major': 'प्रमुख घटना',
  'event.importance.label': 'महत्व',
  'event.persons.title': 'शामिल व्यक्ति',
  'event.terms.title': 'इस घटना के लिए शब्द',
  'event.themes.title': 'व्यापक विषय',
  'event.nearby.title': 'इसी युग में उसी समय',
  'event.nav.aria': 'कालानुक्रमिक पड़ोसी',
  'event.nav.prev': 'पहले',
  'event.nav.next': 'बाद में',

  'person.notfound': 'यह व्यक्ति मौजूद नहीं है।',
  'person.back': 'युग',
  'person.events.title': 'संबंधित घटनाएं',
  'person.terms.title': 'शब्द',
  'person.themes.title': 'व्यापक विषय',
  'person.contemporaries.title': 'समकालीन',

  'bookmarks.title': 'बुकमार्क',
  'bookmarks.empty.title': 'अभी तक कोई बुकमार्क नहीं',
  'bookmarks.empty.text': 'किसी युग, घटना या व्यक्ति पर “{save}” टैप करें ताकि उन्हें यहां एकत्र किया जा सके।',
  'bookmarks.count': '{entries} सहेजे गए। बुकमार्क केवल इस डिवाइस पर संग्रहीत होते हैं।',

  'notfound.title': 'नहीं मिला',
  'notfound.heading': 'पृष्ठ नहीं मिला',
  'notfound.text': 'यह पृष्ठ मौजूद नहीं है।',
  'notfound.home': 'होम पेज पर जाएं',

  'theme.label.system': 'स्वचालित',
  'theme.label.light': 'हल्का',
  'theme.label.dark': 'गहरा',
  'theme.buttonTitle': 'रंग योजना: {name} (बदलने के लिए क्लिक करें)',

  'quiz.verdict.excellent': 'शानदार!',
  'quiz.verdict.verygood': 'बहुत अच्छा!',
  'quiz.verdict.good': 'बढ़िया किया।',
  'quiz.verdict.keepgoing': 'अभ्यास जारी रखें!',

  'tile.theme.kicker': 'व्यापक विषय',
  'tile.theme.events': 'सभी युगों में {events}',

  'timeline.title': 'समयरेखा',
  'timeline.intro': 'हर घटना कालानुक्रमिक क्रम में, युग और शताब्दी के अनुसार समूहीकृत। बड़े बिंदु महत्वपूर्ण पड़ावों को दर्शाते हैं।',
  'timeline.filter.epoch': 'युग के अनुसार फ़िल्टर करें',
  'timeline.filter.region': 'क्षेत्र के अनुसार फ़िल्टर करें',
  'timeline.filter.theme': 'विषय के अनुसार फ़िल्टर करें',
  'timeline.allRegions': 'सभी क्षेत्र',
  'timeline.allThemes': 'सभी विषय',
  'timeline.onlyMilestones': 'केवल महत्वपूर्ण पड़ाव',
  'timeline.toTop': 'ऊपर जाएं',
  'timeline.empty.title': 'कोई घटना नहीं',
  'timeline.empty.text': 'इस फ़िल्टर संयोजन के लिए कोई प्रविष्टि नहीं है।',

  'regions.title': 'क्षेत्र',
  'regions.intro': 'महाद्वीप के अनुसार इतिहास: किन घटनाओं और व्यक्तियों ने दुनिया के हर क्षेत्र को आकार दिया?',
  'regions.notfound': 'यह क्षेत्र मौजूद नहीं है।',
  'regions.back': 'सभी क्षेत्र',
  'regions.persons.title': 'इस क्षेत्र के व्यक्ति',

  'themes.title': 'व्यापक विषय',
  'themes.intro': 'युगों के आर-पार पढ़ा गया इतिहास: हर विषय हर युग की घटनाओं, व्यक्तियों और शब्दों को एक धागे में पिरोता है – शुरुआत से लेकर आज तक।',
  'themes.notfound': 'यह विषय मौजूद नहीं है।',
  'themes.back': 'सभी विषय',
  'themes.empty.title': 'अभी तक कोई विषय नहीं',
  'themes.empty.text': 'विषय तैयार किए जा रहे हैं।',
  'themes.empty.link': 'युगों पर जाएं',
  'themes.intro.title': 'परिचय',
  'themes.course.title': 'युगों के माध्यम से',

  'glossary.title': 'शब्दकोश',
  'glossary.intro': 'हर युग के {terms}, वर्णानुक्रम में और संक्षेप में समझाए गए।',
  'glossary.filter': 'शब्द फ़िल्टर करें …',
  'glossary.letters': 'अक्षर',
  'glossary.allEpochs': 'सभी युग',
  'glossary.none': 'कोई शब्द नहीं मिला।',
  'glossary.empty.title': 'अभी तक कोई शब्द नहीं',
  'glossary.empty.text': 'शब्दकोश तैयार किया जा रहा है।',

  'search.title': 'खोजें',
  'search.placeholder': 'घटना, व्यक्ति, युग, विषय या शब्द …',
  'search.label': 'खोज शब्द',
  'search.all': 'सभी ({n})',
  'search.hint': 'कम से कम दो अक्षर दर्ज करें। उदाहरण:',
  'search.resultsFor': '“{term}” के लिए {results}',
  'search.none': '“{term}” के लिए कोई परिणाम नहीं।',
  'search.examples': 'नेपोलियन, क्रांति, चीन, लोकतंत्र, बर्लिन की दीवार',
  'search.tooShort': 'कृपया कम से कम दो अक्षरों वाला शब्द दर्ज करें।',

  'quiz.intro': 'अपने ज्ञान का परीक्षण करें: एक बार में एक युग, या पूरे विश्व इतिहास में मिश्रित। आपका सर्वश्रेष्ठ स्कोर इस डिवाइस पर संग्रहीत होता है।',
  'quiz.notfound': 'यह प्रश्नोत्तरी मौजूद नहीं है।',
  'quiz.back': 'प्रश्नोत्तरी सिंहावलोकन',
  'quiz.mastered.label': 'पूर्ण किए गए युग (≥ 80%)',
  'quiz.mastered.value': '{total} में से {done}',
  'quiz.mixed.title': 'मिश्रित प्रश्नोत्तरी',
  'quiz.mixed.sub': 'सभी युगों से {questions}',
  'quiz.epoch.sub': 'प्रति राउंड {total} में से {shown} प्रश्न',
  'quiz.epochTitle': 'प्रश्नोत्तरी: {epoch}',
  'quiz.best': 'सर्वश्रेष्ठ स्कोर',
  'quiz.notPlayed': 'अभी तक नहीं खेला गया',
  'quiz.reset': 'प्रगति रीसेट करें',
  'quiz.reset.confirm': 'क्या आप वाकई अपनी प्रश्नोत्तरी प्रगति हटाना चाहते हैं?',
  'quiz.noQuestions.title': 'कोई प्रश्न नहीं',
  'quiz.noQuestions.text': 'इस युग के लिए अभी तक कोई प्रश्न नहीं हैं।',
  'quiz.questionOf': 'प्रश्न {n} / {total}',
  'quiz.difficulty.easy': 'आसान',
  'quiz.difficulty.medium': 'मध्यम',
  'quiz.difficulty.hard': 'कठिन',
  'quiz.correct': 'सही!',
  'quiz.wrong': 'बिल्कुल सही नहीं। उत्तर है: {answer}',
  'quiz.keyHint': 'सुझाव: A–D या 1–4 कुंजियों से उत्तर दें, आगे बढ़ने के लिए Enter दबाएं।',
  'quiz.next': 'अगला',
  'quiz.finish': 'परिणाम',
  'quiz.percentCorrect': '{percent}% सही',
  'quiz.again': 'फिर से खेलें',
  'quiz.other': 'एक और प्रश्नोत्तरी',
  'quiz.toEpoch': 'युग पर जाएं',
  'quiz.review': 'दोबारा देखने लायक',
  'quiz.answerWas': 'सही उत्तर: {answer} –',
  'quiz.allCorrect': 'सभी प्रश्न सही – शानदार!',

  'more.intro': 'ऐप के अन्य क्षेत्र, सेटिंग्स और जानकारी।',
  'more.discover': 'खोजें',
  'more.themes.sub': 'सभी युगों में {themes}',
  'more.regions.sub': 'महाद्वीप के अनुसार इतिहास',
  'more.search.sub': 'सभी सामग्री खोजें',
  'more.bookmarks.sub': '{entries} सहेजे गए',
  'more.settings': 'सेटिंग्स',
  'more.theme.title': 'रंग योजना',
  'more.theme.action': 'बदलें',
  'more.progress.title': 'प्रश्नोत्तरी प्रगति',
  'more.progress.sub': 'इस डिवाइस पर सर्वश्रेष्ठ स्कोर और प्रयास',
  'more.progress.action': 'रीसेट करें',
  'more.progress.done': 'प्रगति रीसेट हो गई',
  'more.offline.title': 'ऑफ़लाइन डेटा',
  'more.offline.sub': 'कैश की गई ऐप फ़ाइलों को रीफ़्रेश करें',
  'more.offline.action': 'रीफ़्रेश करें',
  'more.offline.done': 'कैश साफ़ हो गया – रीलोड हो रहा है …',
  'more.offline.noNetwork': 'इंटरनेट कनेक्शन नहीं है – ऑफ़लाइन डेटा रखा गया है।',
  'more.data.title': 'सभी डेटा हटाएं',
  'more.data.sub': 'इस डिवाइस पर बुकमार्क, प्रश्नोत्तरी प्रगति और सेटिंग्स',
  'more.data.action': 'हटाएं',
  'more.data.confirm': 'क्या आप वाकई इस डिवाइस पर सभी बुकमार्क, प्रश्नोत्तरी प्रगति और सेटिंग्स हटाना चाहते हैं?',
  'more.data.done': 'सभी डेटा हटा दिया गया',
  'more.about.title': 'ऐप के बारे में',
  'more.about.text': 'अतीत के आवश्यक विषयों के लिए एक शिक्षण ऐप है – पहले मनुष्यों से लेकर आज तक, हर महाद्वीप पर।',
  'more.about.note': 'ये पाठ शोध की आम तौर पर स्वीकृत स्थिति का सारांश देते हैं और स्कूल, विश्वविद्यालय और सामान्य शिक्षा के लिए लिखे गए हैं। ईसा पूर्व के वर्षों को “ईसा पूर्व” और अनुमानित तिथियों को “लगभग” से चिह्नित किया गया है। बुकमार्क और प्रश्नोत्तरी प्रगति केवल इस डिवाइस पर रहती हैं।',
  'more.version': 'संस्करण {version} · {kind} · ऑफ़लाइन काम करता है',
  'more.kind.native': 'ऐप संस्करण',
  'more.kind.pwa': 'प्रोग्रेसिव वेब ऐप',
  'more.privacy': 'गोपनीयता नीति',
  'more.imprint': 'कानूनी सूचना',
  'quiz.joker': '50:50 जोकर',
  'quiz.joker.watch': 'एक छोटा विज्ञापन देखकर 50:50 जोकर पाएं',
  'quiz.joker.used': 'दो गलत उत्तर हटा दिए गए हैं।',
  'quiz.joker.unavailable': 'अभी कोई विज्ञापन उपलब्ध नहीं है। कृपया बाद में फिर कोशिश करें।',
  'quiz.joker.loading': 'विज्ञापन लोड हो रहा है …',
  'more.ads.title': 'विज्ञापन और गोपनीयता',
  'more.ads.sub': 'व्यक्तिगत विज्ञापनों के लिए अपनी सहमति बदलें',
  'more.ads.action': 'बदलें',
  'ads.label': 'विज्ञापन',
};
