// Testi dell'interfaccia in italiano.
export default {
  'app.name': 'Storia del mondo',
  'app.description': 'Storia del mondo dalla preistoria a oggi: epoche, temi trasversali, linea del tempo, glossario, quiz, ricerca e segnalibri. Funziona offline.',
  'app.skipToContent': 'Vai al contenuto',
  'app.brandAria': 'Storia del mondo – home',
  'app.install': 'Installa l\'app',
  'app.installed': 'App installata',
  'app.loading': 'Caricamento dei contenuti …',
  'app.loadFailed': 'Impossibile caricare i contenuti',
  'app.retry': 'Riprova',
  'app.error': 'Errore',
  'app.update.available': 'Nuova versione disponibile',
  'app.update.action': 'Ricarica',

  'nav.home': 'Home',
  'nav.epochs': 'Epoche',
  'nav.timeline': 'Linea del tempo',
  'nav.themes': 'Temi',
  'nav.glossary': 'Glossario',
  'nav.quiz': 'Quiz',
  'nav.bookmarks': 'Segnalibri',
  'nav.more': 'Altro',
  'nav.search': 'Cerca',
  'nav.aria.main': 'Navigazione principale',
  'nav.aria.bottom': 'Navigazione',

  'lang.label': 'Lingua',
  'theme.toggle': 'Cambia schema colori',
  'theme.toast': 'Schema colori: {name}',
  'title.page': '{title} – Storia del mondo',

  'year.bc': '{n} a.C.',
  'year.ad': '{n} d.C.',
  'year.approx': 'ca. {s}',
  'year.unknown': '?',
  'year.today': 'oggi',

  'unit.event.one': 'evento',
  'unit.event.other': 'eventi',
  'unit.person.one': 'persona',
  'unit.person.other': 'persone',
  'unit.term.one': 'termine',
  'unit.term.other': 'termini',
  'unit.theme.one': 'tema',
  'unit.theme.other': 'temi',
  'unit.epoch.one': 'epoca',
  'unit.epoch.other': 'epoche',
  'unit.entry.one': 'voce',
  'unit.entry.other': 'voci',
  'unit.hit.one': 'risultato',
  'unit.hit.other': 'risultati',
  'unit.question.one': 'domanda',
  'unit.question.other': 'domande',
  'unit.region.one': 'regione',
  'unit.region.other': 'regioni',
  'unit.attempt.one': 'tentativo',
  'unit.attempt.other': 'tentativi',

  'heading.events': 'Eventi',
  'heading.persons': 'Persone',
  'heading.terms': 'Termini',

  'century.earliest': 'Prima del 10.000 a.C.',
  'century.bc': 'Secolo {n} a.C.',
  'century.ad': 'Secolo {n}',

  'ui.milestone': 'Pietra miliare',
  'ui.bookmark.save': 'Salva',
  'ui.bookmark.saved': 'Salvato',
  'toast.bookmark.added': 'Segnalibro salvato',
  'toast.bookmark.removed': 'Segnalibro rimosso',

  'home.intro': 'Tutti gli argomenti essenziali del passato, dai primi esseri umani a oggi. Organizzati per epoca, tema trasversale e regione, con linea del tempo, glossario e quiz.',
  'home.stat.quiz': 'Domande del quiz',
  'home.cta.epochs': 'Esplora le epoche',
  'home.cta.timeline': 'Linea del tempo',
  'home.cta.quiz': 'Inizia il quiz',
  'home.install.title': 'Installa come app',
  'home.install.ios': 'In Safari, tocca Condividi e poi Aggiungi a Home. Da quel momento l\'app funziona anche offline.',
  'home.install.android': 'Installa {name} nella schermata Home. L\'app funziona quindi anche offline.',
  'home.install.action': 'Installa',
  'home.install.dismiss': 'Nascondi',
  'home.random.kicker': 'Evento casuale',
  'home.random.more': 'Leggi di più',
  'home.random.again': 'Altro evento',
  'home.progress.kicker': 'I tuoi progressi nel quiz',
  'home.progress.title': '{done} epoche padroneggiate su {total}',
  'home.progress.label': 'Progresso',
  'home.progress.hint': 'Un\'epoca è considerata padroneggiata quando rispondi correttamente ad almeno l\'80% delle domande.',
  'home.progress.link': 'Vai al quiz',
  'home.section.epochs': 'Epoche',
  'home.section.themes': 'Temi trasversali',
  'home.section.regions': 'Regioni',
  'home.section.reference': 'Consultazione',
  'home.showall': 'Mostra tutto',
  'home.epochs.note': 'In ordine cronologico, dall\'età della pietra a oggi.',
  'home.themes.note': 'Fili conduttori attraverso i millenni.',
  'home.hub.glossary.title': 'Glossario',
  'home.hub.glossary.sub': '{terms} spiegati brevemente',
  'home.hub.search.title': 'Cerca',
  'home.hub.search.sub': 'Eventi, persone, temi, termini',
  'home.hub.bookmarks.title': 'Segnalibri',
  'home.hub.bookmarks.sub': 'Gli elementi che hai salvato',

  'epochs.title': 'Epoche',
  'epochs.intro': 'La storia del mondo in {count} sezioni, in ordine cronologico. Ogni epoca contiene una panoramica, eventi chiave, persone importanti e le loro conseguenze.',

  'epoch.notfound': 'Questa epoca non esiste.',
  'epoch.back': 'Tutte le epoche',
  'epoch.hero.position': 'Epoca {index} di {total}',
  'epoch.quiz.start': 'Inizia il quiz',
  'epoch.quiz.best': 'Miglior punteggio {best}/{total}',
  'epoch.timeline': 'Sulla linea del tempo',
  'epoch.toc.title': 'Contenuti',
  'epoch.toc.aria': 'Contenuti di questa epoca',
  'epoch.toc.events': 'Eventi',
  'epoch.toc.persons': 'Persone',
  'epoch.toc.terms': 'Termini',
  'epoch.toc.consequences': 'Conseguenze',
  'epoch.keyfacts.title': 'In breve',
  'epoch.keyfacts.milestones': 'Pietre miliari',
  'epoch.overview.title': 'Panoramica',
  'epoch.events.title': 'Eventi chiave',
  'epoch.events.only': 'Solo pietre miliari ({n})',
  'epoch.persons.title': 'Persone importanti',
  'epoch.terms.title': 'Termini di questa epoca',
  'epoch.terms.link': 'Nel glossario',
  'epoch.consequences.title': 'Conseguenze e significato',
  'epoch.themes.title': 'Temi trasversali correlati',
  'epoch.nav.prev': 'Epoca precedente',
  'epoch.nav.next': 'Epoca successiva',
  'epoch.nav.aria': 'Epoche vicine',

  'event.notfound': 'Questo evento non esiste.',
  'event.back': 'Epoca',
  'event.importance.major': 'Evento importante',
  'event.importance.label': 'Importanza',
  'event.persons.title': 'Persone coinvolte',
  'event.terms.title': 'Termini relativi a questo evento',
  'event.themes.title': 'Temi trasversali',
  'event.nearby.title': 'Nello stesso periodo in questa epoca',
  'event.nav.aria': 'Vicini cronologici',
  'event.nav.prev': 'Prima',
  'event.nav.next': 'Dopo',

  'person.notfound': 'Questa persona non esiste.',
  'person.back': 'Epoca',
  'person.events.title': 'Eventi collegati',
  'person.terms.title': 'Termini',
  'person.themes.title': 'Temi trasversali',
  'person.contemporaries.title': 'Contemporanei',

  'bookmarks.title': 'Segnalibri',
  'bookmarks.empty.title': 'Ancora nessun segnalibro',
  'bookmarks.empty.text': 'Tocca «{save}» su un\'epoca, un evento o una persona per raccoglierli qui.',
  'bookmarks.count': '{entries} salvato/i. I segnalibri sono memorizzati solo su questo dispositivo.',

  'notfound.title': 'Non trovato',
  'notfound.heading': 'Pagina non trovata',
  'notfound.text': 'Questa pagina non esiste.',
  'notfound.home': 'Vai alla home page',

  'theme.label.system': 'Automatico',
  'theme.label.light': 'Chiaro',
  'theme.label.dark': 'Scuro',
  'theme.buttonTitle': 'Schema colori: {name} (clicca per cambiare)',

  'quiz.verdict.excellent': 'Eccellente!',
  'quiz.verdict.verygood': 'Molto bene!',
  'quiz.verdict.good': 'Ben fatto.',
  'quiz.verdict.keepgoing': 'Continua a esercitarti!',

  'tile.theme.kicker': 'Tema trasversale',
  'tile.theme.events': '{events} in tutte le epoche',

  'timeline.title': 'Linea del tempo',
  'timeline.intro': 'Tutti gli eventi in ordine cronologico, raggruppati per epoca e secolo. I punti grandi indicano le pietre miliari.',
  'timeline.filter.epoch': 'Filtra per epoca',
  'timeline.filter.region': 'Filtra per regione',
  'timeline.filter.theme': 'Filtra per tema',
  'timeline.allRegions': 'Tutte le regioni',
  'timeline.allThemes': 'Tutti i temi',
  'timeline.onlyMilestones': 'Solo pietre miliari',
  'timeline.toTop': 'Torna su',
  'timeline.empty.title': 'Nessun evento',
  'timeline.empty.text': 'Non ci sono voci per questa combinazione di filtri.',

  'regions.title': 'Regioni',
  'regions.intro': 'La storia per continente: quali eventi e persone hanno plasmato ogni regione del mondo?',
  'regions.notfound': 'Questa regione non esiste.',
  'regions.back': 'Tutte le regioni',
  'regions.persons.title': 'Persone di questa regione',

  'themes.title': 'Temi trasversali',
  'themes.intro': 'La storia letta trasversalmente: ogni tema collega eventi, persone e termini di tutte le epoche in un unico filo conduttore, dagli inizi a oggi.',
  'themes.notfound': 'Questo tema non esiste.',
  'themes.back': 'Tutti i temi',
  'themes.empty.title': 'Ancora nessun tema',
  'themes.empty.text': 'I temi sono in preparazione.',
  'themes.empty.link': 'Vai alle epoche',
  'themes.intro.title': 'Introduzione',
  'themes.course.title': 'Attraverso le epoche',

  'glossary.title': 'Glossario',
  'glossary.intro': '{terms} di tutte le epoche, in ordine alfabetico e spiegati brevemente.',
  'glossary.filter': 'Filtra termini …',
  'glossary.letters': 'Lettere',
  'glossary.allEpochs': 'Tutte le epoche',
  'glossary.none': 'Nessun termine trovato.',
  'glossary.empty.title': 'Ancora nessun termine',
  'glossary.empty.text': 'Il glossario è in preparazione.',

  'search.title': 'Cerca',
  'search.placeholder': 'Evento, persona, epoca, tema o termine …',
  'search.label': 'Termine di ricerca',
  'search.all': 'Tutti ({n})',
  'search.hint': 'Inserisci almeno due caratteri. Esempi:',
  'search.resultsFor': '{results} per «{term}»',
  'search.none': 'Nessun risultato per «{term}».',
  'search.examples': 'Napoleone, Rivoluzione, Cina, Democrazia, Muro di Berlino',
  'search.tooShort': 'Inserisci una parola di almeno due lettere.',

  'quiz.intro': 'Metti alla prova le tue conoscenze: epoca per epoca o miste attraverso tutta la storia del mondo. Il tuo miglior punteggio viene salvato su questo dispositivo.',
  'quiz.notfound': 'Questo quiz non esiste.',
  'quiz.back': 'Panoramica dei quiz',
  'quiz.mastered.label': 'Epoche padroneggiate (≥ 80%)',
  'quiz.mastered.value': '{done} su {total}',
  'quiz.mixed.title': 'Quiz misto',
  'quiz.mixed.sub': '{questions} da tutte le epoche',
  'quiz.epoch.sub': '{shown} domande su {total} per round',
  'quiz.epochTitle': 'Quiz: {epoch}',
  'quiz.best': 'Miglior punteggio',
  'quiz.notPlayed': 'Non ancora giocato',
  'quiz.reset': 'Reimposta progressi',
  'quiz.reset.confirm': 'Vuoi davvero eliminare i tuoi progressi nel quiz?',
  'quiz.noQuestions.title': 'Nessuna domanda',
  'quiz.noQuestions.text': 'Non ci sono ancora domande per questa epoca.',
  'quiz.questionOf': 'Domanda {n} di {total}',
  'quiz.difficulty.easy': 'Facile',
  'quiz.difficulty.medium': 'Medio',
  'quiz.difficulty.hard': 'Difficile',
  'quiz.correct': 'Corretto!',
  'quiz.wrong': 'Non proprio. La risposta è: {answer}',
  'quiz.keyHint': 'Suggerimento: rispondi con i tasti A–D o 1–4, premi Invio per continuare.',
  'quiz.next': 'Avanti',
  'quiz.finish': 'Risultati',
  'quiz.percentCorrect': '{percent}% corrette',
  'quiz.again': 'Rigioca',
  'quiz.other': 'Altro quiz',
  'quiz.toEpoch': 'Vai all\'epoca',
  'quiz.review': 'Da rivedere',
  'quiz.answerWas': 'Corretto: {answer} –',
  'quiz.allCorrect': 'Tutte le domande corrette – eccellente!',

  'more.intro': 'Altre aree dell\'app, impostazioni e informazioni.',
  'more.discover': 'Scopri',
  'more.themes.sub': '{themes} in tutte le epoche',
  'more.regions.sub': 'La storia per continente',
  'more.search.sub': 'Cerca in tutti i contenuti',
  'more.bookmarks.sub': '{entries} salvato/i',
  'more.settings': 'Impostazioni',
  'more.theme.title': 'Schema colori',
  'more.theme.action': 'Cambia',
  'more.progress.title': 'Progressi nel quiz',
  'more.progress.sub': 'Migliori punteggi e tentativi su questo dispositivo',
  'more.progress.action': 'Reimposta',
  'more.progress.done': 'Progressi reimpostati',
  'more.offline.title': 'Dati offline',
  'more.offline.sub': 'Aggiorna i file dell\'app memorizzati nella cache',
  'more.offline.action': 'Aggiorna',
  'more.offline.done': 'Cache svuotata – ricaricamento …',
  'more.offline.noNetwork': 'Nessuna connessione a internet – i dati offline vengono mantenuti.',
  'more.data.title': 'Elimina tutti i dati',
  'more.data.sub': 'Segnalibri, progressi nel quiz e impostazioni su questo dispositivo',
  'more.data.action': 'Elimina',
  'more.data.confirm': 'Vuoi davvero eliminare tutti i segnalibri, i progressi nel quiz e tutte le impostazioni su questo dispositivo?',
  'more.data.done': 'Tutti i dati eliminati',
  'more.about.title': 'Informazioni sull\'app',
  'more.about.text': 'è un\'app di apprendimento sugli argomenti essenziali del passato – dai primi esseri umani a oggi, su tutti i continenti.',
  'more.about.note': 'I testi riassumono lo stato della ricerca generalmente accettato e sono scritti per la scuola, l\'università e la cultura generale. Gli anni prima di Cristo sono indicati con «a.C.», le date approssimative con «ca.». I segnalibri e i progressi nel quiz rimangono solo su questo dispositivo.',
  'more.version': 'Versione {version} · {kind} · Funziona offline',
  'more.kind.native': 'Versione dell\'app',
  'more.kind.pwa': 'Progressive Web App',
  'more.privacy': 'Informativa sulla privacy',
  'more.imprint': 'Note legali',
  'quiz.joker': 'Jolly 50:50',
  'quiz.joker.watch': 'Jolly 50:50 in cambio di una breve pubblicità',
  'quiz.joker.used': 'Due risposte sbagliate sono state rimosse.',
  'quiz.joker.unavailable': 'Al momento nessuna pubblicità è disponibile. Riprova più tardi.',
  'quiz.joker.loading': 'Caricamento pubblicità …',
  'more.ads.title': 'Pubblicità e privacy',
  'more.ads.sub': 'Modifica il tuo consenso per la pubblicità personalizzata',
  'more.ads.action': 'Modifica',
  'ads.label': 'Pubblicità',
};
