// 日本語のインターフェーステキスト。
export default {
  'app.name': '世界史',
  'app.description': '先史時代から現代までの世界史：時代区分、テーマ別解説、年表、用語集、クイズ、検索、ブックマーク。オフラインでも利用可能。',
  'app.skipToContent': 'コンテンツへスキップ',
  'app.brandAria': '世界史 – ホーム',
  'app.install': 'アプリをインストール',
  'app.installed': 'アプリはインストール済みです',
  'app.loading': 'コンテンツを読み込み中…',
  'app.loadFailed': 'コンテンツを読み込めませんでした',
  'app.retry': '再試行',
  'app.error': 'エラー',
  'app.update.available': '新しいバージョンがあります',
  'app.update.action': '再読み込み',

  'nav.home': 'ホーム',
  'nav.epochs': '時代',
  'nav.timeline': '年表',
  'nav.themes': 'テーマ',
  'nav.glossary': '用語集',
  'nav.quiz': 'クイズ',
  'nav.bookmarks': 'ブックマーク',
  'nav.more': 'その他',
  'nav.search': '検索',
  'nav.aria.main': 'メインナビゲーション',
  'nav.aria.bottom': 'ナビゲーション',

  'lang.label': '言語',
  'theme.toggle': '配色を変更',
  'theme.toast': '配色：{name}',
  'title.page': '{title} – 世界史',

  'year.bc': '紀元前{n}年',
  'year.ad': '{n}年',
  'year.approx': '約{s}',
  'year.unknown': '？',
  'year.today': '今日',

  'unit.event.one': '件の出来事',
  'unit.event.other': '件の出来事',
  'unit.person.one': '人の人物',
  'unit.person.other': '人の人物',
  'unit.term.one': '件の用語',
  'unit.term.other': '件の用語',
  'unit.theme.one': '件のテーマ',
  'unit.theme.other': '件のテーマ',
  'unit.epoch.one': '件の時代',
  'unit.epoch.other': '件の時代',
  'unit.entry.one': '件',
  'unit.entry.other': '件',
  'unit.hit.one': '件の結果',
  'unit.hit.other': '件の結果',
  'unit.question.one': '問',
  'unit.question.other': '問',
  'unit.region.one': '件の地域',
  'unit.region.other': '件の地域',
  'unit.attempt.one': '回',
  'unit.attempt.other': '回',

  'heading.events': '出来事',
  'heading.persons': '人物',
  'heading.terms': '用語',

  'century.earliest': '紀元前10000年以前',
  'century.bc': '紀元前{n}世紀',
  'century.ad': '{n}世紀',

  'ui.milestone': '重要な出来事',
  'ui.bookmark.save': '保存',
  'ui.bookmark.saved': '保存済み',
  'toast.bookmark.added': 'ブックマークを保存しました',
  'toast.bookmark.removed': 'ブックマークを削除しました',

  'home.intro': '最初の人類から現代まで、過去のあらゆる重要なテーマを網羅。時代、テーマ、地域別に整理し、年表、用語集、クイズも用意しています。',
  'home.stat.quiz': 'クイズの問題数',
  'home.cta.epochs': '時代を見る',
  'home.cta.timeline': '年表',
  'home.cta.quiz': 'クイズを始める',
  'home.install.title': 'アプリとしてインストール',
  'home.install.ios': 'Safariで共有をタップし、「ホーム画面に追加」を選んでください。これによりオフラインでも利用できます。',
  'home.install.android': '{name}をホーム画面にインストールしてください。これによりオフラインでも利用できます。',
  'home.install.action': 'インストール',
  'home.install.dismiss': '非表示',
  'home.random.kicker': 'ランダムな出来事',
  'home.random.more': '続きを読む',
  'home.random.again': '別の出来事',
  'home.progress.kicker': 'クイズの進捗状況',
  'home.progress.title': '{total}時代中{done}時代を習得済み',
  'home.progress.label': '進捗',
  'home.progress.hint': '正答率が80パーセント以上になると、その時代は習得済みとみなされます。',
  'home.progress.link': 'クイズへ進む',
  'home.section.epochs': '時代',
  'home.section.themes': 'テーマ',
  'home.section.regions': '地域',
  'home.section.reference': '参考資料',
  'home.showall': 'すべて表示',
  'home.epochs.note': '石器時代から現代まで、時系列順に並んでいます。',
  'home.themes.note': '数千年にわたって続く流れ。',
  'home.hub.glossary.title': '用語集',
  'home.hub.glossary.sub': '{terms}を簡潔に解説',
  'home.hub.search.title': '検索',
  'home.hub.search.sub': '出来事、人物、テーマ、用語',
  'home.hub.bookmarks.title': 'ブックマーク',
  'home.hub.bookmarks.sub': '保存した項目',

  'epochs.title': '時代',
  'epochs.intro': '世界史を{count}のセクションに分け、時系列順に紹介します。各時代には概要、主な出来事、重要人物とその影響が含まれます。',

  'epoch.notfound': 'この時代は存在しません。',
  'epoch.back': 'すべての時代',
  'epoch.hero.position': '第{index}時代（全{total}時代中）',
  'epoch.quiz.start': 'クイズを始める',
  'epoch.quiz.best': '最高スコア {best}/{total}',
  'epoch.timeline': '年表で見る',
  'epoch.toc.title': '目次',
  'epoch.toc.aria': 'この時代の目次',
  'epoch.toc.events': '出来事',
  'epoch.toc.persons': '人物',
  'epoch.toc.terms': '用語',
  'epoch.toc.consequences': '影響',
  'epoch.keyfacts.title': '概要',
  'epoch.keyfacts.milestones': '重要な出来事',
  'epoch.overview.title': '概観',
  'epoch.events.title': '主な出来事',
  'epoch.events.only': '重要な出来事のみ（{n}）',
  'epoch.persons.title': '重要人物',
  'epoch.terms.title': 'この時代の用語',
  'epoch.terms.link': '用語集で見る',
  'epoch.consequences.title': '影響と意義',
  'epoch.themes.title': '関連するテーマ',
  'epoch.nav.prev': '前の時代',
  'epoch.nav.next': '次の時代',
  'epoch.nav.aria': '隣接する時代',

  'event.notfound': 'この出来事は存在しません。',
  'event.back': '時代',
  'event.importance.major': '重要な出来事',
  'event.importance.label': '重要度',
  'event.persons.title': '関係した人物',
  'event.terms.title': 'この出来事に関する用語',
  'event.themes.title': 'テーマ',
  'event.nearby.title': '同じ時代の同時期の出来事',
  'event.nav.aria': '時系列で前後する出来事',
  'event.nav.prev': '前へ',
  'event.nav.next': '次へ',

  'person.notfound': 'この人物は存在しません。',
  'person.back': '時代',
  'person.events.title': '関連する出来事',
  'person.terms.title': '用語',
  'person.themes.title': 'テーマ',
  'person.contemporaries.title': '同時代の人物',

  'bookmarks.title': 'ブックマーク',
  'bookmarks.empty.title': 'ブックマークはまだありません',
  'bookmarks.empty.text': '時代、出来事、人物のページで「{save}」をタップすると、ここに収集されます。',
  'bookmarks.count': '{entries}件保存済み。ブックマークはこの端末にのみ保存されます。',

  'notfound.title': '見つかりません',
  'notfound.heading': 'ページが見つかりません',
  'notfound.text': 'このページは存在しません。',
  'notfound.home': 'ホームへ戻る',

  'theme.label.system': '自動',
  'theme.label.light': 'ライト',
  'theme.label.dark': 'ダーク',
  'theme.buttonTitle': '配色：{name}（クリックで変更）',

  'quiz.verdict.excellent': '素晴らしい！',
  'quiz.verdict.verygood': 'とても良いです！',
  'quiz.verdict.good': 'よくできました。',
  'quiz.verdict.keepgoing': 'その調子で練習を続けましょう！',

  'tile.theme.kicker': 'テーマ',
  'tile.theme.events': '全時代にわたる{events}',

  'timeline.title': '年表',
  'timeline.intro': 'すべての出来事を時系列順に、時代と世紀ごとにグループ化しています。大きな点は重要な出来事を示します。',
  'timeline.filter.epoch': '時代で絞り込む',
  'timeline.filter.region': '地域で絞り込む',
  'timeline.filter.theme': 'テーマで絞り込む',
  'timeline.allRegions': 'すべての地域',
  'timeline.allThemes': 'すべてのテーマ',
  'timeline.onlyMilestones': '重要な出来事のみ',
  'timeline.toTop': 'トップへ戻る',
  'timeline.empty.title': '出来事がありません',
  'timeline.empty.text': 'この絞り込み条件に該当する項目はありません。',

  'regions.title': '地域',
  'regions.intro': '大陸別の歴史：それぞれの地域を形作った出来事や人物とは？',
  'regions.notfound': 'この地域は存在しません。',
  'regions.back': 'すべての地域',
  'regions.persons.title': 'この地域出身の人物',

  'themes.title': 'テーマ',
  'themes.intro': '時代を横断して読む歴史：各テーマは、あらゆる時代の出来事・人物・用語を一本の流れとしてつなぎます――始まりから現代まで。',
  'themes.notfound': 'このテーマは存在しません。',
  'themes.back': 'すべてのテーマ',
  'themes.empty.title': 'テーマはまだありません',
  'themes.empty.text': 'テーマは準備中です。',
  'themes.empty.link': '時代へ進む',
  'themes.intro.title': '導入',
  'themes.course.title': '時代を通して',

  'glossary.title': '用語集',
  'glossary.intro': '全時代の{terms}をアルファベット順に簡潔に解説しています。',
  'glossary.filter': '用語を絞り込む…',
  'glossary.letters': '文字',
  'glossary.allEpochs': 'すべての時代',
  'glossary.none': '用語が見つかりません。',
  'glossary.empty.title': '用語はまだありません',
  'glossary.empty.text': '用語集は準備中です。',

  'search.title': '検索',
  'search.placeholder': '出来事、人物、時代、テーマ、用語など…',
  'search.label': '検索語',
  'search.all': 'すべて（{n}）',
  'search.hint': '2文字以上で入力してください。例：',
  'search.resultsFor': '「{term}」の{results}',
  'search.none': '「{term}」に一致する結果はありません。',
  'search.examples': 'ナポレオン、革命、中国、民主主義、ベルリンの壁',
  'search.tooShort': '2文字以上の単語を入力してください。',

  'quiz.intro': '知識を試そう：時代ごとに、または世界史全体からのミックス形式で。最高スコアはこの端末に保存されます。',
  'quiz.notfound': 'このクイズは存在しません。',
  'quiz.back': 'クイズ一覧',
  'quiz.mastered.label': '習得済みの時代（80％以上）',
  'quiz.mastered.value': '{total}時代中{done}時代',
  'quiz.mixed.title': 'ミックスクイズ',
  'quiz.mixed.sub': '全時代からの{questions}',
  'quiz.epoch.sub': '1ラウンドあたり{total}問中{shown}問',
  'quiz.epochTitle': 'クイズ：{epoch}',
  'quiz.best': '最高スコア',
  'quiz.notPlayed': 'まだプレイしていません',
  'quiz.reset': '進捗をリセット',
  'quiz.reset.confirm': 'クイズの進捗を本当に削除しますか？',
  'quiz.noQuestions.title': '問題がありません',
  'quiz.noQuestions.text': 'この時代の問題はまだありません。',
  'quiz.questionOf': '問題 {n}／{total}',
  'quiz.difficulty.easy': '易しい',
  'quiz.difficulty.medium': '普通',
  'quiz.difficulty.hard': '難しい',
  'quiz.correct': '正解！',
  'quiz.wrong': '残念、正解は「{answer}」です',
  'quiz.keyHint': 'ヒント：キーA～Dまたは1～4で回答し、Enterキーで次に進みます。',
  'quiz.next': '次へ',
  'quiz.finish': '結果',
  'quiz.percentCorrect': '正答率{percent}％',
  'quiz.again': 'もう一度プレイ',
  'quiz.other': '別のクイズ',
  'quiz.toEpoch': 'この時代へ進む',
  'quiz.review': 'もう一度見直す価値あり',
  'quiz.answerWas': '正解：{answer} –',
  'quiz.allCorrect': '全問正解――素晴らしい！',

  'more.intro': 'アプリのその他の機能、設定、情報。',
  'more.discover': '探す',
  'more.themes.sub': '全時代にわたる{themes}',
  'more.regions.sub': '大陸別の歴史',
  'more.search.sub': 'すべてのコンテンツを検索',
  'more.bookmarks.sub': '{entries}件保存済み',
  'more.settings': '設定',
  'more.theme.title': '配色',
  'more.theme.action': '変更',
  'more.progress.title': 'クイズの進捗',
  'more.progress.sub': 'この端末での最高スコアと挑戦回数',
  'more.progress.action': 'リセット',
  'more.progress.done': '進捗をリセットしました',
  'more.offline.title': 'オフラインデータ',
  'more.offline.sub': 'キャッシュされたアプリファイルを更新',
  'more.offline.action': '更新',
  'more.offline.done': 'キャッシュを削除しました――再読み込み中…',
  'more.offline.noNetwork': 'インターネット接続がありません――オフラインデータは保持されます。',
  'more.data.title': 'すべてのデータを削除',
  'more.data.sub': 'この端末のブックマーク、クイズの進捗、設定',
  'more.data.action': '削除',
  'more.data.confirm': 'この端末のブックマーク、クイズの進捗、設定をすべて本当に削除しますか？',
  'more.data.done': 'すべてのデータを削除しました',
  'more.about.title': 'このアプリについて',
  'more.about.text': 'は、最初の人類から現代まで、あらゆる大陸にわたる過去の重要なテーマを学べる学習アプリです。',
  'more.about.note': '本文は広く認められた研究成果を要約したもので、学校教育、大学教育、一般教養向けに書かれています。紀元前の年は「紀元前」、おおよその年代は「約」と表記されます。ブックマークとクイズの進捗はこの端末にのみ保存されます。',
  'more.version': 'バージョン {version} · {kind} · オフライン対応',
  'more.kind.native': 'アプリ版',
  'more.kind.pwa': 'プログレッシブウェブアプリ',
  'more.privacy': 'プライバシーポリシー',
  'more.imprint': '法的情報',
  'quiz.joker': '50:50ジョーカー',
  'quiz.joker.watch': '短い広告を見て50:50ジョーカーを獲得',
  'quiz.joker.used': '誤った選択肢が2つ削除されました。',
  'quiz.joker.unavailable': '現在利用できる広告がありません。しばらくしてからもう一度お試しください。',
  'quiz.joker.loading': '広告を読み込み中…',
  'more.ads.title': '広告とプライバシー',
  'more.ads.sub': 'パーソナライズ広告への同意を変更',
  'more.ads.action': '変更',
  'ads.label': '広告',
};
