// Polskie teksty interfejsu.
export default {
  'app.name': 'Historia świata',
  'app.description': 'Historia świata od prehistorii do współczesności: epoki, tematy przekrojowe, oś czasu, słowniczek, quiz, wyszukiwanie i zakładki. Działa offline.',
  'app.skipToContent': 'Przejdź do treści',
  'app.brandAria': 'Historia świata – strona główna',
  'app.install': 'Zainstaluj aplikację',
  'app.installed': 'Aplikacja zainstalowana',
  'app.loading': 'Wczytywanie treści …',
  'app.loadFailed': 'Nie udało się wczytać treści',
  'app.retry': 'Spróbuj ponownie',
  'app.error': 'Błąd',
  'app.update.available': 'Dostępna nowa wersja',
  'app.update.action': 'Odśwież',

  'nav.home': 'Start',
  'nav.epochs': 'Epoki',
  'nav.timeline': 'Oś czasu',
  'nav.themes': 'Tematy',
  'nav.glossary': 'Słowniczek',
  'nav.quiz': 'Quiz',
  'nav.bookmarks': 'Zakładki',
  'nav.more': 'Więcej',
  'nav.search': 'Szukaj',
  'nav.aria.main': 'Nawigacja główna',
  'nav.aria.bottom': 'Nawigacja',

  'lang.label': 'Język',
  'theme.toggle': 'Zmień motyw kolorów',
  'theme.toast': 'Motyw kolorów: {name}',
  'title.page': '{title} – Historia świata',

  'year.bc': '{n} p.n.e.',
  'year.ad': '{n} n.e.',
  'year.approx': 'ok. {s}',
  'year.unknown': '?',
  'year.today': 'dziś',

  'unit.event.one': 'wydarzenie',
  'unit.event.other': 'wydarzenia',
  'unit.event.few': 'wydarzenia',
  'unit.event.many': 'wydarzeń',
  'unit.person.one': 'osoba',
  'unit.person.other': 'osoby',
  'unit.person.few': 'osoby',
  'unit.person.many': 'osób',
  'unit.term.one': 'pojęcie',
  'unit.term.other': 'pojęcia',
  'unit.term.few': 'pojęcia',
  'unit.term.many': 'pojęć',
  'unit.theme.one': 'temat',
  'unit.theme.other': 'tematu',
  'unit.theme.few': 'tematy',
  'unit.theme.many': 'tematów',
  'unit.epoch.one': 'epoka',
  'unit.epoch.other': 'epoki',
  'unit.epoch.few': 'epoki',
  'unit.epoch.many': 'epok',
  'unit.entry.one': 'wpis',
  'unit.entry.other': 'wpisu',
  'unit.entry.few': 'wpisy',
  'unit.entry.many': 'wpisów',
  'unit.hit.one': 'wynik',
  'unit.hit.other': 'wyniku',
  'unit.hit.few': 'wyniki',
  'unit.hit.many': 'wyników',
  'unit.question.one': 'pytanie',
  'unit.question.other': 'pytania',
  'unit.question.few': 'pytania',
  'unit.question.many': 'pytań',
  'unit.region.one': 'region',
  'unit.region.other': 'regionu',
  'unit.region.few': 'regiony',
  'unit.region.many': 'regionów',
  'unit.attempt.one': 'próba',
  'unit.attempt.other': 'próby',
  'unit.attempt.few': 'próby',
  'unit.attempt.many': 'prób',

  'heading.events': 'Wydarzenia',
  'heading.persons': 'Osoby',
  'heading.terms': 'Pojęcia',

  'century.earliest': 'Przed 10 000 r. p.n.e.',
  'century.bc': '{n} wiek p.n.e.',
  'century.ad': '{n} wiek',

  'ui.milestone': 'Kamień milowy',
  'ui.bookmark.save': 'Zapisz',
  'ui.bookmark.saved': 'Zapisano',
  'toast.bookmark.added': 'Zakładka zapisana',
  'toast.bookmark.removed': 'Zakładka usunięta',

  'home.intro': 'Wszystkie najważniejsze tematy przeszłości – od pierwszych ludzi po współczesność. Uporządkowane według epok, tematów przekrojowych i regionów, z osią czasu, słowniczkiem i quizem.',
  'home.stat.quiz': 'Pytania quizowe',
  'home.cta.epochs': 'Odkryj epoki',
  'home.cta.timeline': 'Oś czasu',
  'home.cta.quiz': 'Rozpocznij quiz',
  'home.install.title': 'Zainstaluj jako aplikację',
  'home.install.ios': 'W Safari dotknij Udostępnij, a następnie Dodaj do ekranu początkowego. Potem aplikacja działa również offline.',
  'home.install.android': 'Zainstaluj {name} na ekranie głównym. Aplikacja będzie wtedy działać również offline.',
  'home.install.action': 'Zainstaluj',
  'home.install.dismiss': 'Ukryj',
  'home.random.kicker': 'Losowe wydarzenie',
  'home.random.more': 'Czytaj dalej',
  'home.random.again': 'Inne wydarzenie',
  'home.progress.kicker': 'Twój postęp w quizie',
  'home.progress.title': 'Opanowano {done} z {total} epok',
  'home.progress.label': 'Postęp',
  'home.progress.hint': 'Epoka jest uznawana za opanowaną, gdy odpowiesz poprawnie na co najmniej 80 procent pytań.',
  'home.progress.link': 'Przejdź do quizu',
  'home.section.epochs': 'Epoki',
  'home.section.themes': 'Tematy przekrojowe',
  'home.section.regions': 'Regiony',
  'home.section.reference': 'Materiały źródłowe',
  'home.showall': 'Pokaż wszystko',
  'home.epochs.note': 'W porządku chronologicznym, od epoki kamienia do dziś.',
  'home.themes.note': 'Wątki przewijające się przez tysiąclecia.',
  'home.hub.glossary.title': 'Słowniczek',
  'home.hub.glossary.sub': '{terms} krótko wyjaśnionych',
  'home.hub.search.title': 'Szukaj',
  'home.hub.search.sub': 'Wydarzenia, osoby, tematy, pojęcia',
  'home.hub.bookmarks.title': 'Zakładki',
  'home.hub.bookmarks.sub': 'Twoje zapisane elementy',

  'epochs.title': 'Epoki',
  'epochs.intro': 'Historia świata w {count} rozdziałach, w porządku chronologicznym. Każda epoka zawiera przegląd, kluczowe wydarzenia, ważne osoby i ich następstwa.',

  'epoch.notfound': 'Ta epoka nie istnieje.',
  'epoch.back': 'Wszystkie epoki',
  'epoch.hero.position': 'Epoka {index} z {total}',
  'epoch.quiz.start': 'Rozpocznij quiz',
  'epoch.quiz.best': 'Najlepszy wynik {best}/{total}',
  'epoch.timeline': 'Na osi czasu',
  'epoch.toc.title': 'Spis treści',
  'epoch.toc.aria': 'Spis treści tej epoki',
  'epoch.toc.events': 'Wydarzenia',
  'epoch.toc.persons': 'Osoby',
  'epoch.toc.terms': 'Pojęcia',
  'epoch.toc.consequences': 'Następstwa',
  'epoch.keyfacts.title': 'W skrócie',
  'epoch.keyfacts.milestones': 'Kamienie milowe',
  'epoch.overview.title': 'Przegląd',
  'epoch.events.title': 'Kluczowe wydarzenia',
  'epoch.events.only': 'Tylko kamienie milowe ({n})',
  'epoch.persons.title': 'Ważne osoby',
  'epoch.terms.title': 'Pojęcia z tej epoki',
  'epoch.terms.link': 'W słowniczku',
  'epoch.consequences.title': 'Następstwa i znaczenie',
  'epoch.themes.title': 'Powiązane tematy przekrojowe',
  'epoch.nav.prev': 'Poprzednia epoka',
  'epoch.nav.next': 'Następna epoka',
  'epoch.nav.aria': 'Sąsiednie epoki',

  'event.notfound': 'To wydarzenie nie istnieje.',
  'event.back': 'Epoka',
  'event.importance.major': 'Ważne wydarzenie',
  'event.importance.label': 'Znaczenie',
  'event.persons.title': 'Osoby zaangażowane',
  'event.terms.title': 'Pojęcia dotyczące tego wydarzenia',
  'event.themes.title': 'Tematy przekrojowe',
  'event.nearby.title': 'W tym samym czasie w tej epoce',
  'event.nav.aria': 'Sąsiedzi chronologiczni',
  'event.nav.prev': 'Wcześniej',
  'event.nav.next': 'Później',

  'person.notfound': 'Ta osoba nie istnieje.',
  'person.back': 'Epoka',
  'person.events.title': 'Powiązane wydarzenia',
  'person.terms.title': 'Pojęcia',
  'person.themes.title': 'Tematy przekrojowe',
  'person.contemporaries.title': 'Współcześni',

  'bookmarks.title': 'Zakładki',
  'bookmarks.empty.title': 'Brak zakładek',
  'bookmarks.empty.text': 'Dotknij „{save}” przy epoce, wydarzeniu lub osobie, aby zebrać je tutaj.',
  'bookmarks.count': 'Zapisano: {entries}. Zakładki są przechowywane tylko na tym urządzeniu.',

  'notfound.title': 'Nie znaleziono',
  'notfound.heading': 'Nie znaleziono strony',
  'notfound.text': 'Ta strona nie istnieje.',
  'notfound.home': 'Przejdź do strony głównej',

  'theme.label.system': 'Automatyczny',
  'theme.label.light': 'Jasny',
  'theme.label.dark': 'Ciemny',
  'theme.buttonTitle': 'Motyw kolorów: {name} (kliknij, aby zmienić)',

  'quiz.verdict.excellent': 'Znakomicie!',
  'quiz.verdict.verygood': 'Bardzo dobrze!',
  'quiz.verdict.good': 'Dobra robota.',
  'quiz.verdict.keepgoing': 'Ćwicz dalej!',

  'tile.theme.kicker': 'Temat przekrojowy',
  'tile.theme.events': '{events} we wszystkich epokach',

  'timeline.title': 'Oś czasu',
  'timeline.intro': 'Wszystkie wydarzenia w porządku chronologicznym, pogrupowane według epoki i wieku. Duże kropki oznaczają kamienie milowe.',
  'timeline.filter.epoch': 'Filtruj według epoki',
  'timeline.filter.region': 'Filtruj według regionu',
  'timeline.filter.theme': 'Filtruj według tematu',
  'timeline.allRegions': 'Wszystkie regiony',
  'timeline.allThemes': 'Wszystkie tematy',
  'timeline.onlyMilestones': 'Tylko kamienie milowe',
  'timeline.toTop': 'Powrót do góry',
  'timeline.empty.title': 'Brak wydarzeń',
  'timeline.empty.text': 'Dla tej kombinacji filtrów nie ma żadnych wpisów.',

  'regions.title': 'Regiony',
  'regions.intro': 'Historia według kontynentów: jakie wydarzenia i osoby ukształtowały poszczególne regiony świata?',
  'regions.notfound': 'Ten region nie istnieje.',
  'regions.back': 'Wszystkie regiony',
  'regions.persons.title': 'Osoby z tego regionu',

  'themes.title': 'Tematy przekrojowe',
  'themes.intro': 'Historia czytana w poprzek epok: każdy temat łączy wydarzenia, osoby i pojęcia ze wszystkich epok w jedną nić – od początków po współczesność.',
  'themes.notfound': 'Ten temat nie istnieje.',
  'themes.back': 'Wszystkie tematy',
  'themes.empty.title': 'Brak jeszcze tematów',
  'themes.empty.text': 'Tematy są przygotowywane.',
  'themes.empty.link': 'Przejdź do epok',
  'themes.intro.title': 'Wprowadzenie',
  'themes.course.title': 'Przez epoki',

  'glossary.title': 'Słowniczek',
  'glossary.intro': '{terms} ze wszystkich epok, w porządku alfabetycznym i krótko wyjaśnione.',
  'glossary.filter': 'Filtruj pojęcia …',
  'glossary.letters': 'Litery',
  'glossary.allEpochs': 'Wszystkie epoki',
  'glossary.none': 'Nie znaleziono pojęć.',
  'glossary.empty.title': 'Brak jeszcze pojęć',
  'glossary.empty.text': 'Słowniczek jest przygotowywany.',

  'search.title': 'Szukaj',
  'search.placeholder': 'Wydarzenie, osoba, epoka, temat lub pojęcie …',
  'search.label': 'Wyszukiwane hasło',
  'search.all': 'Wszystko ({n})',
  'search.hint': 'Wpisz co najmniej dwa znaki. Przykłady:',
  'search.resultsFor': '{results} dla „{term}”',
  'search.none': 'Brak wyników dla „{term}”.',
  'search.examples': 'Napoleon, Rewolucja, Chiny, Demokracja, Mur Berliński',
  'search.tooShort': 'Wpisz słowo składające się z co najmniej dwóch liter.',

  'quiz.intro': 'Sprawdź swoją wiedzę: epoka po epoce lub w wersji mieszanej z całej historii świata. Twój najlepszy wynik jest zapisywany na tym urządzeniu.',
  'quiz.notfound': 'Ten quiz nie istnieje.',
  'quiz.back': 'Przegląd quizów',
  'quiz.mastered.label': 'Opanowane epoki (≥ 80%)',
  'quiz.mastered.value': '{done} z {total}',
  'quiz.mixed.title': 'Quiz mieszany',
  'quiz.mixed.sub': '{questions} ze wszystkich epok',
  'quiz.epoch.sub': '{shown} z {total} pytań na rundę',
  'quiz.epochTitle': 'Quiz: {epoch}',
  'quiz.best': 'Najlepszy wynik',
  'quiz.notPlayed': 'Jeszcze nie grano',
  'quiz.reset': 'Zresetuj postęp',
  'quiz.reset.confirm': 'Czy na pewno usunąć postęp quizu?',
  'quiz.noQuestions.title': 'Brak pytań',
  'quiz.noQuestions.text': 'Dla tej epoki nie ma jeszcze pytań.',
  'quiz.questionOf': 'Pytanie {n} z {total}',
  'quiz.difficulty.easy': 'Łatwy',
  'quiz.difficulty.medium': 'Średni',
  'quiz.difficulty.hard': 'Trudny',
  'quiz.correct': 'Dobrze!',
  'quiz.wrong': 'Niestety źle. Prawidłowa odpowiedź: {answer}',
  'quiz.keyHint': 'Wskazówka: odpowiadaj klawiszami A–D lub 1–4, Enter przechodzi dalej.',
  'quiz.next': 'Dalej',
  'quiz.finish': 'Wyniki',
  'quiz.percentCorrect': '{percent}% poprawnych odpowiedzi',
  'quiz.again': 'Zagraj ponownie',
  'quiz.other': 'Inny quiz',
  'quiz.toEpoch': 'Przejdź do epoki',
  'quiz.review': 'Warto powtórzyć',
  'quiz.answerWas': 'Prawidłowa odpowiedź: {answer} –',
  'quiz.allCorrect': 'Wszystkie odpowiedzi poprawne – znakomicie!',

  'more.intro': 'Więcej obszarów aplikacji, ustawienia i informacje.',
  'more.discover': 'Odkrywaj',
  'more.themes.sub': '{themes} przekrojowo przez wszystkie epoki',
  'more.regions.sub': 'Historia według kontynentów',
  'more.search.sub': 'Przeszukaj całą zawartość',
  'more.bookmarks.sub': 'Zapisano: {entries}',
  'more.settings': 'Ustawienia',
  'more.theme.title': 'Motyw kolorów',
  'more.theme.action': 'Zmień',
  'more.progress.title': 'Postęp w quizie',
  'more.progress.sub': 'Najlepsze wyniki i próby na tym urządzeniu',
  'more.progress.action': 'Resetuj',
  'more.progress.done': 'Postęp zresetowany',
  'more.offline.title': 'Dane offline',
  'more.offline.sub': 'Odśwież zapisane w pamięci podręcznej pliki aplikacji',
  'more.offline.action': 'Odśwież',
  'more.offline.done': 'Pamięć podręczna wyczyszczona – trwa ponowne wczytywanie …',
  'more.offline.noNetwork': 'Brak połączenia z internetem – dane offline pozostają zachowane.',
  'more.data.title': 'Usuń wszystkie dane',
  'more.data.sub': 'Zakładki, postęp w quizie i ustawienia na tym urządzeniu',
  'more.data.action': 'Usuń',
  'more.data.confirm': 'Czy na pewno usunąć wszystkie zakładki, postęp w quizie i ustawienia na tym urządzeniu?',
  'more.data.done': 'Wszystkie dane usunięte',
  'more.about.title': 'O aplikacji',
  'more.about.text': 'to aplikacja edukacyjna poświęcona najważniejszym tematom z przeszłości – od pierwszych ludzi po współczesność, na wszystkich kontynentach.',
  'more.about.note': 'Teksty podsumowują ogólnie przyjęty stan wiedzy i są przeznaczone dla szkoły, studiów i edukacji ogólnej. Lata przed naszą erą są oznaczone jako „p.n.e.”, daty przybliżone jako „ok.”. Zakładki i postęp w quizie pozostają wyłącznie na tym urządzeniu.',
  'more.version': 'Wersja {version} · {kind} · Działa offline',
  'more.kind.native': 'Wersja aplikacji',
  'more.kind.pwa': 'Progresywna aplikacja webowa',
  'more.privacy': 'Polityka prywatności',
  'more.imprint': 'Nota prawna',
  'quiz.joker': 'Joker 50:50',
  'quiz.joker.watch': 'Joker 50:50 za krótką reklamę',
  'quiz.joker.used': 'Usunięto dwie błędne odpowiedzi.',
  'quiz.joker.unavailable': 'Obecnie żadna reklama nie jest dostępna. Spróbuj ponownie później.',
  'quiz.joker.loading': 'Wczytywanie reklamy …',
  'more.ads.title': 'Reklamy i prywatność',
  'more.ads.sub': 'Zmień zgodę na spersonalizowane reklamy',
  'more.ads.action': 'Zmień',
  'ads.label': 'Reklama',
};
