// Textos de interface em português brasileiro.
export default {
  'app.name': 'História Mundial',
  'app.description': 'História mundial da pré-história até os dias de hoje: épocas, temas transversais, linha do tempo, glossário, quiz, busca e favoritos. Funciona offline.',
  'app.skipToContent': 'Pular para o conteúdo',
  'app.brandAria': 'História Mundial – início',
  'app.install': 'Instalar aplicativo',
  'app.installed': 'Aplicativo instalado',
  'app.loading': 'Carregando conteúdo …',
  'app.loadFailed': 'Não foi possível carregar o conteúdo',
  'app.retry': 'Tentar novamente',
  'app.error': 'Erro',
  'app.update.available': 'Nova versão disponível',
  'app.update.action': 'Recarregar',

  'nav.home': 'Início',
  'nav.epochs': 'Épocas',
  'nav.timeline': 'Linha do tempo',
  'nav.themes': 'Temas',
  'nav.glossary': 'Glossário',
  'nav.quiz': 'Quiz',
  'nav.bookmarks': 'Favoritos',
  'nav.more': 'Mais',
  'nav.search': 'Buscar',
  'nav.aria.main': 'Navegação principal',
  'nav.aria.bottom': 'Navegação',

  'lang.label': 'Idioma',
  'theme.toggle': 'Alterar esquema de cores',
  'theme.toast': 'Esquema de cores: {name}',
  'title.page': '{title} – História Mundial',

  'year.bc': '{n} a.C.',
  'year.ad': '{n} d.C.',
  'year.approx': 'c. {s}',
  'year.unknown': '?',
  'year.today': 'hoje',

  'unit.event.one': 'evento',
  'unit.event.other': 'eventos',
  'unit.person.one': 'pessoa',
  'unit.person.other': 'pessoas',
  'unit.term.one': 'termo',
  'unit.term.other': 'termos',
  'unit.theme.one': 'tema',
  'unit.theme.other': 'temas',
  'unit.epoch.one': 'época',
  'unit.epoch.other': 'épocas',
  'unit.entry.one': 'entrada',
  'unit.entry.other': 'entradas',
  'unit.hit.one': 'resultado',
  'unit.hit.other': 'resultados',
  'unit.question.one': 'pergunta',
  'unit.question.other': 'perguntas',
  'unit.region.one': 'região',
  'unit.region.other': 'regiões',
  'unit.attempt.one': 'tentativa',
  'unit.attempt.other': 'tentativas',

  'heading.events': 'Eventos',
  'heading.persons': 'Pessoas',
  'heading.terms': 'Termos',

  'century.earliest': 'Antes de 10.000 a.C.',
  'century.bc': 'Século {n} a.C.',
  'century.ad': 'Século {n}',

  'ui.milestone': 'Marco',
  'ui.bookmark.save': 'Salvar',
  'ui.bookmark.saved': 'Salvo',
  'toast.bookmark.added': 'Favorito salvo',
  'toast.bookmark.removed': 'Favorito removido',

  'home.intro': 'Todos os temas essenciais do passado, desde os primeiros humanos até os dias de hoje. Organizados por época, tema transversal e região, com linha do tempo, glossário e quiz.',
  'home.stat.quiz': 'Perguntas do quiz',
  'home.cta.epochs': 'Explorar as épocas',
  'home.cta.timeline': 'Linha do tempo',
  'home.cta.quiz': 'Começar o quiz',
  'home.install.title': 'Instalar como aplicativo',
  'home.install.ios': 'No Safari, toque em Compartilhar e depois em Adicionar à Tela de Início. Depois disso, o aplicativo também funciona offline.',
  'home.install.android': 'Instale {name} na sua tela inicial. O aplicativo também funciona offline depois disso.',
  'home.install.action': 'Instalar',
  'home.install.dismiss': 'Ocultar',
  'home.random.kicker': 'Evento aleatório',
  'home.random.more': 'Leia mais',
  'home.random.again': 'Outro evento',
  'home.progress.kicker': 'Seu progresso no quiz',
  'home.progress.title': '{done} de {total} épocas dominadas',
  'home.progress.label': 'Progresso',
  'home.progress.hint': 'Uma época é considerada dominada quando você responde corretamente a pelo menos 80% das perguntas.',
  'home.progress.link': 'Ir para o quiz',
  'home.section.epochs': 'Épocas',
  'home.section.themes': 'Temas transversais',
  'home.section.regions': 'Regiões',
  'home.section.reference': 'Referência',
  'home.showall': 'Mostrar tudo',
  'home.epochs.note': 'Em ordem cronológica, da Idade da Pedra até hoje.',
  'home.themes.note': 'Fios condutores ao longo dos milênios.',
  'home.hub.glossary.title': 'Glossário',
  'home.hub.glossary.sub': '{terms} explicados brevemente',
  'home.hub.search.title': 'Buscar',
  'home.hub.search.sub': 'Eventos, pessoas, temas, termos',
  'home.hub.bookmarks.title': 'Favoritos',
  'home.hub.bookmarks.sub': 'Os itens que você salvou',

  'epochs.title': 'Épocas',
  'epochs.intro': 'A história mundial em {count} seções, em ordem cronológica. Cada época contém uma visão geral, eventos-chave, pessoas importantes e suas consequências.',

  'epoch.notfound': 'Esta época não existe.',
  'epoch.back': 'Todas as épocas',
  'epoch.hero.position': 'Época {index} de {total}',
  'epoch.quiz.start': 'Começar o quiz',
  'epoch.quiz.best': 'Melhor pontuação {best}/{total}',
  'epoch.timeline': 'Na linha do tempo',
  'epoch.toc.title': 'Conteúdo',
  'epoch.toc.aria': 'Conteúdo desta época',
  'epoch.toc.events': 'Eventos',
  'epoch.toc.persons': 'Pessoas',
  'epoch.toc.terms': 'Termos',
  'epoch.toc.consequences': 'Consequências',
  'epoch.keyfacts.title': 'Em resumo',
  'epoch.keyfacts.milestones': 'Marcos',
  'epoch.overview.title': 'Visão geral',
  'epoch.events.title': 'Eventos-chave',
  'epoch.events.only': 'Apenas marcos ({n})',
  'epoch.persons.title': 'Pessoas importantes',
  'epoch.terms.title': 'Termos desta época',
  'epoch.terms.link': 'No glossário',
  'epoch.consequences.title': 'Consequências e importância',
  'epoch.themes.title': 'Temas transversais relacionados',
  'epoch.nav.prev': 'Época anterior',
  'epoch.nav.next': 'Próxima época',
  'epoch.nav.aria': 'Épocas vizinhas',

  'event.notfound': 'Este evento não existe.',
  'event.back': 'Época',
  'event.importance.major': 'Evento importante',
  'event.importance.label': 'Importância',
  'event.persons.title': 'Pessoas envolvidas',
  'event.terms.title': 'Termos relacionados a este evento',
  'event.themes.title': 'Temas transversais',
  'event.nearby.title': 'Na mesma época',
  'event.nav.aria': 'Vizinhos cronológicos',
  'event.nav.prev': 'Antes',
  'event.nav.next': 'Depois',

  'person.notfound': 'Esta pessoa não existe.',
  'person.back': 'Época',
  'person.events.title': 'Eventos relacionados',
  'person.terms.title': 'Termos',
  'person.themes.title': 'Temas transversais',
  'person.contemporaries.title': 'Contemporâneos',

  'bookmarks.title': 'Favoritos',
  'bookmarks.empty.title': 'Ainda não há favoritos',
  'bookmarks.empty.text': 'Toque em “{save}” em uma época, um evento ou uma pessoa para reuni-los aqui.',
  'bookmarks.count': '{entries} salvo(s). Os favoritos são armazenados apenas neste dispositivo.',

  'notfound.title': 'Não encontrado',
  'notfound.heading': 'Página não encontrada',
  'notfound.text': 'Esta página não existe.',
  'notfound.home': 'Ir para a página inicial',

  'theme.label.system': 'Automático',
  'theme.label.light': 'Claro',
  'theme.label.dark': 'Escuro',
  'theme.buttonTitle': 'Esquema de cores: {name} (clique para alterar)',

  'quiz.verdict.excellent': 'Excelente!',
  'quiz.verdict.verygood': 'Muito bom!',
  'quiz.verdict.good': 'Muito bem.',
  'quiz.verdict.keepgoing': 'Continue praticando!',

  'tile.theme.kicker': 'Tema transversal',
  'tile.theme.events': '{events} em todas as épocas',

  'timeline.title': 'Linha do tempo',
  'timeline.intro': 'Todos os eventos em ordem cronológica, agrupados por época e século. Pontos grandes marcam os marcos.',
  'timeline.filter.epoch': 'Filtrar por época',
  'timeline.filter.region': 'Filtrar por região',
  'timeline.filter.theme': 'Filtrar por tema',
  'timeline.allRegions': 'Todas as regiões',
  'timeline.allThemes': 'Todos os temas',
  'timeline.onlyMilestones': 'Apenas marcos',
  'timeline.toTop': 'Voltar ao topo',
  'timeline.empty.title': 'Nenhum evento',
  'timeline.empty.text': 'Não há entradas para esta combinação de filtros.',

  'regions.title': 'Regiões',
  'regions.intro': 'A história por continente: quais eventos e pessoas moldaram cada região do mundo?',
  'regions.notfound': 'Esta região não existe.',
  'regions.back': 'Todas as regiões',
  'regions.persons.title': 'Pessoas desta região',

  'themes.title': 'Temas transversais',
  'themes.intro': 'A história lida de forma transversal: cada tema une eventos, pessoas e termos de todas as épocas em um mesmo fio condutor – dos primórdios até os dias de hoje.',
  'themes.notfound': 'Este tema não existe.',
  'themes.back': 'Todos os temas',
  'themes.empty.title': 'Ainda não há temas',
  'themes.empty.text': 'Os temas estão sendo preparados.',
  'themes.empty.link': 'Ir para as épocas',
  'themes.intro.title': 'Introdução',
  'themes.course.title': 'Ao longo das épocas',

  'glossary.title': 'Glossário',
  'glossary.intro': '{terms} de todas as épocas, em ordem alfabética e explicados brevemente.',
  'glossary.filter': 'Filtrar termos …',
  'glossary.letters': 'Letras',
  'glossary.allEpochs': 'Todas as épocas',
  'glossary.none': 'Nenhum termo encontrado.',
  'glossary.empty.title': 'Ainda não há termos',
  'glossary.empty.text': 'O glossário está sendo preparado.',

  'search.title': 'Buscar',
  'search.placeholder': 'Evento, pessoa, época, tema ou termo …',
  'search.label': 'Termo de busca',
  'search.all': 'Todos ({n})',
  'search.hint': 'Digite pelo menos dois caracteres. Exemplos:',
  'search.resultsFor': '{results} para “{term}”',
  'search.none': 'Nenhum resultado para “{term}”.',
  'search.examples': 'Napoleão, Revolução, China, Democracia, Muro de Berlim',
  'search.tooShort': 'Digite uma palavra com pelo menos duas letras.',

  'quiz.intro': 'Teste seus conhecimentos: por época ou misturados em toda a história mundial. Sua melhor pontuação é armazenada neste dispositivo.',
  'quiz.notfound': 'Este quiz não existe.',
  'quiz.back': 'Visão geral dos quizzes',
  'quiz.mastered.label': 'Épocas dominadas (≥ 80%)',
  'quiz.mastered.value': '{done} de {total}',
  'quiz.mixed.title': 'Quiz misto',
  'quiz.mixed.sub': '{questions} de todas as épocas',
  'quiz.epoch.sub': '{shown} de {total} perguntas por rodada',
  'quiz.epochTitle': 'Quiz: {epoch}',
  'quiz.best': 'Melhor pontuação',
  'quiz.notPlayed': 'Ainda não jogado',
  'quiz.reset': 'Redefinir progresso',
  'quiz.reset.confirm': 'Realmente excluir seu progresso no quiz?',
  'quiz.noQuestions.title': 'Nenhuma pergunta',
  'quiz.noQuestions.text': 'Ainda não há perguntas para esta época.',
  'quiz.questionOf': 'Pergunta {n} de {total}',
  'quiz.difficulty.easy': 'Fácil',
  'quiz.difficulty.medium': 'Médio',
  'quiz.difficulty.hard': 'Difícil',
  'quiz.correct': 'Correto!',
  'quiz.wrong': 'Não exatamente. A resposta é: {answer}',
  'quiz.keyHint': 'Dica: responda com as teclas A–D ou 1–4, pressione Enter para continuar.',
  'quiz.next': 'Próxima',
  'quiz.finish': 'Resultados',
  'quiz.percentCorrect': '{percent}% corretas',
  'quiz.again': 'Jogar novamente',
  'quiz.other': 'Outro quiz',
  'quiz.toEpoch': 'Ir para a época',
  'quiz.review': 'Vale a pena revisar',
  'quiz.answerWas': 'Correto: {answer} –',
  'quiz.allCorrect': 'Todas as perguntas corretas – excelente!',

  'more.intro': 'Mais áreas do aplicativo, configurações e informações.',
  'more.discover': 'Descobrir',
  'more.themes.sub': '{themes} em todas as épocas',
  'more.regions.sub': 'A história por continente',
  'more.search.sub': 'Buscar em todo o conteúdo',
  'more.bookmarks.sub': '{entries} salvo(s)',
  'more.settings': 'Configurações',
  'more.theme.title': 'Esquema de cores',
  'more.theme.action': 'Alterar',
  'more.progress.title': 'Progresso do quiz',
  'more.progress.sub': 'Melhores pontuações e tentativas neste dispositivo',
  'more.progress.action': 'Redefinir',
  'more.progress.done': 'Progresso redefinido',
  'more.offline.title': 'Dados offline',
  'more.offline.sub': 'Atualizar os arquivos do aplicativo em cache',
  'more.offline.action': 'Atualizar',
  'more.offline.done': 'Cache limpo – recarregando …',
  'more.offline.noNetwork': 'Sem conexão à internet – os dados offline são mantidos.',
  'more.data.title': 'Excluir todos os dados',
  'more.data.sub': 'Favoritos, progresso do quiz e configurações neste dispositivo',
  'more.data.action': 'Excluir',
  'more.data.confirm': 'Excluir mesmo todos os favoritos, o progresso do quiz e todas as configurações neste dispositivo?',
  'more.data.done': 'Todos os dados excluídos',
  'more.about.title': 'Sobre o aplicativo',
  'more.about.text': 'é um aplicativo de aprendizado sobre os temas essenciais do passado – dos primeiros humanos até os dias de hoje, em todos os continentes.',
  'more.about.note': 'Os textos resumem o estado geralmente aceito da pesquisa e são escritos para a escola, a universidade e a educação geral. Os anos antes de Cristo são marcados com “a.C.”, as datas aproximadas com “c.”. Os favoritos e o progresso do quiz permanecem apenas neste dispositivo.',
  'more.version': 'Versão {version} · {kind} · Funciona offline',
  'more.kind.native': 'Versão do aplicativo',
  'more.kind.pwa': 'Aplicativo web progressivo',
  'more.privacy': 'Política de privacidade',
  'more.imprint': 'Aviso legal',
  'quiz.joker': 'Ajuda 50:50',
  'quiz.joker.watch': 'Ajuda 50:50 em troca de um anúncio curto',
  'quiz.joker.used': 'Duas respostas erradas foram removidas.',
  'quiz.joker.unavailable': 'Nenhum anúncio disponível no momento. Tente novamente mais tarde.',
  'quiz.joker.loading': 'Carregando anúncio …',
  'more.ads.title': 'Anúncios e privacidade',
  'more.ads.sub': 'Alterar seu consentimento para anúncios personalizados',
  'more.ads.action': 'Alterar',
  'ads.label': 'Anúncio',
};
