// Русские тексты интерфейса.
export default {
  'app.name': 'Всемирная история',
  'app.description': 'Всемирная история от доисторической эпохи до наших дней: эпохи, сквозные темы, лента времени, глоссарий, викторина, поиск и закладки. Работает офлайн.',
  'app.skipToContent': 'Перейти к содержимому',
  'app.brandAria': 'Всемирная история – главная',
  'app.install': 'Установить приложение',
  'app.installed': 'Приложение установлено',
  'app.loading': 'Загрузка содержимого …',
  'app.loadFailed': 'Не удалось загрузить содержимое',
  'app.retry': 'Повторить попытку',
  'app.error': 'Ошибка',
  'app.update.available': 'Доступна новая версия',
  'app.update.action': 'Обновить',

  'nav.home': 'Главная',
  'nav.epochs': 'Эпохи',
  'nav.timeline': 'Лента времени',
  'nav.themes': 'Темы',
  'nav.glossary': 'Глоссарий',
  'nav.quiz': 'Викторина',
  'nav.bookmarks': 'Закладки',
  'nav.more': 'Ещё',
  'nav.search': 'Поиск',
  'nav.aria.main': 'Основная навигация',
  'nav.aria.bottom': 'Навигация',

  'lang.label': 'Язык',
  'theme.toggle': 'Сменить цветовую тему',
  'theme.toast': 'Цветовая тема: {name}',
  'title.page': '{title} – Всемирная история',

  'year.bc': '{n} до н. э.',
  'year.ad': '{n} н. э.',
  'year.approx': 'ок. {s}',
  'year.unknown': '?',
  'year.today': 'сегодня',

  'unit.event.one': 'событие',
  'unit.event.other': 'события',
  'unit.event.few': 'события',
  'unit.event.many': 'событий',
  'unit.person.one': 'человек',
  'unit.person.other': 'человека',
  'unit.person.few': 'человека',
  'unit.person.many': 'человек',
  'unit.term.one': 'термин',
  'unit.term.other': 'термина',
  'unit.term.few': 'термина',
  'unit.term.many': 'терминов',
  'unit.theme.one': 'тема',
  'unit.theme.other': 'темы',
  'unit.theme.few': 'темы',
  'unit.theme.many': 'тем',
  'unit.epoch.one': 'эпоха',
  'unit.epoch.other': 'эпохи',
  'unit.epoch.few': 'эпохи',
  'unit.epoch.many': 'эпох',
  'unit.entry.one': 'запись',
  'unit.entry.other': 'записи',
  'unit.entry.few': 'записи',
  'unit.entry.many': 'записей',
  'unit.hit.one': 'результат',
  'unit.hit.other': 'результата',
  'unit.hit.few': 'результата',
  'unit.hit.many': 'результатов',
  'unit.question.one': 'вопрос',
  'unit.question.other': 'вопроса',
  'unit.question.few': 'вопроса',
  'unit.question.many': 'вопросов',
  'unit.region.one': 'регион',
  'unit.region.other': 'региона',
  'unit.region.few': 'региона',
  'unit.region.many': 'регионов',
  'unit.attempt.one': 'попытка',
  'unit.attempt.other': 'попытки',
  'unit.attempt.few': 'попытки',
  'unit.attempt.many': 'попыток',

  'heading.events': 'События',
  'heading.persons': 'Люди',
  'heading.terms': 'Термины',

  'century.earliest': 'До 10 000 г. до н. э.',
  'century.bc': '{n} век до н. э.',
  'century.ad': '{n} век',

  'ui.milestone': 'Веха',
  'ui.bookmark.save': 'Сохранить',
  'ui.bookmark.saved': 'Сохранено',
  'toast.bookmark.added': 'Закладка сохранена',
  'toast.bookmark.removed': 'Закладка удалена',

  'home.intro': 'Все важнейшие темы прошлого – от первых людей до наших дней. Систематизировано по эпохам, сквозным темам и регионам, с лентой времени, глоссарием и викториной.',
  'home.stat.quiz': 'Вопросы викторины',
  'home.cta.epochs': 'Изучить эпохи',
  'home.cta.timeline': 'Лента времени',
  'home.cta.quiz': 'Начать викторину',
  'home.install.title': 'Установить как приложение',
  'home.install.ios': 'В Safari нажмите «Поделиться», затем «На экран «Домой»». После этого приложение будет работать и офлайн.',
  'home.install.android': 'Установите {name} на главный экран. После этого приложение будет работать и офлайн.',
  'home.install.action': 'Установить',
  'home.install.dismiss': 'Скрыть',
  'home.random.kicker': 'Случайное событие',
  'home.random.more': 'Читать далее',
  'home.random.again': 'Другое событие',
  'home.progress.kicker': 'Ваш прогресс в викторине',
  'home.progress.title': 'Освоено {done} из {total} эпох',
  'home.progress.label': 'Прогресс',
  'home.progress.hint': 'Эпоха считается освоенной, если вы правильно ответили минимум на 80 процентов вопросов.',
  'home.progress.link': 'Перейти к викторине',
  'home.section.epochs': 'Эпохи',
  'home.section.themes': 'Сквозные темы',
  'home.section.regions': 'Регионы',
  'home.section.reference': 'Справочник',
  'home.showall': 'Показать всё',
  'home.epochs.note': 'В хронологическом порядке, от каменного века до наших дней.',
  'home.themes.note': 'Нити, проходящие через тысячелетия.',
  'home.hub.glossary.title': 'Глоссарий',
  'home.hub.glossary.sub': '{terms} с кратким объяснением',
  'home.hub.search.title': 'Поиск',
  'home.hub.search.sub': 'События, люди, темы, термины',
  'home.hub.bookmarks.title': 'Закладки',
  'home.hub.bookmarks.sub': 'Сохранённые вами материалы',

  'epochs.title': 'Эпохи',
  'epochs.intro': 'Всемирная история в {count} разделах, в хронологическом порядке. Каждая эпоха содержит обзор, ключевые события, важных людей и их последствия.',

  'epoch.notfound': 'Такой эпохи не существует.',
  'epoch.back': 'Все эпохи',
  'epoch.hero.position': 'Эпоха {index} из {total}',
  'epoch.quiz.start': 'Начать викторину',
  'epoch.quiz.best': 'Лучший результат {best}/{total}',
  'epoch.timeline': 'На ленте времени',
  'epoch.toc.title': 'Содержание',
  'epoch.toc.aria': 'Содержание этой эпохи',
  'epoch.toc.events': 'События',
  'epoch.toc.persons': 'Люди',
  'epoch.toc.terms': 'Термины',
  'epoch.toc.consequences': 'Последствия',
  'epoch.keyfacts.title': 'Коротко',
  'epoch.keyfacts.milestones': 'Вехи',
  'epoch.overview.title': 'Обзор',
  'epoch.events.title': 'Ключевые события',
  'epoch.events.only': 'Только вехи ({n})',
  'epoch.persons.title': 'Важные личности',
  'epoch.terms.title': 'Термины этой эпохи',
  'epoch.terms.link': 'В глоссарии',
  'epoch.consequences.title': 'Последствия и значение',
  'epoch.themes.title': 'Связанные сквозные темы',
  'epoch.nav.prev': 'Предыдущая эпоха',
  'epoch.nav.next': 'Следующая эпоха',
  'epoch.nav.aria': 'Соседние эпохи',

  'event.notfound': 'Такого события не существует.',
  'event.back': 'Эпоха',
  'event.importance.major': 'Значимое событие',
  'event.importance.label': 'Значение',
  'event.persons.title': 'Причастные лица',
  'event.terms.title': 'Термины по этому событию',
  'event.themes.title': 'Сквозные темы',
  'event.nearby.title': 'В то же время в этой эпохе',
  'event.nav.aria': 'Хронологические соседи',
  'event.nav.prev': 'До',
  'event.nav.next': 'После',

  'person.notfound': 'Такого человека не существует.',
  'person.back': 'Эпоха',
  'person.events.title': 'Связанные события',
  'person.terms.title': 'Термины',
  'person.themes.title': 'Сквозные темы',
  'person.contemporaries.title': 'Современники',

  'bookmarks.title': 'Закладки',
  'bookmarks.empty.title': 'Закладок пока нет',
  'bookmarks.empty.text': 'Нажмите «{save}» у эпохи, события или человека, чтобы собрать их здесь.',
  'bookmarks.count': 'Сохранено: {entries}. Закладки хранятся только на этом устройстве.',

  'notfound.title': 'Не найдено',
  'notfound.heading': 'Страница не найдена',
  'notfound.text': 'Такой страницы не существует.',
  'notfound.home': 'На главную страницу',

  'theme.label.system': 'Автоматически',
  'theme.label.light': 'Светлая',
  'theme.label.dark': 'Тёмная',
  'theme.buttonTitle': 'Цветовая тема: {name} (нажмите, чтобы сменить)',

  'quiz.verdict.excellent': 'Отлично!',
  'quiz.verdict.verygood': 'Очень хорошо!',
  'quiz.verdict.good': 'Хорошая работа.',
  'quiz.verdict.keepgoing': 'Продолжайте тренироваться!',

  'tile.theme.kicker': 'Сквозная тема',
  'tile.theme.events': '{events} во всех эпохах',

  'timeline.title': 'Лента времени',
  'timeline.intro': 'Все события в хронологическом порядке, сгруппированные по эпохам и векам. Крупные точки отмечают вехи.',
  'timeline.filter.epoch': 'Фильтр по эпохе',
  'timeline.filter.region': 'Фильтр по региону',
  'timeline.filter.theme': 'Фильтр по теме',
  'timeline.allRegions': 'Все регионы',
  'timeline.allThemes': 'Все темы',
  'timeline.onlyMilestones': 'Только вехи',
  'timeline.toTop': 'Наверх',
  'timeline.empty.title': 'Нет событий',
  'timeline.empty.text': 'Для этой комбинации фильтров нет записей.',

  'regions.title': 'Регионы',
  'regions.intro': 'История по континентам: какие события и люди сформировали каждый регион мира?',
  'regions.notfound': 'Такого региона не существует.',
  'regions.back': 'Все регионы',
  'regions.persons.title': 'Люди из этого региона',

  'themes.title': 'Сквозные темы',
  'themes.intro': 'История сквозь века: каждая тема связывает события, людей и термины из всех эпох в единую нить – от истоков до наших дней.',
  'themes.notfound': 'Такой темы не существует.',
  'themes.back': 'Все темы',
  'themes.empty.title': 'Тем пока нет',
  'themes.empty.text': 'Темы находятся в разработке.',
  'themes.empty.link': 'К эпохам',
  'themes.intro.title': 'Введение',
  'themes.course.title': 'Через эпохи',

  'glossary.title': 'Глоссарий',
  'glossary.intro': '{terms} из всех эпох, в алфавитном порядке и с кратким объяснением.',
  'glossary.filter': 'Фильтр терминов …',
  'glossary.letters': 'Буквы',
  'glossary.allEpochs': 'Все эпохи',
  'glossary.none': 'Термины не найдены.',
  'glossary.empty.title': 'Терминов пока нет',
  'glossary.empty.text': 'Глоссарий находится в разработке.',

  'search.title': 'Поиск',
  'search.placeholder': 'Событие, человек, эпоха, тема или термин …',
  'search.label': 'Поисковый запрос',
  'search.all': 'Все ({n})',
  'search.hint': 'Введите не менее двух символов. Примеры:',
  'search.resultsFor': '{results} по запросу «{term}»',
  'search.none': 'Нет результатов по запросу «{term}».',
  'search.examples': 'Наполеон, Революция, Китай, Демократия, Берлинская стена',
  'search.tooShort': 'Пожалуйста, введите слово не менее чем из двух букв.',

  'quiz.intro': 'Проверьте свои знания: по одной эпохе или вперемешку по всей всемирной истории. Ваш лучший результат сохраняется на этом устройстве.',
  'quiz.notfound': 'Такой викторины не существует.',
  'quiz.back': 'Обзор викторин',
  'quiz.mastered.label': 'Освоенные эпохи (≥ 80%)',
  'quiz.mastered.value': '{done} из {total}',
  'quiz.mixed.title': 'Смешанная викторина',
  'quiz.mixed.sub': '{questions} из всех эпох',
  'quiz.epoch.sub': '{shown} из {total} вопросов за раунд',
  'quiz.epochTitle': 'Викторина: {epoch}',
  'quiz.best': 'Лучший результат',
  'quiz.notPlayed': 'Ещё не пройдено',
  'quiz.reset': 'Сбросить прогресс',
  'quiz.reset.confirm': 'Действительно удалить прогресс викторины?',
  'quiz.noQuestions.title': 'Нет вопросов',
  'quiz.noQuestions.text': 'Для этой эпохи пока нет вопросов.',
  'quiz.questionOf': 'Вопрос {n} из {total}',
  'quiz.difficulty.easy': 'Лёгкий',
  'quiz.difficulty.medium': 'Средний',
  'quiz.difficulty.hard': 'Сложный',
  'quiz.correct': 'Правильно!',
  'quiz.wrong': 'Не совсем. Правильный ответ: {answer}',
  'quiz.keyHint': 'Совет: отвечайте клавишами A–D или 1–4, нажмите Enter, чтобы продолжить.',
  'quiz.next': 'Далее',
  'quiz.finish': 'Результаты',
  'quiz.percentCorrect': '{percent}% правильных ответов',
  'quiz.again': 'Сыграть ещё раз',
  'quiz.other': 'Другая викторина',
  'quiz.toEpoch': 'Перейти к эпохе',
  'quiz.review': 'Стоит перечитать',
  'quiz.answerWas': 'Правильно: {answer} –',
  'quiz.allCorrect': 'Все ответы верны – отлично!',

  'more.intro': 'Другие разделы приложения, настройки и информация.',
  'more.discover': 'Обзор',
  'more.themes.sub': '{themes} по всем эпохам',
  'more.regions.sub': 'История по континентам',
  'more.search.sub': 'Поиск по всему содержимому',
  'more.bookmarks.sub': 'Сохранено: {entries}',
  'more.settings': 'Настройки',
  'more.theme.title': 'Цветовая тема',
  'more.theme.action': 'Сменить',
  'more.progress.title': 'Прогресс викторины',
  'more.progress.sub': 'Лучшие результаты и попытки на этом устройстве',
  'more.progress.action': 'Сбросить',
  'more.progress.done': 'Прогресс сброшен',
  'more.offline.title': 'Офлайн-данные',
  'more.offline.sub': 'Обновить кэшированные файлы приложения',
  'more.offline.action': 'Обновить',
  'more.offline.done': 'Кэш очищен – перезагрузка …',
  'more.offline.noNetwork': 'Нет подключения к интернету – офлайн-данные сохранены.',
  'more.data.title': 'Удалить все данные',
  'more.data.sub': 'Закладки, прогресс викторины и настройки на этом устройстве',
  'more.data.action': 'Удалить',
  'more.data.confirm': 'Действительно удалить все закладки, прогресс викторины и настройки на этом устройстве?',
  'more.data.done': 'Все данные удалены',
  'more.about.title': 'О приложении',
  'more.about.text': '– это обучающее приложение об основных темах прошлого – от первых людей до наших дней, на всех континентах.',
  'more.about.note': 'Тексты обобщают общепризнанное состояние исследований и написаны для школы, вуза и общего образования. Годы до нашей эры обозначаются «до н. э.», приблизительные даты – «ок.». Закладки и прогресс викторины хранятся только на этом устройстве.',
  'more.version': 'Версия {version} · {kind} · Работает офлайн',
  'more.kind.native': 'Версия приложения',
  'more.kind.pwa': 'Прогрессивное веб-приложение',
  'more.privacy': 'Политика конфиденциальности',
  'more.imprint': 'Юридическая информация',
  'quiz.joker': 'Джокер 50:50',
  'quiz.joker.watch': 'Джокер 50:50 за короткую рекламу',
  'quiz.joker.used': 'Удалены два неправильных ответа.',
  'quiz.joker.unavailable': 'Сейчас реклама недоступна. Повторите попытку позже.',
  'quiz.joker.loading': 'Загрузка рекламы …',
  'more.ads.title': 'Реклама и конфиденциальность',
  'more.ads.sub': 'Изменить согласие на персонализированную рекламу',
  'more.ads.action': 'Изменить',
  'ads.label': 'Реклама',
};
