// Türkçe arayüz metinleri.
export default {
  'app.name': 'Dünya Tarihi',
  'app.description': 'Tarih öncesinden günümüze dünya tarihi: çağlar, ortak temalar, zaman çizelgesi, sözlük, quiz, arama ve yer imleri. Çevrimdışı çalışır.',
  'app.skipToContent': 'İçeriğe geç',
  'app.brandAria': 'Dünya Tarihi – ana sayfa',
  'app.install': 'Uygulamayı yükle',
  'app.installed': 'Uygulama yüklendi',
  'app.loading': 'İçerik yükleniyor …',
  'app.loadFailed': 'İçerik yüklenemedi',
  'app.retry': 'Tekrar dene',
  'app.error': 'Hata',
  'app.update.available': 'Yeni sürüm mevcut',
  'app.update.action': 'Yeniden yükle',

  'nav.home': 'Ana sayfa',
  'nav.epochs': 'Çağlar',
  'nav.timeline': 'Zaman çizelgesi',
  'nav.themes': 'Temalar',
  'nav.glossary': 'Sözlük',
  'nav.quiz': 'Quiz',
  'nav.bookmarks': 'Yer imleri',
  'nav.more': 'Daha fazla',
  'nav.search': 'Ara',
  'nav.aria.main': 'Ana gezinme',
  'nav.aria.bottom': 'Gezinme',

  'lang.label': 'Dil',
  'theme.toggle': 'Renk şemasını değiştir',
  'theme.toast': 'Renk şeması: {name}',
  'title.page': '{title} – Dünya Tarihi',

  'year.bc': 'MÖ {n}',
  'year.ad': 'MS {n}',
  'year.approx': 'yakl. {s}',
  'year.unknown': '?',
  'year.today': 'bugün',

  'unit.event.one': 'olay',
  'unit.event.other': 'olay',
  'unit.person.one': 'kişi',
  'unit.person.other': 'kişi',
  'unit.term.one': 'terim',
  'unit.term.other': 'terim',
  'unit.theme.one': 'tema',
  'unit.theme.other': 'tema',
  'unit.epoch.one': 'çağ',
  'unit.epoch.other': 'çağ',
  'unit.entry.one': 'kayıt',
  'unit.entry.other': 'kayıt',
  'unit.hit.one': 'sonuç',
  'unit.hit.other': 'sonuç',
  'unit.question.one': 'soru',
  'unit.question.other': 'soru',
  'unit.region.one': 'bölge',
  'unit.region.other': 'bölge',
  'unit.attempt.one': 'deneme',
  'unit.attempt.other': 'deneme',

  'heading.events': 'Olaylar',
  'heading.persons': 'Kişiler',
  'heading.terms': 'Terimler',

  'century.earliest': 'MÖ 10.000\'den önce',
  'century.bc': 'MÖ {n} yüzyıl',
  'century.ad': '{n} yüzyıl',

  'ui.milestone': 'Kilometre taşı',
  'ui.bookmark.save': 'Kaydet',
  'ui.bookmark.saved': 'Kaydedildi',
  'toast.bookmark.added': 'Yer imi kaydedildi',
  'toast.bookmark.removed': 'Yer imi kaldırıldı',

  'home.intro': 'Geçmişin tüm önemli konuları, ilk insanlardan günümüze. Çağlara, ortak temalara ve bölgelere göre düzenlenmiş; zaman çizelgesi, sözlük ve quiz ile.',
  'home.stat.quiz': 'Quiz soruları',
  'home.cta.epochs': 'Çağları keşfet',
  'home.cta.timeline': 'Zaman çizelgesi',
  'home.cta.quiz': 'Quiz\'i başlat',
  'home.install.title': 'Uygulama olarak yükle',
  'home.install.ios': 'Safari\'de Paylaş\'a, ardından Ana Ekrana Ekle\'ye dokun. Bundan sonra uygulama çevrimdışı da çalışır.',
  'home.install.android': '{name} uygulamasını ana ekranınıza yükleyin. Uygulama böylece çevrimdışı da çalışır.',
  'home.install.action': 'Yükle',
  'home.install.dismiss': 'Gizle',
  'home.random.kicker': 'Rastgele olay',
  'home.random.more': 'Devamını oku',
  'home.random.again': 'Başka bir olay',
  'home.progress.kicker': 'Quiz ilerlemen',
  'home.progress.title': '{total} çağdan {done} tanesi tamamlandı',
  'home.progress.label': 'İlerleme',
  'home.progress.hint': 'Bir çağ, soruların en az yüzde 80\'ini doğru yanıtladığında tamamlanmış sayılır.',
  'home.progress.link': 'Quiz\'e git',
  'home.section.epochs': 'Çağlar',
  'home.section.themes': 'Ortak temalar',
  'home.section.regions': 'Bölgeler',
  'home.section.reference': 'Başvuru',
  'home.showall': 'Tümünü göster',
  'home.epochs.note': 'Kronolojik sırayla, Taş Devri\'nden günümüze.',
  'home.themes.note': 'Binyıllar boyunca uzanan ortak ipuçları.',
  'home.hub.glossary.title': 'Sözlük',
  'home.hub.glossary.sub': '{terms} kısaca açıklandı',
  'home.hub.search.title': 'Ara',
  'home.hub.search.sub': 'Olaylar, kişiler, temalar, terimler',
  'home.hub.bookmarks.title': 'Yer imleri',
  'home.hub.bookmarks.sub': 'Kaydettiğin öğeler',

  'epochs.title': 'Çağlar',
  'epochs.intro': 'Dünya tarihi {count} bölümde, kronolojik sırayla. Her çağ; genel bir bakış, önemli olaylar, önemli kişiler ve sonuçlarını içerir.',

  'epoch.notfound': 'Bu çağ mevcut değil.',
  'epoch.back': 'Tüm çağlar',
  'epoch.hero.position': '{total} çağdan {index}.',
  'epoch.quiz.start': 'Quiz\'i başlat',
  'epoch.quiz.best': 'En iyi skor {best}/{total}',
  'epoch.timeline': 'Zaman çizelgesinde',
  'epoch.toc.title': 'İçindekiler',
  'epoch.toc.aria': 'Bu çağın içindekiler listesi',
  'epoch.toc.events': 'Olaylar',
  'epoch.toc.persons': 'Kişiler',
  'epoch.toc.terms': 'Terimler',
  'epoch.toc.consequences': 'Sonuçlar',
  'epoch.keyfacts.title': 'Bir bakışta',
  'epoch.keyfacts.milestones': 'Kilometre taşları',
  'epoch.overview.title': 'Genel bakış',
  'epoch.events.title': 'Önemli olaylar',
  'epoch.events.only': 'Yalnızca kilometre taşları ({n})',
  'epoch.persons.title': 'Önemli kişiler',
  'epoch.terms.title': 'Bu çağın terimleri',
  'epoch.terms.link': 'Sözlükte',
  'epoch.consequences.title': 'Sonuçlar ve önemi',
  'epoch.themes.title': 'İlgili ortak temalar',
  'epoch.nav.prev': 'Önceki çağ',
  'epoch.nav.next': 'Sonraki çağ',
  'epoch.nav.aria': 'Komşu çağlar',

  'event.notfound': 'Bu olay mevcut değil.',
  'event.back': 'Çağ',
  'event.importance.major': 'Önemli olay',
  'event.importance.label': 'Önem',
  'event.persons.title': 'İlgili kişiler',
  'event.terms.title': 'Bu olayla ilgili terimler',
  'event.themes.title': 'Ortak temalar',
  'event.nearby.title': 'Bu çağda aynı dönemde',
  'event.nav.aria': 'Kronolojik komşular',
  'event.nav.prev': 'Önce',
  'event.nav.next': 'Sonra',

  'person.notfound': 'Bu kişi mevcut değil.',
  'person.back': 'Çağ',
  'person.events.title': 'İlgili olaylar',
  'person.terms.title': 'Terimler',
  'person.themes.title': 'Ortak temalar',
  'person.contemporaries.title': 'Çağdaşları',

  'bookmarks.title': 'Yer imleri',
  'bookmarks.empty.title': 'Henüz yer imi yok',
  'bookmarks.empty.text': 'Bir çağda, olayda veya kişide "{save}" öğesine dokunarak onları burada topla.',
  'bookmarks.count': '{entries} kaydedildi. Yer imleri yalnızca bu cihazda saklanır.',

  'notfound.title': 'Bulunamadı',
  'notfound.heading': 'Sayfa bulunamadı',
  'notfound.text': 'Bu sayfa mevcut değil.',
  'notfound.home': 'Ana sayfaya git',

  'theme.label.system': 'Otomatik',
  'theme.label.light': 'Açık',
  'theme.label.dark': 'Koyu',
  'theme.buttonTitle': 'Renk şeması: {name} (değiştirmek için tıkla)',

  'quiz.verdict.excellent': 'Mükemmel!',
  'quiz.verdict.verygood': 'Çok iyi!',
  'quiz.verdict.good': 'Aferin.',
  'quiz.verdict.keepgoing': 'Pratik yapmaya devam et!',

  'tile.theme.kicker': 'Ortak tema',
  'tile.theme.events': 'Tüm çağlarda {events}',

  'timeline.title': 'Zaman çizelgesi',
  'timeline.intro': 'Tüm olaylar kronolojik sırayla, çağa ve yüzyıla göre gruplandırılmış. Büyük noktalar kilometre taşlarını işaret eder.',
  'timeline.filter.epoch': 'Çağa göre filtrele',
  'timeline.filter.region': 'Bölgeye göre filtrele',
  'timeline.filter.theme': 'Temaya göre filtrele',
  'timeline.allRegions': 'Tüm bölgeler',
  'timeline.allThemes': 'Tüm temalar',
  'timeline.onlyMilestones': 'Yalnızca kilometre taşları',
  'timeline.toTop': 'Başa dön',
  'timeline.empty.title': 'Olay yok',
  'timeline.empty.text': 'Bu filtre kombinasyonu için kayıt yok.',

  'regions.title': 'Bölgeler',
  'regions.intro': 'Kıtalara göre tarih: dünyanın her bölgesini hangi olaylar ve kişiler şekillendirdi?',
  'regions.notfound': 'Bu bölge mevcut değil.',
  'regions.back': 'Tüm bölgeler',
  'regions.persons.title': 'Bu bölgeden kişiler',

  'themes.title': 'Ortak temalar',
  'themes.intro': 'Çağlar boyunca okunan tarih: her tema, her çağdan olayları, kişileri ve terimleri tek bir çizgide birleştirir – başlangıçtan günümüze.',
  'themes.notfound': 'Bu tema mevcut değil.',
  'themes.back': 'Tüm temalar',
  'themes.empty.title': 'Henüz tema yok',
  'themes.empty.text': 'Temalar hazırlanıyor.',
  'themes.empty.link': 'Çağlara git',
  'themes.intro.title': 'Giriş',
  'themes.course.title': 'Çağlar boyunca',

  'glossary.title': 'Sözlük',
  'glossary.intro': 'Her çağdan {terms}, alfabetik sırayla ve kısaca açıklanmış.',
  'glossary.filter': 'Terim filtrele …',
  'glossary.letters': 'Harfler',
  'glossary.allEpochs': 'Tüm çağlar',
  'glossary.none': 'Terim bulunamadı.',
  'glossary.empty.title': 'Henüz terim yok',
  'glossary.empty.text': 'Sözlük hazırlanıyor.',

  'search.title': 'Ara',
  'search.placeholder': 'Olay, kişi, çağ, tema veya terim …',
  'search.label': 'Arama terimi',
  'search.all': 'Tümü ({n})',
  'search.hint': 'En az iki karakter girin. Örnekler:',
  'search.resultsFor': '"{term}" için {results}',
  'search.none': '"{term}" için sonuç yok.',
  'search.examples': 'Napolyon, Devrim, Çin, Demokrasi, Berlin Duvarı',
  'search.tooShort': 'Lütfen en az iki harften oluşan bir kelime girin.',

  'quiz.intro': 'Bilgini test et: çağ çağ ya da tüm dünya tarihinden karışık sorularla. En iyi skorun bu cihazda saklanır.',
  'quiz.notfound': 'Bu quiz mevcut değil.',
  'quiz.back': 'Quiz genel bakış',
  'quiz.mastered.label': 'Tamamlanan çağlar (≥ %80)',
  'quiz.mastered.value': '{total} çağdan {done}',
  'quiz.mixed.title': 'Karışık quiz',
  'quiz.mixed.sub': 'Tüm çağlardan {questions}',
  'quiz.epoch.sub': 'Tur başına {total} sorudan {shown}',
  'quiz.epochTitle': 'Quiz: {epoch}',
  'quiz.best': 'En iyi skor',
  'quiz.notPlayed': 'Henüz oynanmadı',
  'quiz.reset': 'İlerlemeyi sıfırla',
  'quiz.reset.confirm': 'Quiz ilerlemeni gerçekten silmek istiyor musun?',
  'quiz.noQuestions.title': 'Soru yok',
  'quiz.noQuestions.text': 'Bu çağ için henüz soru yok.',
  'quiz.questionOf': '{total} sorudan {n}.',
  'quiz.difficulty.easy': 'Kolay',
  'quiz.difficulty.medium': 'Orta',
  'quiz.difficulty.hard': 'Zor',
  'quiz.correct': 'Doğru!',
  'quiz.wrong': 'Maalesef yanlış. Doğru cevap: {answer}',
  'quiz.keyHint': 'İpucu: A–D veya 1–4 tuşlarıyla yanıtla, devam etmek için Enter\'a bas.',
  'quiz.next': 'İleri',
  'quiz.finish': 'Sonuçlar',
  'quiz.percentCorrect': '%{percent} doğru',
  'quiz.again': 'Tekrar oyna',
  'quiz.other': 'Başka bir quiz',
  'quiz.toEpoch': 'Çağa git',
  'quiz.review': 'Tekrar bakmaya değer',
  'quiz.answerWas': 'Doğru cevap: {answer} –',
  'quiz.allCorrect': 'Tüm sorular doğru – mükemmel!',

  'more.intro': 'Uygulamanın diğer bölümleri, ayarlar ve bilgiler.',
  'more.discover': 'Keşfet',
  'more.themes.sub': 'Tüm çağlarda {themes}',
  'more.regions.sub': 'Kıtalara göre tarih',
  'more.search.sub': 'Tüm içerikte ara',
  'more.bookmarks.sub': '{entries} kaydedildi',
  'more.settings': 'Ayarlar',
  'more.theme.title': 'Renk şeması',
  'more.theme.action': 'Değiştir',
  'more.progress.title': 'Quiz ilerlemesi',
  'more.progress.sub': 'Bu cihazdaki en iyi skorlar ve denemeler',
  'more.progress.action': 'Sıfırla',
  'more.progress.done': 'İlerleme sıfırlandı',
  'more.offline.title': 'Çevrimdışı veriler',
  'more.offline.sub': 'Önbelleğe alınan uygulama dosyalarını yenile',
  'more.offline.action': 'Yenile',
  'more.offline.done': 'Önbellek temizlendi – yeniden yükleniyor …',
  'more.offline.noNetwork': 'İnternet bağlantısı yok – çevrimdışı veriler korunuyor.',
  'more.data.title': 'Tüm verileri sil',
  'more.data.sub': 'Bu cihazdaki yer imleri, quiz ilerlemesi ve ayarlar',
  'more.data.action': 'Sil',
  'more.data.confirm': 'Bu cihazdaki tüm yer imlerini, quiz ilerlemesini ve ayarları gerçekten silmek istiyor musun?',
  'more.data.done': 'Tüm veriler silindi',
  'more.about.title': 'Uygulama hakkında',
  'more.about.text': 'geçmişin temel konuları için bir öğrenme uygulamasıdır – ilk insanlardan günümüze, her kıtada.',
  'more.about.note': 'Metinler, genel kabul gören araştırma durumunu özetler ve okul, üniversite ve genel eğitim için yazılmıştır. Milattan önceki yıllar "MÖ" ile, yaklaşık tarihler "yakl." ile işaretlenir. Yer imleri ve quiz ilerlemesi yalnızca bu cihazda kalır.',
  'more.version': 'Sürüm {version} · {kind} · Çevrimdışı çalışır',
  'more.kind.native': 'Uygulama sürümü',
  'more.kind.pwa': 'Progressive Web App',
  'more.privacy': 'Gizlilik politikası',
  'more.imprint': 'Yasal bilgiler',
  'quiz.joker': '50:50 joker',
  'quiz.joker.watch': 'Kısa bir reklam karşılığında 50:50 joker',
  'quiz.joker.used': 'İki yanlış cevap kaldırıldı.',
  'quiz.joker.unavailable': 'Şu anda kullanılabilir reklam yok. Lütfen daha sonra tekrar dene.',
  'quiz.joker.loading': 'Reklam yükleniyor …',
  'more.ads.title': 'Reklamlar ve gizlilik',
  'more.ads.sub': 'Kişiselleştirilmiş reklamlar için onayını değiştir',
  'more.ads.action': 'Değiştir',
  'ads.label': 'Reklam',
};
