// Тексти інтерфейсу українською.
export default {
  'app.name': 'Всесвітня історія',
  'app.description': 'Всесвітня історія від первісних часів до сучасності: епохи, наскрізні теми, хронологічна шкала, глосарій, вікторина, пошук і закладки. Працює офлайн.',
  'app.skipToContent': 'Перейти до змісту',
  'app.brandAria': 'Всесвітня історія – головна сторінка',
  'app.install': 'Встановити застосунок',
  'app.installed': 'Застосунок встановлено',
  'app.loading': 'Завантаження вмісту …',
  'app.loadFailed': 'Не вдалося завантажити вміст',
  'app.retry': 'Спробувати ще раз',
  'app.error': 'Помилка',
  'app.update.available': 'Доступна нова версія',
  'app.update.action': 'Оновити',

  'nav.home': 'Головна',
  'nav.epochs': 'Епохи',
  'nav.timeline': 'Хронологія',
  'nav.themes': 'Теми',
  'nav.glossary': 'Глосарій',
  'nav.quiz': 'Вікторина',
  'nav.bookmarks': 'Закладки',
  'nav.more': 'Більше',
  'nav.search': 'Пошук',
  'nav.aria.main': 'Основна навігація',
  'nav.aria.bottom': 'Навігація',

  'lang.label': 'Мова',
  'theme.toggle': 'Змінити колірну схему',
  'theme.toast': 'Колірна схема: {name}',
  'title.page': '{title} – Всесвітня історія',

  'year.bc': '{n} до н. е.',
  'year.ad': '{n} н. е.',
  'year.approx': 'бл. {s}',
  'year.unknown': '?',
  'year.today': 'сьогодні',

  'unit.event.one': 'подія',
  'unit.event.few': 'події',
  'unit.event.many': 'подій',
  'unit.event.other': 'події',
  'unit.person.one': 'особа',
  'unit.person.few': 'особи',
  'unit.person.many': 'осіб',
  'unit.person.other': 'особи',
  'unit.term.one': 'термін',
  'unit.term.few': 'терміни',
  'unit.term.many': 'термінів',
  'unit.term.other': 'терміна',
  'unit.theme.one': 'тема',
  'unit.theme.few': 'теми',
  'unit.theme.many': 'тем',
  'unit.theme.other': 'теми',
  'unit.epoch.one': 'епоха',
  'unit.epoch.few': 'епохи',
  'unit.epoch.many': 'епох',
  'unit.epoch.other': 'епохи',
  'unit.entry.one': 'запис',
  'unit.entry.few': 'записи',
  'unit.entry.many': 'записів',
  'unit.entry.other': 'запису',
  'unit.hit.one': 'результат',
  'unit.hit.few': 'результати',
  'unit.hit.many': 'результатів',
  'unit.hit.other': 'результату',
  'unit.question.one': 'питання',
  'unit.question.few': 'питання',
  'unit.question.many': 'питань',
  'unit.question.other': 'питання',
  'unit.region.one': 'регіон',
  'unit.region.few': 'регіони',
  'unit.region.many': 'регіонів',
  'unit.region.other': 'регіону',
  'unit.attempt.one': 'спроба',
  'unit.attempt.few': 'спроби',
  'unit.attempt.many': 'спроб',
  'unit.attempt.other': 'спроби',

  'heading.events': 'Події',
  'heading.persons': 'Особи',
  'heading.terms': 'Терміни',

  'century.earliest': 'До 10 000 року до н. е.',
  'century.bc': '{n} століття до н. е.',
  'century.ad': '{n} століття',

  'ui.milestone': 'Віха',
  'ui.bookmark.save': 'Зберегти',
  'ui.bookmark.saved': 'Збережено',
  'toast.bookmark.added': 'Закладку збережено',
  'toast.bookmark.removed': 'Закладку видалено',

  'home.intro': 'Усі найважливіші теми минулого – від перших людей до сьогодення. Впорядковано за епохами, наскрізними темами та регіонами, з хронологічною шкалою, глосарієм і вікториною.',
  'home.stat.quiz': 'Питання вікторини',
  'home.cta.epochs': 'Дослідити епохи',
  'home.cta.timeline': 'Хронологічна шкала',
  'home.cta.quiz': 'Почати вікторину',
  'home.install.title': 'Встановити як застосунок',
  'home.install.ios': 'У Safari натисніть «Поділитися», а потім «На екран «Домівка»». Після цього застосунок працюватиме й офлайн.',
  'home.install.android': 'Встановіть {name} на головний екран. Тоді застосунок працюватиме й офлайн.',
  'home.install.action': 'Встановити',
  'home.install.dismiss': 'Приховати',
  'home.random.kicker': 'Випадкова подія',
  'home.random.more': 'Читати далі',
  'home.random.again': 'Інша подія',
  'home.progress.kicker': 'Ваш прогрес у вікторині',
  'home.progress.title': '{done} з {total} епох опановано',
  'home.progress.label': 'Прогрес',
  'home.progress.hint': 'Епоха вважається опанованою, якщо правильно дано щонайменше 80 відсотків відповідей.',
  'home.progress.link': 'Перейти до вікторини',
  'home.section.epochs': 'Епохи',
  'home.section.themes': 'Наскрізні теми',
  'home.section.regions': 'Регіони',
  'home.section.reference': 'Довідник',
  'home.showall': 'Показати всі',
  'home.epochs.note': 'У хронологічному порядку, від кам’яного віку до сьогодення.',
  'home.themes.note': 'Нитки, що проходять крізь тисячоліття.',
  'home.hub.glossary.title': 'Глосарій',
  'home.hub.glossary.sub': '{terms} коротко пояснено',
  'home.hub.search.title': 'Пошук',
  'home.hub.search.sub': 'Події, особи, теми, терміни',
  'home.hub.bookmarks.title': 'Закладки',
  'home.hub.bookmarks.sub': 'Збережені вами елементи',

  'epochs.title': 'Епохи',
  'epochs.intro': 'Всесвітня історія у {count} розділах у хронологічному порядку. Кожна епоха містить огляд, ключові події, важливих осіб та їхні наслідки.',

  'epoch.notfound': 'Ця епоха не існує.',
  'epoch.back': 'Усі епохи',
  'epoch.hero.position': 'Епоха {index} з {total}',
  'epoch.quiz.start': 'Почати вікторину',
  'epoch.quiz.best': 'Найкращий результат {best}/{total}',
  'epoch.timeline': 'На хронологічній шкалі',
  'epoch.toc.title': 'Зміст',
  'epoch.toc.aria': 'Зміст цієї епохи',
  'epoch.toc.events': 'Події',
  'epoch.toc.persons': 'Особи',
  'epoch.toc.terms': 'Терміни',
  'epoch.toc.consequences': 'Наслідки',
  'epoch.keyfacts.title': 'Коротко',
  'epoch.keyfacts.milestones': 'Віхи',
  'epoch.overview.title': 'Огляд',
  'epoch.events.title': 'Ключові події',
  'epoch.events.only': 'Лише віхи ({n})',
  'epoch.persons.title': 'Важливі особи',
  'epoch.terms.title': 'Терміни цієї епохи',
  'epoch.terms.link': 'У глосарії',
  'epoch.consequences.title': 'Наслідки та значення',
  'epoch.themes.title': 'Пов’язані наскрізні теми',
  'epoch.nav.prev': 'Попередня епоха',
  'epoch.nav.next': 'Наступна епоха',
  'epoch.nav.aria': 'Сусідні епохи',

  'event.notfound': 'Ця подія не існує.',
  'event.back': 'Епоха',
  'event.importance.major': 'Важлива подія',
  'event.importance.label': 'Значення',
  'event.persons.title': 'Причетні особи',
  'event.terms.title': 'Терміни до цієї події',
  'event.themes.title': 'Наскрізні теми',
  'event.nearby.title': 'У той самий час у цій епосі',
  'event.nav.aria': 'Хронологічні сусіди',
  'event.nav.prev': 'До',
  'event.nav.next': 'Після',

  'person.notfound': 'Ця особа не існує.',
  'person.back': 'Епоха',
  'person.events.title': 'Пов’язані події',
  'person.terms.title': 'Терміни',
  'person.themes.title': 'Наскрізні теми',
  'person.contemporaries.title': 'Сучасники',

  'bookmarks.title': 'Закладки',
  'bookmarks.empty.title': 'Поки що немає закладок',
  'bookmarks.empty.text': 'Натисніть «{save}» на епосі, події або особі, щоб зібрати їх тут.',
  'bookmarks.count': '{entries} збережено. Закладки зберігаються лише на цьому пристрої.',

  'notfound.title': 'Не знайдено',
  'notfound.heading': 'Сторінку не знайдено',
  'notfound.text': 'Ця сторінка не існує.',
  'notfound.home': 'На головну сторінку',

  'theme.label.system': 'Автоматично',
  'theme.label.light': 'Світла',
  'theme.label.dark': 'Темна',
  'theme.buttonTitle': 'Колірна схема: {name} (натисніть, щоб змінити)',

  'quiz.verdict.excellent': 'Чудово!',
  'quiz.verdict.verygood': 'Дуже добре!',
  'quiz.verdict.good': 'Добре зроблено.',
  'quiz.verdict.keepgoing': 'Тренуйтеся далі!',

  'tile.theme.kicker': 'Наскрізна тема',
  'tile.theme.events': '{events} у всіх епохах',

  'timeline.title': 'Хронологічна шкала',
  'timeline.intro': 'Усі події в хронологічному порядку, згруповані за епохами та століттями. Великі крапки позначають віхи.',
  'timeline.filter.epoch': 'Фільтр за епохою',
  'timeline.filter.region': 'Фільтр за регіоном',
  'timeline.filter.theme': 'Фільтр за темою',
  'timeline.allRegions': 'Усі регіони',
  'timeline.allThemes': 'Усі теми',
  'timeline.onlyMilestones': 'Лише віхи',
  'timeline.toTop': 'Нагору',
  'timeline.empty.title': 'Немає подій',
  'timeline.empty.text': 'Для цієї комбінації фільтрів немає записів.',

  'regions.title': 'Регіони',
  'regions.intro': 'Історія за континентами: які події та особи сформували кожен регіон світу?',
  'regions.notfound': 'Цей регіон не існує.',
  'regions.back': 'Усі регіони',
  'regions.persons.title': 'Особи з цього регіону',

  'themes.title': 'Наскрізні теми',
  'themes.intro': 'Історія крізь віки: кожна тема об’єднує події, осіб і терміни всіх епох в одну нитку – від витоків до сьогодення.',
  'themes.notfound': 'Ця тема не існує.',
  'themes.back': 'Усі теми',
  'themes.empty.title': 'Поки що немає тем',
  'themes.empty.text': 'Теми готуються.',
  'themes.empty.link': 'Перейти до епох',
  'themes.intro.title': 'Вступ',
  'themes.course.title': 'Крізь епохи',

  'glossary.title': 'Глосарій',
  'glossary.intro': '{terms} з усіх епох, в алфавітному порядку та коротко пояснені.',
  'glossary.filter': 'Фільтр термінів …',
  'glossary.letters': 'Літери',
  'glossary.allEpochs': 'Усі епохи',
  'glossary.none': 'Термінів не знайдено.',
  'glossary.empty.title': 'Поки що немає термінів',
  'glossary.empty.text': 'Глосарій готується.',

  'search.title': 'Пошук',
  'search.placeholder': 'Подія, особа, епоха, тема або термін …',
  'search.label': 'Пошуковий запит',
  'search.all': 'Усі ({n})',
  'search.hint': 'Введіть щонайменше два символи. Приклади:',
  'search.resultsFor': '{results} за запитом «{term}»',
  'search.none': 'Немає результатів за запитом «{term}».',
  'search.examples': 'Наполеон, Революція, Китай, Демократія, Берлінська стіна',
  'search.tooShort': 'Будь ласка, введіть слово щонайменше з двох літер.',

  'quiz.intro': 'Перевірте свої знання: по одній епосі або в змішаному режимі з усієї всесвітньої історії. Ваш найкращий результат зберігається на цьому пристрої.',
  'quiz.notfound': 'Ця вікторина не існує.',
  'quiz.back': 'Огляд вікторин',
  'quiz.mastered.label': 'Опановано епох (≥ 80%)',
  'quiz.mastered.value': '{done} з {total}',
  'quiz.mixed.title': 'Змішана вікторина',
  'quiz.mixed.sub': '{questions} з усіх епох',
  'quiz.epoch.sub': '{shown} з {total} питань за раунд',
  'quiz.epochTitle': 'Вікторина: {epoch}',
  'quiz.best': 'Найкращий результат',
  'quiz.notPlayed': 'Ще не грали',
  'quiz.reset': 'Скинути прогрес',
  'quiz.reset.confirm': 'Дійсно видалити ваш прогрес у вікторині?',
  'quiz.noQuestions.title': 'Немає питань',
  'quiz.noQuestions.text': 'Для цієї епохи ще немає питань.',
  'quiz.questionOf': 'Питання {n} з {total}',
  'quiz.difficulty.easy': 'Легкий',
  'quiz.difficulty.medium': 'Середній',
  'quiz.difficulty.hard': 'Складний',
  'quiz.correct': 'Правильно!',
  'quiz.wrong': 'Не зовсім. Правильна відповідь: {answer}',
  'quiz.keyHint': 'Порада: відповідайте клавішами A–D або 1–4, натисніть Enter, щоб продовжити.',
  'quiz.next': 'Далі',
  'quiz.finish': 'Результати',
  'quiz.percentCorrect': '{percent}% правильних відповідей',
  'quiz.again': 'Зіграти ще раз',
  'quiz.other': 'Інша вікторина',
  'quiz.toEpoch': 'Перейти до епохи',
  'quiz.review': 'Варто переглянути ще раз',
  'quiz.answerWas': 'Правильно: {answer} –',
  'quiz.allCorrect': 'Усі відповіді правильні – чудово!',

  'more.intro': 'Інші розділи застосунку, налаштування та інформація.',
  'more.discover': 'Огляд',
  'more.themes.sub': '{themes} у всіх епохах',
  'more.regions.sub': 'Історія за континентами',
  'more.search.sub': 'Пошук у всьому вмісті',
  'more.bookmarks.sub': '{entries} збережено',
  'more.settings': 'Налаштування',
  'more.theme.title': 'Колірна схема',
  'more.theme.action': 'Змінити',
  'more.progress.title': 'Прогрес вікторини',
  'more.progress.sub': 'Найкращі результати та спроби на цьому пристрої',
  'more.progress.action': 'Скинути',
  'more.progress.done': 'Прогрес скинуто',
  'more.offline.title': 'Офлайн-дані',
  'more.offline.sub': 'Оновити кешовані файли застосунку',
  'more.offline.action': 'Оновити',
  'more.offline.done': 'Кеш очищено – перезавантаження …',
  'more.offline.noNetwork': 'Немає підключення до інтернету – офлайн-дані збережено.',
  'more.data.title': 'Видалити всі дані',
  'more.data.sub': 'Закладки, прогрес вікторини та налаштування на цьому пристрої',
  'more.data.action': 'Видалити',
  'more.data.confirm': 'Дійсно видалити всі закладки, прогрес вікторини та налаштування на цьому пристрої?',
  'more.data.done': 'Усі дані видалено',
  'more.about.title': 'Про застосунок',
  'more.about.text': '– це навчальний застосунок про найважливіші теми минулого – від перших людей до сьогодення, на кожному континенті.',
  'more.about.note': 'Тексти узагальнюють загальноприйнятий стан досліджень і написані для школи, університету та загальної освіти. Роки до нашої ери позначено «до н. е.», приблизні дати – «бл.». Закладки та прогрес вікторини зберігаються лише на цьому пристрої.',
  'more.version': 'Версія {version} · {kind} · Працює офлайн',
  'more.kind.native': 'Версія застосунку',
  'more.kind.pwa': 'Прогресивний вебзастосунок',
  'more.privacy': 'Політика конфіденційності',
  'more.imprint': 'Правова інформація',
  'quiz.joker': 'Джокер 50:50',
  'quiz.joker.watch': 'Джокер 50:50 за коротку рекламу',
  'quiz.joker.used': 'Дві неправильні відповіді прибрано.',
  'quiz.joker.unavailable': 'Наразі реклама недоступна. Спробуйте пізніше.',
  'quiz.joker.loading': 'Завантаження реклами …',
  'more.ads.title': 'Реклама та конфіденційність',
  'more.ads.sub': 'Змінити згоду на персоналізовану рекламу',
  'more.ads.action': 'Змінити',
  'ads.label': 'Реклама',
};
