// 简体中文界面文本。
export default {
  'app.name': '世界历史',
  'app.description': '从史前到当代的世界历史：各个时代、贯穿主题、时间线、词汇表、测验、搜索和书签。可离线使用。',
  'app.skipToContent': '跳到内容',
  'app.brandAria': '世界历史 – 首页',
  'app.install': '安装应用',
  'app.installed': '应用已安装',
  'app.loading': '正在加载内容……',
  'app.loadFailed': '内容加载失败',
  'app.retry': '重试',
  'app.error': '错误',
  'app.update.available': '有新版本可用',
  'app.update.action': '重新加载',

  'nav.home': '首页',
  'nav.epochs': '时代',
  'nav.timeline': '时间线',
  'nav.themes': '主题',
  'nav.glossary': '词汇表',
  'nav.quiz': '测验',
  'nav.bookmarks': '书签',
  'nav.more': '更多',
  'nav.search': '搜索',
  'nav.aria.main': '主导航',
  'nav.aria.bottom': '导航',

  'lang.label': '语言',
  'theme.toggle': '更改配色方案',
  'theme.toast': '配色方案：{name}',
  'title.page': '{title} – 世界历史',

  'year.bc': '公元前{n}年',
  'year.ad': '公元{n}年',
  'year.approx': '约{s}',
  'year.unknown': '？',
  'year.today': '今天',

  'unit.event.one': '个事件',
  'unit.event.other': '个事件',
  'unit.person.one': '位人物',
  'unit.person.other': '位人物',
  'unit.term.one': '个术语',
  'unit.term.other': '个术语',
  'unit.theme.one': '个主题',
  'unit.theme.other': '个主题',
  'unit.epoch.one': '个时代',
  'unit.epoch.other': '个时代',
  'unit.entry.one': '条记录',
  'unit.entry.other': '条记录',
  'unit.hit.one': '个结果',
  'unit.hit.other': '个结果',
  'unit.question.one': '个问题',
  'unit.question.other': '个问题',
  'unit.region.one': '个地区',
  'unit.region.other': '个地区',
  'unit.attempt.one': '次尝试',
  'unit.attempt.other': '次尝试',

  'heading.events': '事件',
  'heading.persons': '人物',
  'heading.terms': '术语',

  'century.earliest': '公元前10000年之前',
  'century.bc': '公元前{n}世纪',
  'century.ad': '{n}世纪',

  'ui.milestone': '里程碑',
  'ui.bookmark.save': '保存',
  'ui.bookmark.saved': '已保存',
  'toast.bookmark.added': '书签已保存',
  'toast.bookmark.removed': '书签已移除',

  'home.intro': '从最早的人类到今天，涵盖过去所有重要主题。按时代、贯穿主题和地区编排，配有时间线、词汇表和测验。',
  'home.stat.quiz': '测验题目',
  'home.cta.epochs': '探索各个时代',
  'home.cta.timeline': '时间线',
  'home.cta.quiz': '开始测验',
  'home.install.title': '安装为应用',
  'home.install.ios': '在 Safari 中点击“分享”，然后选择“添加到主屏幕”。之后该应用也可离线使用。',
  'home.install.android': '将{name}安装到主屏幕。这样该应用也可离线使用。',
  'home.install.action': '安装',
  'home.install.dismiss': '隐藏',
  'home.random.kicker': '随机事件',
  'home.random.more': '阅读更多',
  'home.random.again': '换一个事件',
  'home.progress.kicker': '您的测验进度',
  'home.progress.title': '已掌握 {total} 个时代中的 {done} 个',
  'home.progress.label': '进度',
  'home.progress.hint': '当您至少答对80%的问题时，该时代即视为已掌握。',
  'home.progress.link': '前往测验',
  'home.section.epochs': '时代',
  'home.section.themes': '贯穿主题',
  'home.section.regions': '地区',
  'home.section.reference': '参考资料',
  'home.showall': '显示全部',
  'home.epochs.note': '按时间顺序排列，从石器时代到今天。',
  'home.themes.note': '贯穿数千年的主线。',
  'home.hub.glossary.title': '词汇表',
  'home.hub.glossary.sub': '简明解释{terms}',
  'home.hub.search.title': '搜索',
  'home.hub.search.sub': '事件、人物、主题、术语',
  'home.hub.bookmarks.title': '书签',
  'home.hub.bookmarks.sub': '您保存的内容',

  'epochs.title': '时代',
  'epochs.intro': '世界历史分为{count}个部分，按时间顺序排列。每个时代都包含概述、关键事件、重要人物及其影响。',

  'epoch.notfound': '该时代不存在。',
  'epoch.back': '所有时代',
  'epoch.hero.position': '第 {index} 个时代，共 {total} 个',
  'epoch.quiz.start': '开始测验',
  'epoch.quiz.best': '最佳成绩 {best}/{total}',
  'epoch.timeline': '在时间线上',
  'epoch.toc.title': '目录',
  'epoch.toc.aria': '本时代的目录',
  'epoch.toc.events': '事件',
  'epoch.toc.persons': '人物',
  'epoch.toc.terms': '术语',
  'epoch.toc.consequences': '影响',
  'epoch.keyfacts.title': '概览',
  'epoch.keyfacts.milestones': '里程碑',
  'epoch.overview.title': '概述',
  'epoch.events.title': '关键事件',
  'epoch.events.only': '仅显示里程碑（{n}）',
  'epoch.persons.title': '重要人物',
  'epoch.terms.title': '本时代的术语',
  'epoch.terms.link': '在词汇表中查看',
  'epoch.consequences.title': '影响与意义',
  'epoch.themes.title': '相关贯穿主题',
  'epoch.nav.prev': '上一个时代',
  'epoch.nav.next': '下一个时代',
  'epoch.nav.aria': '相邻时代',

  'event.notfound': '该事件不存在。',
  'event.back': '时代',
  'event.importance.major': '重大事件',
  'event.importance.label': '重要性',
  'event.persons.title': '相关人物',
  'event.terms.title': '与该事件相关的术语',
  'event.themes.title': '贯穿主题',
  'event.nearby.title': '同一时代的同期事件',
  'event.nav.aria': '相邻时间的事件',
  'event.nav.prev': '之前',
  'event.nav.next': '之后',

  'person.notfound': '该人物不存在。',
  'person.back': '时代',
  'person.events.title': '相关事件',
  'person.terms.title': '术语',
  'person.themes.title': '贯穿主题',
  'person.contemporaries.title': '同时代人物',

  'bookmarks.title': '书签',
  'bookmarks.empty.title': '还没有书签',
  'bookmarks.empty.text': '在时代、事件或人物页面点击“{save}”，即可在此处收藏它们。',
  'bookmarks.count': '已保存 {entries} 个。书签仅存储在此设备上。',

  'notfound.title': '未找到',
  'notfound.heading': '页面未找到',
  'notfound.text': '该页面不存在。',
  'notfound.home': '前往首页',

  'theme.label.system': '自动',
  'theme.label.light': '浅色',
  'theme.label.dark': '深色',
  'theme.buttonTitle': '配色方案：{name}（点击更改）',

  'quiz.verdict.excellent': '太棒了！',
  'quiz.verdict.verygood': '非常好！',
  'quiz.verdict.good': '做得好。',
  'quiz.verdict.keepgoing': '继续加油！',

  'tile.theme.kicker': '贯穿主题',
  'tile.theme.events': '贯穿所有时代的{events}',

  'timeline.title': '时间线',
  'timeline.intro': '所有事件按时间顺序排列，并按时代和世纪分组。较大的圆点标记里程碑。',
  'timeline.filter.epoch': '按时代筛选',
  'timeline.filter.region': '按地区筛选',
  'timeline.filter.theme': '按主题筛选',
  'timeline.allRegions': '所有地区',
  'timeline.allThemes': '所有主题',
  'timeline.onlyMilestones': '仅显示里程碑',
  'timeline.toTop': '返回顶部',
  'timeline.empty.title': '没有事件',
  'timeline.empty.text': '没有符合此筛选组合的记录。',

  'regions.title': '地区',
  'regions.intro': '按大洲划分的历史：哪些事件和人物塑造了世界的每个地区？',
  'regions.notfound': '该地区不存在。',
  'regions.back': '所有地区',
  'regions.persons.title': '来自该地区的人物',

  'themes.title': '贯穿主题',
  'themes.intro': '跨越时代阅读历史：每个主题都将所有时代的事件、人物和术语串联成一条线索——从起源到今天。',
  'themes.notfound': '该主题不存在。',
  'themes.back': '所有主题',
  'themes.empty.title': '暂无主题',
  'themes.empty.text': '主题正在编写中。',
  'themes.empty.link': '前往时代',
  'themes.intro.title': '简介',
  'themes.course.title': '贯穿各个时代',

  'glossary.title': '词汇表',
  'glossary.intro': '涵盖所有时代的{terms}，按字母顺序排列并附有简明解释。',
  'glossary.filter': '筛选术语……',
  'glossary.letters': '字母',
  'glossary.allEpochs': '所有时代',
  'glossary.none': '未找到术语。',
  'glossary.empty.title': '暂无术语',
  'glossary.empty.text': '词汇表正在编写中。',

  'search.title': '搜索',
  'search.placeholder': '事件、人物、时代、主题或术语……',
  'search.label': '搜索词',
  'search.all': '全部（{n}）',
  'search.hint': '请至少输入两个字符。示例：',
  'search.resultsFor': '“{term}”的{results}',
  'search.none': '未找到与“{term}”相关的结果。',
  'search.examples': '拿破仑、革命、中国、民主、柏林墙',
  'search.tooShort': '请输入至少两个字母的词语。',

  'quiz.intro': '测试您的知识：可选择单个时代，也可混合整个世界历史。您的最佳成绩会保存在此设备上。',
  'quiz.notfound': '该测验不存在。',
  'quiz.back': '测验总览',
  'quiz.mastered.label': '已掌握的时代（≥ 80%）',
  'quiz.mastered.value': '{total}个中的{done}个',
  'quiz.mixed.title': '混合测验',
  'quiz.mixed.sub': '来自所有时代的{questions}',
  'quiz.epoch.sub': '每轮{total}个问题中的{shown}个',
  'quiz.epochTitle': '测验：{epoch}',
  'quiz.best': '最佳成绩',
  'quiz.notPlayed': '尚未进行',
  'quiz.reset': '重置进度',
  'quiz.reset.confirm': '确定要删除您的测验进度吗？',
  'quiz.noQuestions.title': '没有问题',
  'quiz.noQuestions.text': '该时代目前还没有问题。',
  'quiz.questionOf': '第 {n} 题，共 {total} 题',
  'quiz.difficulty.easy': '简单',
  'quiz.difficulty.medium': '中等',
  'quiz.difficulty.hard': '困难',
  'quiz.correct': '回答正确！',
  'quiz.wrong': '不太对。正确答案是：{answer}',
  'quiz.keyHint': '提示：可用按键 A–D 或 1–4 作答，按 Enter 继续。',
  'quiz.next': '下一题',
  'quiz.finish': '结果',
  'quiz.percentCorrect': '正确率 {percent}%',
  'quiz.again': '再玩一次',
  'quiz.other': '换个测验',
  'quiz.toEpoch': '前往该时代',
  'quiz.review': '值得再看一遍',
  'quiz.answerWas': '正确答案：{answer} –',
  'quiz.allCorrect': '全部答对——太棒了！',

  'more.intro': '应用的更多功能、设置和信息。',
  'more.discover': '探索',
  'more.themes.sub': '贯穿所有时代的{themes}',
  'more.regions.sub': '按大洲划分的历史',
  'more.search.sub': '搜索全部内容',
  'more.bookmarks.sub': '已保存 {entries} 个',
  'more.settings': '设置',
  'more.theme.title': '配色方案',
  'more.theme.action': '更改',
  'more.progress.title': '测验进度',
  'more.progress.sub': '此设备上的最佳成绩和尝试次数',
  'more.progress.action': '重置',
  'more.progress.done': '进度已重置',
  'more.offline.title': '离线数据',
  'more.offline.sub': '刷新已缓存的应用文件',
  'more.offline.action': '刷新',
  'more.offline.done': '缓存已清除——正在重新加载……',
  'more.offline.noNetwork': '没有网络连接——离线数据将被保留。',
  'more.data.title': '删除所有数据',
  'more.data.sub': '此设备上的书签、测验进度和设置',
  'more.data.action': '删除',
  'more.data.confirm': '确定要删除此设备上的所有书签、测验进度和设置吗？',
  'more.data.done': '所有数据已删除',
  'more.about.title': '关于本应用',
  'more.about.text': '是一款学习应用，涵盖过去所有重要主题——从最早的人类到今天，覆盖每一个大洲。',
  'more.about.note': '文本内容总结了普遍认可的研究成果，适合学校、大学及大众教育使用。公元前的年份标注为“公元前”，大致日期标注为“约”。书签和测验进度仅保存在此设备上。',
  'more.version': '版本 {version} · {kind} · 可离线使用',
  'more.kind.native': '应用版本',
  'more.kind.pwa': '渐进式网络应用',
  'more.privacy': '隐私政策',
  'more.imprint': '法律声明',
  'quiz.joker': '50:50 提示卡',
  'quiz.joker.watch': '观看短广告获得 50:50 提示卡',
  'quiz.joker.used': '已排除两个错误答案。',
  'quiz.joker.unavailable': '当前没有可用的广告，请稍后再试。',
  'quiz.joker.loading': '正在加载广告……',
  'more.ads.title': '广告与隐私',
  'more.ads.sub': '更改个性化广告的同意设置',
  'more.ads.action': '更改',
  'ads.label': '广告',
};
